import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.98.0';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type, x-finlo-monitor-secret','Access-Control-Allow-Methods':'POST, OPTIONS'};
const out=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...cors,'Content-Type':'application/json'}});
const hex=(b:ArrayBuffer)=>Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,'0')).join('');
const sha=async(b:ArrayBuffer)=>hex(await crypto.subtle.digest('SHA-256',b));
const normalize=(html:string)=>html.replace(/<script[\s\S]*?<\/script>/gi,'').replace(/<style[\s\S]*?<\/style>/gi,'').replace(/\s+/g,' ').trim();
Deno.serve(async req=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return out({error:'Method not allowed'},405);
 const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;if(!url||!anon||!service)return out({error:'Server configuration incomplete'},500);
 const admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});const supplied=req.headers.get('x-finlo-monitor-secret')||'';const suppliedHash=supplied?await sha(new TextEncoder().encode(supplied).buffer):'';let actor:string|null=null,scheduled=false;
 if(suppliedHash==='a92ab7c4574a89ee6d46a8743ea2721197d60705643f9a0435169e5bee7cbcfa'){scheduled=true}else{const auth=req.headers.get('Authorization')||'';const client=createClient(url,anon,{global:{headers:{Authorization:auth}}});const {data:{user}}=await client.auth.getUser();if(!user)return out({error:'Not authenticated'},401);const {data:p}=await client.from('profiles').select('is_super_admin').eq('id',user.id).single();if(!p?.is_super_admin)return out({error:'Super Admin access required'},403);actor=user.id;}
 const {data:sources,error}=await admin.from('business_tax_compliance_sources').select('*').eq('active',true);if(error)return out({error:error.message},500);const results:any[]=[];
 for(const s of sources||[]){const checked=new Date().toISOString();try{const r=await fetch(s.source_url,{headers:{'User-Agent':'Finlo-Business-Tax-Compliance-Monitor/1.0'}});if(!r.ok)throw new Error(`Official source returned HTTP ${r.status}`);const text=normalize(await r.text());if(text.length<500)throw new Error('Official source content was unexpectedly short');const fp=await sha(new TextEncoder().encode(text).buffer),previous=s.last_known_fingerprint||null,changed=!!previous&&previous!==fp;if(changed){await admin.from('business_tax_compliance_updates').upsert({source_id:s.id,country_code:s.country_code,source_fingerprint:fp,previous_fingerprint:previous,status:'review_required',summary:'Official Business Tax/GST source changed — manual review required',source_reference:s.source_url,updated_at:checked},{onConflict:'source_id,source_fingerprint',ignoreDuplicates:true});}await admin.from('business_tax_compliance_sources').update({last_checked_at:checked,last_successful_check_at:checked,last_changed_at:changed?checked:s.last_changed_at,last_known_fingerprint:fp,last_check_status:changed?'change_detected':'no_change',last_error:null,updated_at:checked}).eq('id',s.id);results.push({source_id:s.id,country:s.country_code,status:changed?'change_detected':'no_change',source_reference:s.source_url});}catch(e){const msg=e instanceof Error?e.message:'Source check failed';await admin.from('business_tax_compliance_sources').update({last_checked_at:checked,last_check_status:'check_error',last_error:msg.slice(0,500),updated_at:checked}).eq('id',s.id);results.push({source_id:s.id,country:s.country_code,status:'check_error',error:msg});}}
 return out({ok:true,scheduled,actor:actor?true:false,results});
});
