const ORIGINAL_LOGO='assets/careclean-logo.jpg';
const DEFAULT_PRODUCTS=[
  {name:'Regular Cleaning - Fortnightly',price:0},{name:'Regular Cleaning - Weekly',price:0},{name:'Move In Clean',price:0},{name:'Move Out Clean',price:0},{name:'Deep Clean',price:0},{name:'Carpet Clean',price:0},{name:'Commercial Cleaning Service',price:0},{name:'Oven Cleaning',price:0},{name:'Refrigerator Cleaning',price:0},{name:'Other',price:0}
];
const DEFAULT_SETTINGS={
  company:'Care New Zealand Limited',trading:'CareClean',address:'120 Melksham Drive, Churton Park, Wellington 6037',phone:'027 499 4445',email:'info@careclean.co.nz',gstNumber:'',dueDays:3,
  bankAccounts:[{name:'CareClean Main Account',account:'02-0506-0400503-000',isDefault:true}],
  products:DEFAULT_PRODUCTS,template:'classic',theme:'careclean',primaryColor:'#082f4f',accentColor:'#72bf2e',logoData:'',supabaseUrl:'',supabaseKey:'',
  invoiceText:{invoiceTitle:'INVOICE',billTo:'Bill To',invoiceNumber:'Invoice #',invoiceDate:'Invoice date',dueDate:'Due date',description:'Description',qty:'Qty',unitPrice:'Unit (ex GST)',lineTotal:'Amount',subtotal:'Subtotal (ex GST)',gst:'GST (15%)',total:'Total',paymentTo:'Payment to',paymentReference:'Payment reference',paymentInstruction:'Please use the invoice number above as your bank payment reference.',defaultNote:'Thank you for choosing CareClean. Please pay within 3 days.'}
};
let stored={};try{stored=JSON.parse(localStorage.getItem('cc_settings')||'{}')}catch{}
if(stored.bankAccount && !stored.bankAccounts) stored.bankAccounts=[{name:'CareClean Main Account',account:stored.bankAccount,isDefault:true}];
let settings={...DEFAULT_SETTINGS,...stored};
settings.bankAccounts=Array.isArray(settings.bankAccounts)&&settings.bankAccounts.length?settings.bankAccounts:DEFAULT_SETTINGS.bankAccounts.map(x=>({...x}));
settings.products=Array.isArray(settings.products)&&settings.products.length?settings.products:DEFAULT_PRODUCTS.map(x=>({...x}));
settings.invoiceText={...DEFAULT_SETTINGS.invoiceText,...(settings.invoiceText||{})};
let sb=null,currentId=null,items=[];
const $=id=>document.getElementById(id); const money=n=>'$'+Number(n||0).toFixed(2); const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2300)}
function initSupabase(){try{sb=settings.supabaseUrl&&settings.supabaseKey?window.supabase.createClient(settings.supabaseUrl,settings.supabaseKey):null}catch{sb=null}}
function invoiceNo(){const d=new Date(),p=n=>String(n).padStart(2,'0');return `CC-${d.getFullYear()}${p(d.getMonth()+1)}${p(d.getDate())}-${String(Math.floor(Math.random()*9000)+1000)}`}
function isoDate(d=new Date()){return d.toISOString().slice(0,10)}
function addDays(dateStr,days){let d=dateStr?new Date(dateStr+'T12:00:00'):new Date();d.setDate(d.getDate()+Number(days||0));return isoDate(d)}
function logoSrc(){return settings.logoData||ORIGINAL_LOGO}
function defaultBank(){return settings.bankAccounts.find(x=>x.isDefault)||settings.bankAccounts[0]||{name:'',account:''}}
function applyBranding(){
  document.documentElement.style.setProperty('--navy',settings.primaryColor||'#082f4f');document.documentElement.style.setProperty('--green',settings.accentColor||'#72bf2e');
  $('brandLogo').src=logoSrc();
}
function newInvoice(){
  currentId=null;$('invoiceNumber').value=invoiceNo();$('invoiceDate').value=isoDate();$('dueDate').value=addDays($('invoiceDate').value,settings.dueDays??3);
  ['customerName','customerAddress','customerEmail','reference'].forEach(id=>$(id).value='');$('customerNote').value=(settings.invoiceText.defaultNote||`Thank you for choosing ${settings.trading||'CareClean'}. Please pay within ${settings.dueDays??3} days.`).replace(/\{dueDays\}/g,String(settings.dueDays??3)).replace(/\{tradingName\}/g,settings.trading||'CareClean');items=[];addItem();recalc()
}
function addItem(data){
  const first=settings.products[0]||{name:'Other',price:0};
  items.push(data?{...data}:{description:first.name,custom:'',qty:1,unit_price:Number(first.price||0)});renderItems()
}
function renderItems(){
  const root=$('items');const products=settings.products.length?settings.products:DEFAULT_PRODUCTS;
  const listId='productOptions';
  root.innerHTML=`<datalist id="${listId}">${products.map(s=>`<option value="${esc(s.name)}"></option>`).join('')}</datalist><div class="items-header"><span>Description</span><span>Qty</span><span>Unit price (ex GST)</span><span>Line total</span><span></span></div>`+items.map((it,i)=>`<div class="item-row"><div class="desc-wrap"><input list="${listId}" data-i="${i}" data-k="description" placeholder="Select a service or type any description" value="${esc(it.description)}"><input data-i="${i}" data-k="custom" placeholder="Optional extra detail" value="${esc(it.custom)}"></div><input type="number" min="0" step="1" data-i="${i}" data-k="qty" value="${it.qty}"><input type="number" min="0" step="0.01" data-i="${i}" data-k="unit_price" value="${it.unit_price}"><div class="line-total">${money(it.qty*it.unit_price)}</div><button class="remove" data-remove="${i}" title="Remove">×</button></div>`).join('');
  root.querySelectorAll('input').forEach(el=>el.addEventListener('input',e=>{let i=+e.target.dataset.i,k=e.target.dataset.k;if(!k)return;items[i][k]=(k==='qty'||k==='unit_price')?Number(e.target.value):e.target.value;if(k==='description'){const p=products.find(x=>x.name.toLowerCase()===String(e.target.value).trim().toLowerCase());if(p){items[i].unit_price=Number(p.price||0);const priceInput=root.querySelector(`input[data-i="${i}"][data-k="unit_price"]`);if(priceInput)priceInput.value=items[i].unit_price}}recalc();const row=e.target.closest('.item-row');if(row)row.querySelector('.line-total').textContent=money(items[i].qty*items[i].unit_price)}));
  root.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{items.splice(+b.dataset.remove,1);if(!items.length)addItem();else{renderItems();recalc()}})
}
function totals(){const subtotal=items.reduce((a,x)=>a+(Number(x.qty)||0)*(Number(x.unit_price)||0),0),gst=subtotal*.15;return{subtotal,gst,total:subtotal+gst}}
function recalc(){const t=totals();$('subtotal').textContent=money(t.subtotal);$('gst').textContent=money(t.gst);$('total').textContent=money(t.total)}
function payload(){const t=totals();return{id:currentId,invoice_number:$('invoiceNumber').value,invoice_date:$('invoiceDate').value,due_date:$('dueDate').value,customer_name:$('customerName').value.trim(),customer_address:$('customerAddress').value.trim(),customer_email:$('customerEmail').value.trim(),reference:$('reference').value.trim(),customer_note:$('customerNote').value.trim(),items,subtotal:t.subtotal,gst:t.gst,total:t.total,company_snapshot:settings,updated_at:new Date().toISOString()}}
function validate(){if(!$('customerName').value.trim())return toast('Please enter customer name'),false;if(!$('customerAddress').value.trim())return toast('Please enter customer address'),false;if(!items.some(x=>x.qty>0&&x.unit_price>=0))return toast('Please add at least one invoice item'),false;return true}
async function save(p=payload()){if(!validate())return null;if(sb){const row={...p};delete row.id;let r=currentId?await sb.from('invoices').update(row).eq('id',currentId).select().single():await sb.from('invoices').insert(row).select().single();if(r.error){toast('Supabase error: '+r.error.message);return null}currentId=r.data.id;return r.data}else{let arr=JSON.parse(localStorage.getItem('cc_invoices')||'[]');if(currentId){let idx=arr.findIndex(x=>x.id===currentId);if(idx>=0)arr[idx]={...p,id:currentId}}else{currentId=crypto.randomUUID();arr.unshift({...p,id:currentId,created_at:new Date().toISOString()})}localStorage.setItem('cc_invoices',JSON.stringify(arr));return {...p,id:currentId}}}
async function allInvoices(){if(sb){let {data,error}=await sb.from('invoices').select('*').order('created_at',{ascending:false});if(error){toast(error.message);return[]}return data||[]}return JSON.parse(localStorage.getItem('cc_invoices')||'[]')}
function pdfColors(){const hex=(settings.primaryColor||'#082f4f').replace('#','');return [parseInt(hex.slice(0,2),16),parseInt(hex.slice(2,4),16),parseInt(hex.slice(4,6),16)]}
function makePdf(inv=payload(),output='save'){
  const snap=inv.company_snapshot||settings,bank=(snap.bankAccounts||settings.bankAccounts||[]).find(x=>x.isDefault)||(snap.bankAccounts||settings.bankAccounts||[])[0]||defaultBank();
  const t={...DEFAULT_SETTINGS.invoiceText,...(snap.invoiceText||settings.invoiceText||{})};
  const {jsPDF}=window.jspdf;const doc=new jsPDF({unit:'mm',format:'a4'});const color=pdfColors();
  try{doc.addImage(snap.logoData||logoSrc(),15,12,45,45)}catch{}
  doc.setTextColor(...color);doc.setFontSize(24);doc.text(t.invoiceTitle||'INVOICE',195,20,{align:'right'});doc.setFontSize(10);doc.setTextColor(40,55,65);doc.text(snap.company||settings.company,195,29,{align:'right'});doc.text(snap.address||settings.address,195,35,{align:'right'});doc.text(`${snap.phone||settings.phone}  |  ${snap.email||settings.email}`,195,41,{align:'right'});doc.text(`GST No: ${snap.gstNumber||'Not set'}`,195,47,{align:'right'});doc.setDrawColor(...color);doc.line(15,62,195,62);
  doc.setFontSize(10);doc.text(`${t.invoiceNumber||'Invoice #'}: ${inv.invoice_number}`,15,72);doc.text(`${t.invoiceDate||'Invoice date'}: ${inv.invoice_date}`,15,78);doc.text(`${t.dueDate||'Due date'}: ${inv.due_date}`,15,84);doc.setFont(undefined,'bold');doc.text(t.billTo||'Bill To',120,72);doc.setFont(undefined,'normal');doc.text(inv.customer_name||'',120,78);doc.text(doc.splitTextToSize(inv.customer_address||'',75),120,84);
  const body=(inv.items||[]).map(x=>[x.custom?`${x.description} - ${x.custom}`:x.description,String(x.qty),money(x.unit_price),money(x.qty*x.unit_price)]);
  const template=snap.template||settings.template||'classic';const theme=template==='minimal'?'plain':'grid';doc.autoTable({startY:105,head:[[t.description||'Description',t.qty||'Qty',t.unitPrice||'Unit (ex GST)',t.lineTotal||'Amount']],body,theme,headStyles:{fillColor:template==='minimal'?[245,247,249]:color,textColor:template==='minimal'?[30,48,63]:[255,255,255]},styles:{fontSize:9},columnStyles:{1:{halign:'right'},2:{halign:'right'},3:{halign:'right'}}});
  let y=doc.lastAutoTable.finalY+10;doc.text(`${t.subtotal||'Subtotal (ex GST)'}: ${money(inv.subtotal)}`,195,y,{align:'right'});doc.text(`${t.gst||'GST (15%)'}: ${money(inv.gst)}`,195,y+6,{align:'right'});doc.setFont(undefined,'bold');doc.setFontSize(12);doc.text(`${t.total||'Total'}: ${money(inv.total)}`,195,y+14,{align:'right'});doc.setFontSize(9);doc.setFont(undefined,'normal');
  doc.text(`${t.paymentTo||'Payment to'}: ${bank.name?bank.name+' — ':''}${bank.account||'Bank account not set'}`,15,y+28);doc.setFont(undefined,'bold');doc.text(`${t.paymentReference||'Payment reference'}: ${inv.invoice_number}`,15,y+34);doc.setFont(undefined,'normal');if(t.paymentInstruction)doc.text(doc.splitTextToSize(t.paymentInstruction,175),15,y+40);if(inv.customer_note)doc.text(doc.splitTextToSize(inv.customer_note,175),15,y+52);
  const filename=`${inv.invoice_number}-${(inv.customer_name||'customer').replace(/[^a-z0-9]/gi,'_')}.pdf`;if(output==='blob')return{blob:doc.output('blob'),filename,base64:doc.output('datauristring').split(',')[1]};doc.save(filename)
}
function previewHtml(inv){
  const snap=inv.company_snapshot||settings,accounts=snap.bankAccounts||settings.bankAccounts,bank=accounts.find(x=>x.isDefault)||accounts[0]||defaultBank();
  const t={...DEFAULT_SETTINGS.invoiceText,...(snap.invoiceText||settings.invoiceText||{})};
  return `<div class="inv-preview template-${esc(snap.template||settings.template)}"><div class="inv-preview-head"><img src="${esc(snap.logoData||logoSrc())}"><div class="inv-company"><strong>${esc(snap.company||settings.company)}</strong><br>${esc(snap.address||settings.address)}<br>${esc(snap.phone||settings.phone)} · ${esc(snap.email||settings.email)}<br>GST No: ${esc(snap.gstNumber||'Not set')}</div></div><div class="inv-title"><div><h2>${esc(t.invoiceTitle||'INVOICE')}</h2><div>${esc(inv.invoice_number)}</div></div><div><strong>${esc(t.billTo||'Bill To')}</strong><br>${esc(inv.customer_name)}<br>${esc(inv.customer_address).replace(/\n/g,'<br>')}</div></div><p><strong>${esc(t.invoiceDate||'Invoice date')}:</strong> ${esc(inv.invoice_date)} &nbsp; <strong>${esc(t.dueDate||'Due date')}:</strong> ${esc(inv.due_date)}</p><table class="inv-table"><thead><tr><th>${esc(t.description||'Description')}</th><th>${esc(t.qty||'Qty')}</th><th>${esc(t.unitPrice||'Unit (ex GST)')}</th><th>${esc(t.lineTotal||'Amount')}</th></tr></thead><tbody>${inv.items.map(x=>`<tr><td>${esc(x.description)}${x.custom?' — '+esc(x.custom):''}</td><td>${x.qty}</td><td>${money(x.unit_price)}</td><td>${money(x.qty*x.unit_price)}</td></tr>`).join('')}</tbody></table><div class="inv-summary"><div><span>${esc(t.subtotal||'Subtotal (ex GST)')}</span><span>${money(inv.subtotal)}</span></div><div><span>${esc(t.gst||'GST (15%)')}</span><span>${money(inv.gst)}</span></div><div class="grand"><span>${esc(t.total||'Total')}</span><span>${money(inv.total)}</span></div></div><div class="inv-footer"><strong>${esc(t.paymentTo||'Payment to')}:</strong> ${esc(bank.name?bank.name+' — ':'')}${esc(bank.account||'Bank account not set')}<br><strong>${esc(t.paymentReference||'Payment reference')}:</strong> ${esc(inv.invoice_number)}<br><span>${esc(t.paymentInstruction||'')}</span>${inv.customer_note?'<p>'+esc(inv.customer_note)+'</p>':''}</div></div>`
}
async function renderInvoiceList(){let arr=await allInvoices(),month=$('filterMonth').value,q=$('filterSearch').value.toLowerCase();arr=arr.filter(x=>(!month||String(x.invoice_date).startsWith(month))&&(!q||[x.customer_name,x.customer_address,x.invoice_number].join(' ').toLowerCase().includes(q)));let net=0,gst=0,total=0;arr.forEach(x=>{net+=+x.subtotal;gst+=+x.gst;total+=+x.total});$('sumNet').textContent=money(net);$('sumGst').textContent=money(gst);$('sumTotal').textContent=money(total);$('sumCount').textContent=arr.length;$('invoiceRows').innerHTML=arr.map(x=>`<tr><td>${esc(x.invoice_date)}</td><td><strong>${esc(x.invoice_number)}</strong></td><td>${esc(x.customer_name)}</td><td>${esc(x.customer_address)}</td><td>${money(x.subtotal)}</td><td>${money(x.gst)}</td><td><strong>${money(x.total)}</strong></td><td><div class="row-actions"><button class="secondary" data-view-id="${x.id}">View</button><button class="secondary" data-edit-id="${x.id}">Edit</button><button class="danger" data-del-id="${x.id}">Delete</button></div></td></tr>`).join('')||'<tr><td colspan="8">No invoices found.</td></tr>';$('invoiceRows').querySelectorAll('[data-view-id]').forEach(b=>b.onclick=async()=>{let x=(await allInvoices()).find(i=>i.id===b.dataset.viewId);$('modalContent').innerHTML=previewHtml(x);$('invoiceModal').classList.add('open')});$('invoiceRows').querySelectorAll('[data-edit-id]').forEach(b=>b.onclick=async()=>{let x=(await allInvoices()).find(i=>i.id===b.dataset.editId);loadForEdit(x)});$('invoiceRows').querySelectorAll('[data-del-id]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this invoice?'))return;if(sb)await sb.from('invoices').delete().eq('id',b.dataset.delId);else{let a=await allInvoices();localStorage.setItem('cc_invoices',JSON.stringify(a.filter(x=>x.id!==b.dataset.delId)))}renderInvoiceList();toast('Invoice deleted')})}
function loadForEdit(x){currentId=x.id;$('invoiceNumber').value=x.invoice_number;$('invoiceDate').value=x.invoice_date;$('dueDate').value=x.due_date;$('customerName').value=x.customer_name;$('customerAddress').value=x.customer_address;$('customerEmail').value=x.customer_email||'';$('reference').value=x.reference||'';$('customerNote').value=x.customer_note||'';items=x.items||[];renderItems();recalc();switchView('create');toast('Invoice loaded for editing')}
function switchView(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$('view-'+v).classList.add('active');document.querySelectorAll('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.view===v));if(v==='invoices')renderInvoiceList();if(v==='settings')loadSettingsForm()}
function loadSettingsForm(){
  [['sCompany','company'],['sTrading','trading'],['sAddress','address'],['sPhone','phone'],['sEmail','email'],['sGst','gstNumber'],['sDueDays','dueDays'],['sTemplate','template'],['sTheme','theme'],['sPrimary','primaryColor'],['sAccent','accentColor'],['sSupabaseUrl','supabaseUrl'],['sSupabaseKey','supabaseKey']].forEach(([id,k])=>$(id).value=settings[k]??'');
  const textIds={sTextInvoiceTitle:'invoiceTitle',sTextBillTo:'billTo',sTextInvoiceNumber:'invoiceNumber',sTextInvoiceDate:'invoiceDate',sTextDueDate:'dueDate',sTextDescription:'description',sTextQty:'qty',sTextUnitPrice:'unitPrice',sTextLineTotal:'lineTotal',sTextSubtotal:'subtotal',sTextGst:'gst',sTextTotal:'total',sTextPaymentTo:'paymentTo',sTextPaymentReference:'paymentReference',sTextPaymentInstruction:'paymentInstruction',sTextDefaultNote:'defaultNote'};Object.entries(textIds).forEach(([id,k])=>$(id).value=settings.invoiceText[k]??DEFAULT_SETTINGS.invoiceText[k]);
  $('settingsLogoPreview').src=logoSrc();renderBankSettings();renderProductSettings();renderSettingsPreview()
}
function renderBankSettings(){
  $('bankSettings').innerHTML=settings.bankAccounts.map((b,i)=>`<div class="settings-row bank-row"><label>Account label<input data-bank-i="${i}" data-bank-k="name" value="${esc(b.name)}"></label><label>Account number<input data-bank-i="${i}" data-bank-k="account" value="${esc(b.account)}"></label><label class="default-check"><input type="radio" name="defaultBank" data-default-bank="${i}" ${b.isDefault?'checked':''}> Default</label><button class="danger" type="button" data-remove-bank="${i}">Remove</button></div>`).join('');
  $('bankSettings').querySelectorAll('[data-bank-k]').forEach(x=>x.oninput=e=>settings.bankAccounts[+e.target.dataset.bankI][e.target.dataset.bankK]=e.target.value);
  $('bankSettings').querySelectorAll('[data-default-bank]').forEach(x=>x.onchange=e=>settings.bankAccounts.forEach((b,j)=>b.isDefault=j===+e.target.dataset.defaultBank));
  $('bankSettings').querySelectorAll('[data-remove-bank]').forEach(x=>x.onclick=()=>{if(settings.bankAccounts.length===1)return toast('Keep at least one bank account');settings.bankAccounts.splice(+x.dataset.removeBank,1);if(!settings.bankAccounts.some(b=>b.isDefault))settings.bankAccounts[0].isDefault=true;renderBankSettings()})
}
function renderProductSettings(){
  $('productSettings').innerHTML=settings.products.map((p,i)=>`<div class="settings-row product-row"><label>Product / service<input data-product-i="${i}" data-product-k="name" value="${esc(p.name)}"></label><label>Default price ex GST<input type="number" min="0" step="0.01" data-product-i="${i}" data-product-k="price" value="${Number(p.price||0)}"></label><button class="danger" type="button" data-remove-product="${i}">Remove</button></div>`).join('');
  $('productSettings').querySelectorAll('[data-product-k]').forEach(x=>x.oninput=e=>settings.products[+e.target.dataset.productI][e.target.dataset.productK]=e.target.dataset.productK==='price'?Number(e.target.value):e.target.value);
  $('productSettings').querySelectorAll('[data-remove-product]').forEach(x=>x.onclick=()=>{if(settings.products.length===1)return toast('Keep at least one product');settings.products.splice(+x.dataset.removeProduct,1);renderProductSettings()})
}
function settingsDraft(){
  const invoiceText={invoiceTitle:$('sTextInvoiceTitle').value,billTo:$('sTextBillTo').value,invoiceNumber:$('sTextInvoiceNumber').value,invoiceDate:$('sTextInvoiceDate').value,dueDate:$('sTextDueDate').value,description:$('sTextDescription').value,qty:$('sTextQty').value,unitPrice:$('sTextUnitPrice').value,lineTotal:$('sTextLineTotal').value,subtotal:$('sTextSubtotal').value,gst:$('sTextGst').value,total:$('sTextTotal').value,paymentTo:$('sTextPaymentTo').value,paymentReference:$('sTextPaymentReference').value,paymentInstruction:$('sTextPaymentInstruction').value,defaultNote:$('sTextDefaultNote').value};
  return {...settings,company:$('sCompany').value,trading:$('sTrading').value,address:$('sAddress').value,phone:$('sPhone').value,email:$('sEmail').value,gstNumber:$('sGst').value,dueDays:Number($('sDueDays').value||3),template:$('sTemplate').value,theme:$('sTheme').value,primaryColor:$('sPrimary').value,accentColor:$('sAccent').value,invoiceText};
}
function renderSettingsPreview(){
  if(!$('settingsInvoicePreview'))return;const snap=settingsDraft();const t=snap.invoiceText||DEFAULT_SETTINGS.invoiceText;const bank=(settings.bankAccounts||[]).find(x=>x.isDefault)||(settings.bankAccounts||[])[0]||{name:'CareClean Main Account',account:'02-0506-0400503-000'};const logo=settings.logoData||ORIGINAL_LOGO;const template=snap.template||'classic';
  $('settingsInvoicePreview').innerHTML=`<div class="settings-invoice-preview preview-${esc(template)}" style="--preview-primary:${esc(snap.primaryColor||'#082f4f')};--preview-accent:${esc(snap.accentColor||'#72bf2e')}"><div class="preview-top"><img src="${esc(logo)}"><div class="preview-company"><strong>${esc(snap.company||'Care New Zealand Limited')}</strong><span>${esc(snap.address||'Company address')}</span><span>${esc(snap.phone||'Phone')} · ${esc(snap.email||'Email')}</span><span>GST No: ${esc(snap.gstNumber||'GST NUMBER')}</span></div></div><div class="preview-title"><div><h3>${esc(t.invoiceTitle||'INVOICE')}</h3><span>${esc(t.invoiceNumber||'Invoice #')}: CC-20260901-1234</span></div><div><strong>${esc(t.billTo||'Bill To')}</strong><span>Sample Customer</span><span>25 Example Street, Wellington</span></div></div><div class="preview-date">${esc(t.invoiceDate||'Invoice date')}: 01 Sep 2026 &nbsp;&nbsp; ${esc(t.dueDate||'Due date')}: 04 Sep 2026</div><table><thead><tr><th>${esc(t.description||'Description')}</th><th>${esc(t.qty||'Qty')}</th><th>${esc(t.unitPrice||'Unit (ex GST)')}</th><th>${esc(t.lineTotal||'Amount')}</th></tr></thead><tbody><tr><td>Regular Cleaning - Fortnightly</td><td>1</td><td>$149.00</td><td>$149.00</td></tr><tr><td>Oven Cleaning</td><td>1</td><td>$60.00</td><td>$60.00</td></tr></tbody></table><div class="preview-totals"><span>${esc(t.subtotal||'Subtotal (ex GST)')} <strong>$209.00</strong></span><span>${esc(t.gst||'GST (15%)')} <strong>$31.35</strong></span><span class="preview-grand">${esc(t.total||'Total')} <strong>$240.35</strong></span></div><div class="preview-payment"><strong>${esc(t.paymentTo||'Payment to')}:</strong> ${esc(bank.name||'Bank account')} — ${esc(bank.account||'00-0000-0000000-00')}<br><strong>${esc(t.paymentReference||'Payment reference')}:</strong> CC-20260901-1234<br>${esc(t.paymentInstruction||'')}<br><br>${esc((t.defaultNote||'').replace(/\{dueDays\}/g,String(snap.dueDays||3)).replace(/\{tradingName\}/g,snap.trading||'CareClean'))}</div></div>`;
}
function exportCsvRows(arr){const fields=['invoice_date','invoice_number','customer_name','customer_address','subtotal','gst','total'];const csv=[fields.join(','),...arr.map(x=>fields.map(f=>'"'+String(x[f]??'').replace(/"/g,'""')+'"').join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='careclean-invoices.csv';a.click()}
function setThemePreset(){const map={careclean:['#082f4f','#72bf2e'],navy:['#17324d','#5b7c99'],green:['#245b35','#67a86b'],charcoal:['#2d3439','#7c8b91'],'pastel-pink':['#9f6f86','#f4c9d9'],'pastel-blue':['#6689a3','#c8e3f1'],'pastel-purple':['#796d9c','#ddd2f2'],'pastel-green':['#668c79','#cfe8d8']};if(map[$('sTheme').value]){[$('sPrimary').value,$('sAccent').value]=map[$('sTheme').value]}renderSettingsPreview()}

document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>switchView(b.dataset.view));
$('addItem').onclick=()=>addItem();$('clearInvoice').onclick=newInvoice;$('invoiceDate').onchange=()=>{if(!currentId)$('dueDate').value=addDays($('invoiceDate').value,settings.dueDays??3)};
$('previewPdf').onclick=()=>{if(validate())makePdf()};$('saveInvoice').onclick=async()=>{let r=await save();if(r){await renderInvoiceList();newInvoice();toast('Invoice saved. Ready for the next invoice.')}};
$('emailInvoice').onclick=async()=>{if(!$('customerEmail').value.trim())return toast('Please enter customer email');let inv=await save();if(!inv)return;await renderInvoiceList();if(!sb){newInvoice();return toast('Invoice saved. Email requires Supabase setup. Ready for the next invoice.')}let pdf=makePdf(inv,'blob');let {error}=await sb.functions.invoke('send-invoice',{body:{to:inv.customer_email,invoice:inv,pdf_base64:pdf.base64,filename:pdf.filename}});if(error)toast('Invoice saved, but email failed: '+error.message);else toast('Invoice emailed successfully. Ready for the next invoice.');newInvoice()};
$('filterMonth').oninput=renderInvoiceList;$('filterSearch').oninput=renderInvoiceList;$('resetFilters').onclick=()=>{$('filterMonth').value='';$('filterSearch').value='';renderInvoiceList()};$('exportCsv').onclick=async()=>exportCsvRows(await allInvoices());$('closeModal').onclick=()=>$('invoiceModal').classList.remove('open');$('invoiceModal').onclick=e=>{if(e.target===$('invoiceModal'))$('invoiceModal').classList.remove('open')};
$('addBank').onclick=()=>{settings.bankAccounts.push({name:'Additional Account',account:'',isDefault:false});renderBankSettings()};$('addProduct').onclick=()=>{settings.products.push({name:'New Service',price:0});renderProductSettings()};
$('sTheme').onchange=setThemePreset;['sCompany','sTrading','sAddress','sPhone','sEmail','sGst','sDueDays','sTemplate','sPrimary','sAccent','sTextInvoiceTitle','sTextBillTo','sTextInvoiceNumber','sTextInvoiceDate','sTextDueDate','sTextDescription','sTextQty','sTextUnitPrice','sTextLineTotal','sTextSubtotal','sTextGst','sTextTotal','sTextPaymentTo','sTextPaymentReference','sTextPaymentInstruction','sTextDefaultNote'].forEach(id=>$(id).addEventListener('input',renderSettingsPreview));$('sTemplate').addEventListener('change',renderSettingsPreview);
$('sLogo').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{settings.logoData=reader.result;$('settingsLogoPreview').src=reader.result;renderSettingsPreview()};reader.readAsDataURL(file)};
$('resetLogo').onclick=()=>{settings.logoData='';$('settingsLogoPreview').src=ORIGINAL_LOGO;$('sLogo').value='';renderSettingsPreview()};
$('saveSettings').onclick=()=>{
  const draft=settingsDraft();settings={...settings,...draft,supabaseUrl:$('sSupabaseUrl').value,supabaseKey:$('sSupabaseKey').value};
  localStorage.setItem('cc_settings',JSON.stringify(settings));initSupabase();applyBranding();$('configNotice').style.display=settings.gstNumber?'none':'block';toast('Settings saved')
};
initSupabase();applyBranding();newInvoice();$('configNotice').style.display=settings.gstNumber?'none':'block';
