const ORIGINAL_LOGO='assets/careclean-logo.jpg';
const DEFAULT_PRODUCTS=[
  {name:'Regular Cleaning - Fortnightly',price:0},{name:'Regular Cleaning - Weekly',price:0},{name:'Move In Clean',price:0},{name:'Move Out Clean',price:0},{name:'Deep Clean',price:0},{name:'Carpet Clean',price:0},{name:'Commercial Cleaning Service',price:0},{name:'Oven Cleaning',price:0},{name:'Refrigerator Cleaning',price:0},{name:'Other',price:0}
];
const DEFAULT_SETTINGS={
  company:'Care New Zealand Limited',trading:'CareClean',address:'120 Melksham Drive, Churton Park, Wellington 6037',phone:'027 499 4445',email:'info@careclean.co.nz',gstNumber:'',dueDays:3,
  gstRate:15,extraFeeEnabled:false,extraFeeLabel:'Service fee',extraFeeRate:0,
  bankAccounts:[{name:'CareClean Main Account',account:'02-0506-0400503-000',isDefault:true}],
  products:DEFAULT_PRODUCTS,template:'classic',theme:'careclean',primaryColor:'#082f4f',accentColor:'#72bf2e',logoData:'',supabaseUrl:'',supabaseKey:'',
  invoiceText:{invoiceTitle:'INVOICE',billTo:'Bill To',invoiceNumber:'Invoice #',invoiceDate:'Invoice date',dueDate:'Due date',description:'Description',qty:'Qty',unitPrice:'Unit (ex GST)',lineTotal:'Amount',subtotal:'Subtotal (ex GST)',gst:'GST',total:'Total',paymentTo:'Payment to',paymentReference:'Payment reference',paymentInstruction:'Please use the invoice number above as your bank payment reference.',defaultNote:'Thank you for choosing CareClean. Please pay within 3 days.'}
};
let stored={};try{stored=JSON.parse(localStorage.getItem('cc_settings')||'{}')}catch{}
if(stored.bankAccount && !stored.bankAccounts) stored.bankAccounts=[{name:'CareClean Main Account',account:stored.bankAccount,isDefault:true}];
let settings={...DEFAULT_SETTINGS,...stored};
settings.bankAccounts=Array.isArray(settings.bankAccounts)&&settings.bankAccounts.length?settings.bankAccounts:DEFAULT_SETTINGS.bankAccounts.map(x=>({...x}));
settings.products=Array.isArray(settings.products)&&settings.products.length?settings.products:DEFAULT_PRODUCTS.map(x=>({...x}));
settings.invoiceText={...DEFAULT_SETTINGS.invoiceText,...(settings.invoiceText||{})};
if(settings.gstRate===undefined)settings.gstRate=15;
if(settings.extraFeeEnabled===undefined)settings.extraFeeEnabled=false;
if(settings.extraFeeLabel===undefined)settings.extraFeeLabel='Service fee';
if(settings.extraFeeRate===undefined)settings.extraFeeRate=0;

let sb=null,currentId=null,items=[],salesChart=null,currentReportInvoices=[];
const $=id=>document.getElementById(id);
const money=n=>'$'+Number(n||0).toFixed(2);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const num=v=>Number(v)||0;
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2600)}
function initSupabase(){try{sb=settings.supabaseUrl&&settings.supabaseKey?window.supabase.createClient(settings.supabaseUrl,settings.supabaseKey):null}catch{sb=null}}
function invoiceNo(){const d=new Date(),p=n=>String(n).padStart(2,'0');return `CC-${String(d.getFullYear()).slice(-2)}${p(d.getMonth()+1)}${p(d.getDate())}-${String(Math.floor(Math.random()*9000)+1000)}`}
function isoDate(d=new Date()){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function addDays(dateStr,days){let d=dateStr?new Date(dateStr+'T12:00:00'):new Date();d.setDate(d.getDate()+num(days));return isoDate(d)}
function logoSrc(){return settings.logoData||ORIGINAL_LOGO}
function defaultBank(src=settings){return (src.bankAccounts||[]).find(x=>x.isDefault)||(src.bankAccounts||[])[0]||{name:'',account:''}}
function taxConfig(src=settings){return {gstRate:num(src.gstRate??15),extraFeeEnabled:!!src.extraFeeEnabled,extraFeeRate:num(src.extraFeeRate),extraFeeLabel:(src.extraFeeLabel||'Service fee').trim()||'Service fee'}}
function applyBranding(){document.documentElement.style.setProperty('--navy',settings.primaryColor||'#082f4f');document.documentElement.style.setProperty('--green',settings.accentColor||'#72bf2e');$('brandLogo').src=logoSrc();updateTaxLabels()}
function updateTaxLabels(){const tx=taxConfig();$('gstLabel').textContent=`${settings.invoiceText.gst||'GST'} (${tx.gstRate}%)`;$('extraFeeRow').style.display=tx.extraFeeEnabled&&tx.extraFeeRate!==0?'flex':'none';$('extraFeeLabel').textContent=`${tx.extraFeeLabel} (${tx.extraFeeRate}%)`}
function newInvoice(){currentId=null;$('invoiceNumber').value=invoiceNo();$('invoiceDate').value=isoDate();$('dueDate').value=addDays($('invoiceDate').value,settings.dueDays??3);['customerName','customerAddress','customerEmail','reference'].forEach(id=>$(id).value='');$('customerNote').value=(settings.invoiceText.defaultNote||`Thank you for choosing ${settings.trading||'CareClean'}. Please pay within ${settings.dueDays??3} days.`).replace(/\{dueDays\}/g,String(settings.dueDays??3)).replace(/\{tradingName\}/g,settings.trading||'CareClean');items=[];addItem();updateTaxLabels();recalc()}
function addItem(data){const first=settings.products[0]||{name:'Other',price:0};items.push(data?{...data}:{description:first.name,custom:'',qty:1,unit_price:num(first.price)});renderItems()}
function renderItems(){const root=$('items'),products=settings.products.length?settings.products:DEFAULT_PRODUCTS,listId='productOptions';root.innerHTML=`<datalist id="${listId}">${products.map(s=>`<option value="${esc(s.name)}"></option>`).join('')}</datalist><div class="items-header"><span>Description</span><span>Qty</span><span>Unit price (ex GST)</span><span>Line total</span><span></span></div>`+items.map((it,i)=>`<div class="item-row"><div class="desc-wrap"><input list="${listId}" data-i="${i}" data-k="description" placeholder="Select a service or type any description" value="${esc(it.description)}"><input data-i="${i}" data-k="custom" placeholder="Optional extra detail" value="${esc(it.custom)}"></div><input type="number" min="0" step="1" data-i="${i}" data-k="qty" value="${num(it.qty)}"><input type="number" min="0" step="0.01" data-i="${i}" data-k="unit_price" value="${num(it.unit_price)}"><div class="line-total">${money(num(it.qty)*num(it.unit_price))}</div><button class="remove" data-remove="${i}" title="Remove">×</button></div>`).join('');root.querySelectorAll('input').forEach(el=>el.addEventListener('input',e=>{let i=+e.target.dataset.i,k=e.target.dataset.k;if(!k)return;items[i][k]=(k==='qty'||k==='unit_price')?num(e.target.value):e.target.value;if(k==='description'){const p=products.find(x=>x.name.toLowerCase()===String(e.target.value).trim().toLowerCase());if(p){items[i].unit_price=num(p.price);const priceInput=root.querySelector(`input[data-i="${i}"][data-k="unit_price"]`);if(priceInput)priceInput.value=items[i].unit_price}}recalc();const row=e.target.closest('.item-row');if(row)row.querySelector('.line-total').textContent=money(num(items[i].qty)*num(items[i].unit_price))}));root.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{items.splice(+b.dataset.remove,1);if(!items.length)addItem();else{renderItems();recalc()}})}
function totals(src=settings){const subtotal=items.reduce((a,x)=>a+num(x.qty)*num(x.unit_price),0),tx=taxConfig(src),gst=subtotal*(tx.gstRate/100),extraFee=tx.extraFeeEnabled?subtotal*(tx.extraFeeRate/100):0;return{subtotal,gst,extraFee,total:subtotal+gst+extraFee}}
function recalc(){const t=totals();$('subtotal').textContent=money(t.subtotal);$('gst').textContent=money(t.gst);$('extraFee').textContent=money(t.extraFee);$('total').textContent=money(t.total);updateTaxLabels()}
function payload(){const t=totals(),snap=JSON.parse(JSON.stringify(settings));snap.invoiceTax=taxConfig(settings);return{id:currentId,invoice_number:$('invoiceNumber').value,invoice_date:$('invoiceDate').value,due_date:$('dueDate').value,customer_name:$('customerName').value.trim(),customer_address:$('customerAddress').value.trim(),customer_email:$('customerEmail').value.trim(),reference:$('reference').value.trim(),customer_note:$('customerNote').value.trim(),items:items.map(x=>({...x})),subtotal:t.subtotal,gst:t.gst,total:t.total,company_snapshot:snap,updated_at:new Date().toISOString()}}
function validate(){if(!$('customerName').value.trim())return toast('Please enter customer name'),false;if(!items.some(x=>num(x.qty)>0&&num(x.unit_price)>=0&&String(x.description||'').trim()))return toast('Please add at least one invoice item'),false;const email=$('customerEmail').value.trim();if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return toast('Please check the customer email address'),false;return true}
async function save(p=payload()){if(!validate())return null;if(sb){const row={...p};delete row.id;let r=currentId?await sb.from('invoices').update(row).eq('id',currentId).select().single():await sb.from('invoices').insert(row).select().single();if(r.error){toast('Supabase error: '+r.error.message);return null}currentId=r.data.id;return r.data}else{let arr=JSON.parse(localStorage.getItem('cc_invoices')||'[]');if(currentId){let idx=arr.findIndex(x=>x.id===currentId);if(idx>=0)arr[idx]={...p,id:currentId,created_at:arr[idx].created_at||new Date().toISOString()}}else{currentId=crypto.randomUUID();arr.unshift({...p,id:currentId,created_at:new Date().toISOString()})}localStorage.setItem('cc_invoices',JSON.stringify(arr));return {...p,id:currentId}}}
async function allInvoices(){if(sb){let {data,error}=await sb.from('invoices').select('*').order('created_at',{ascending:false});if(error){toast(error.message);return[]}return data||[]}return JSON.parse(localStorage.getItem('cc_invoices')||'[]')}
function hexToRgb(hex){hex=String(hex||'#082f4f').replace('#','');if(hex.length===3)hex=hex.split('').map(x=>x+x).join('');return [parseInt(hex.slice(0,2),16)||8,parseInt(hex.slice(2,4),16)||47,parseInt(hex.slice(4,6),16)||79]}
function invoiceTaxFrom(inv){const snap=inv.company_snapshot||settings;const tx=snap.invoiceTax||taxConfig(snap);const extraFee=Math.max(0,num(inv.total)-num(inv.subtotal)-num(inv.gst));return {...taxConfig(tx),extraFee}}
function makePdf(inv=payload(),output='save'){
  const snap=inv.company_snapshot||settings,bank=defaultBank(snap),t={...DEFAULT_SETTINGS.invoiceText,...(snap.invoiceText||{})},tx=invoiceTaxFrom(inv),color=hexToRgb(snap.primaryColor||settings.primaryColor),accent=hexToRgb(snap.accentColor||settings.accentColor),{jsPDF}=window.jspdf,doc=new jsPDF({unit:'mm',format:'a4'}),template=snap.template||'classic';
  try{doc.addImage(snap.logoData||logoSrc(),15,12,45,45)}catch{}
  if(template==='modern'){doc.setFillColor(...color);doc.rect(0,0,210,30,'F');doc.setTextColor(255,255,255)}else doc.setTextColor(...color);
  doc.setFontSize(24);doc.text(t.invoiceTitle||'INVOICE',195,20,{align:'right'});doc.setFontSize(10);doc.setTextColor(40,55,65);doc.text(snap.company||settings.company,195,36,{align:'right'});doc.text(snap.address||settings.address,195,42,{align:'right'});doc.text(`${snap.phone||settings.phone}  |  ${snap.email||settings.email}`,195,48,{align:'right'});doc.text(`GST No: ${snap.gstNumber||'Not set'}`,195,54,{align:'right'});doc.setDrawColor(...color);doc.line(15,62,195,62);
  doc.setFontSize(10);doc.text(`${t.invoiceNumber||'Invoice #'}: ${inv.invoice_number}`,15,72);doc.text(`${t.invoiceDate||'Invoice date'}: ${inv.invoice_date}`,15,78);doc.text(`${t.dueDate||'Due date'}: ${inv.due_date}`,15,84);doc.setFont(undefined,'bold');doc.text(t.billTo||'Bill To',120,72);doc.setFont(undefined,'normal');doc.text(inv.customer_name||'',120,78);if(inv.customer_address)doc.text(doc.splitTextToSize(inv.customer_address,75),120,84);
  const body=(inv.items||[]).map(x=>[x.custom?`${x.description} - ${x.custom}`:x.description,String(x.qty),money(x.unit_price),money(num(x.qty)*num(x.unit_price))]);const theme=template==='minimal'?'plain':'grid';doc.autoTable({startY:105,head:[[t.description||'Description',t.qty||'Qty',t.unitPrice||'Unit (ex GST)',t.lineTotal||'Amount']],body,theme,headStyles:{fillColor:template==='minimal'?[245,247,249]:color,textColor:template==='minimal'?[30,48,63]:[255,255,255]},styles:{fontSize:9},columnStyles:{1:{halign:'right'},2:{halign:'right'},3:{halign:'right'}}});
  let y=doc.lastAutoTable.finalY+10;doc.text(`${t.subtotal||'Subtotal (ex GST)'}: ${money(inv.subtotal)}`,195,y,{align:'right'});doc.text(`${t.gst||'GST'} (${tx.gstRate}%): ${money(inv.gst)}`,195,y+6,{align:'right'});let totalY=y+14;if(tx.extraFeeEnabled&&tx.extraFeeRate!==0){doc.text(`${tx.extraFeeLabel} (${tx.extraFeeRate}%): ${money(tx.extraFee)}`,195,y+12,{align:'right'});totalY=y+20}doc.setFont(undefined,'bold');doc.setFontSize(12);doc.text(`${t.total||'Total'}: ${money(inv.total)}`,195,totalY,{align:'right'});doc.setFontSize(9);doc.setFont(undefined,'normal');
  const payY=totalY+14;doc.text(`${t.paymentTo||'Payment to'}: ${bank.name?bank.name+' - ':''}${bank.account||'Bank account not set'}`,15,payY);doc.setFont(undefined,'bold');doc.text(`${t.paymentReference||'Payment reference'}: ${inv.invoice_number}`,15,payY+6);doc.setFont(undefined,'normal');if(t.paymentInstruction)doc.text(doc.splitTextToSize(t.paymentInstruction,175),15,payY+12);if(inv.customer_note)doc.text(doc.splitTextToSize(inv.customer_note,175),15,payY+24);
  const filename=`${inv.invoice_number}-${(inv.customer_name||'customer').replace(/[^a-z0-9]/gi,'_')}.pdf`;if(output==='blob')return{blob:doc.output('blob'),filename,base64:doc.output('datauristring').split(',')[1]};doc.save(filename)
}
function previewHtml(inv){const snap=inv.company_snapshot||settings,bank=defaultBank(snap),t={...DEFAULT_SETTINGS.invoiceText,...(snap.invoiceText||{})},tx=invoiceTaxFrom(inv),extra=tx.extraFeeEnabled&&tx.extraFeeRate!==0?`<div><span>${esc(tx.extraFeeLabel)} (${tx.extraFeeRate}%)</span><span>${money(tx.extraFee)}</span></div>`:'';return `<div class="inv-preview template-${esc(snap.template||settings.template)}"><div class="inv-preview-head"><img src="${esc(snap.logoData||logoSrc())}"><div class="inv-company"><strong>${esc(snap.company||settings.company)}</strong><br>${esc(snap.address||settings.address)}<br>${esc(snap.phone||settings.phone)} · ${esc(snap.email||settings.email)}<br>GST No: ${esc(snap.gstNumber||'Not set')}</div></div><div class="inv-title"><div><h2>${esc(t.invoiceTitle||'INVOICE')}</h2><div>${esc(inv.invoice_number)}</div></div><div><strong>${esc(t.billTo||'Bill To')}</strong><br>${esc(inv.customer_name)}${inv.customer_address?'<br>'+esc(inv.customer_address).replace(/\n/g,'<br>'):''}</div></div><p><strong>${esc(t.invoiceDate||'Invoice date')}:</strong> ${esc(inv.invoice_date)} &nbsp; <strong>${esc(t.dueDate||'Due date')}:</strong> ${esc(inv.due_date)}</p><table class="inv-table"><thead><tr><th>${esc(t.description||'Description')}</th><th>${esc(t.qty||'Qty')}</th><th>${esc(t.unitPrice||'Unit (ex GST)')}</th><th>${esc(t.lineTotal||'Amount')}</th></tr></thead><tbody>${(inv.items||[]).map(x=>`<tr><td>${esc(x.description)}${x.custom?' - '+esc(x.custom):''}</td><td>${num(x.qty)}</td><td>${money(x.unit_price)}</td><td>${money(num(x.qty)*num(x.unit_price))}</td></tr>`).join('')}</tbody></table><div class="inv-summary"><div><span>${esc(t.subtotal||'Subtotal (ex GST)')}</span><span>${money(inv.subtotal)}</span></div><div><span>${esc(t.gst||'GST')} (${tx.gstRate}%)</span><span>${money(inv.gst)}</span></div>${extra}<div class="grand"><span>${esc(t.total||'Total')}</span><span>${money(inv.total)}</span></div></div><div class="inv-footer"><strong>${esc(t.paymentTo||'Payment to')}:</strong> ${esc(bank.name?bank.name+' - ':'')}${esc(bank.account||'Bank account not set')}<br><strong>${esc(t.paymentReference||'Payment reference')}:</strong> ${esc(inv.invoice_number)}<br><span>${esc(t.paymentInstruction||'')}</span>${inv.customer_note?'<p>'+esc(inv.customer_note)+'</p>':''}</div></div>`}
async function renderInvoiceList(){let arr=await allInvoices(),month=$('filterMonth').value,q=$('filterSearch').value.toLowerCase();arr=arr.filter(x=>(!month||String(x.invoice_date).startsWith(month))&&(!q||[x.customer_name,x.customer_address,x.invoice_number].join(' ').toLowerCase().includes(q)));let net=0,gst=0,total=0;arr.forEach(x=>{net+=num(x.subtotal);gst+=num(x.gst);total+=num(x.total)});$('sumNet').textContent=money(net);$('sumGst').textContent=money(gst);$('sumTotal').textContent=money(total);$('sumCount').textContent=arr.length;$('invoiceRows').innerHTML=arr.map(x=>`<tr><td>${esc(x.invoice_date)}</td><td><strong>${esc(x.invoice_number)}</strong></td><td>${esc(x.customer_name)}</td><td>${esc(x.customer_address||'')}</td><td>${money(x.subtotal)}</td><td>${money(x.gst)}</td><td><strong>${money(x.total)}</strong></td><td><div class="row-actions"><button class="secondary" data-view-id="${x.id}">View</button><button class="secondary" data-download-id="${x.id}">PDF</button><button class="secondary" data-edit-id="${x.id}">Edit</button><button class="danger" data-del-id="${x.id}">Delete</button></div></td></tr>`).join('')||'<tr><td colspan="8">No invoices found.</td></tr>';const get=async id=>(await allInvoices()).find(i=>i.id===id);$('invoiceRows').querySelectorAll('[data-view-id]').forEach(b=>b.onclick=async()=>{let x=await get(b.dataset.viewId);$('modalContent').innerHTML=previewHtml(x);$('invoiceModal').classList.add('open')});$('invoiceRows').querySelectorAll('[data-download-id]').forEach(b=>b.onclick=async()=>{let x=await get(b.dataset.downloadId);makePdf(x);toast('PDF downloaded')});$('invoiceRows').querySelectorAll('[data-edit-id]').forEach(b=>b.onclick=async()=>loadForEdit(await get(b.dataset.editId)));$('invoiceRows').querySelectorAll('[data-del-id]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this invoice?'))return;if(sb)await sb.from('invoices').delete().eq('id',b.dataset.delId);else{let a=await allInvoices();localStorage.setItem('cc_invoices',JSON.stringify(a.filter(x=>x.id!==b.dataset.delId)))}renderInvoiceList();toast('Invoice deleted')})}
function loadForEdit(x){currentId=x.id;$('invoiceNumber').value=x.invoice_number;$('invoiceDate').value=x.invoice_date;$('dueDate').value=x.due_date;$('customerName').value=x.customer_name||'';$('customerAddress').value=x.customer_address||'';$('customerEmail').value=x.customer_email||'';$('reference').value=x.reference||'';$('customerNote').value=x.customer_note||'';items=x.items||[];renderItems();recalc();switchView('create');toast('Invoice loaded for editing')}
function switchView(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$('view-'+v).classList.add('active');document.querySelectorAll('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.view===v));if(v==='invoices')renderInvoiceList();if(v==='settings')loadSettingsForm();if(v==='reports')initReports()}
function loadSettingsForm(){[['sCompany','company'],['sTrading','trading'],['sAddress','address'],['sPhone','phone'],['sEmail','email'],['sGst','gstNumber'],['sDueDays','dueDays'],['sGstRate','gstRate'],['sExtraFeeLabel','extraFeeLabel'],['sExtraFeeRate','extraFeeRate'],['sTemplate','template'],['sTheme','theme'],['sPrimary','primaryColor'],['sAccent','accentColor'],['sSupabaseUrl','supabaseUrl'],['sSupabaseKey','supabaseKey']].forEach(([id,k])=>$(id).value=settings[k]??'');$('sExtraFeeEnabled').checked=!!settings.extraFeeEnabled;const textIds={sTextInvoiceTitle:'invoiceTitle',sTextBillTo:'billTo',sTextInvoiceNumber:'invoiceNumber',sTextInvoiceDate:'invoiceDate',sTextDueDate:'dueDate',sTextDescription:'description',sTextQty:'qty',sTextUnitPrice:'unitPrice',sTextLineTotal:'lineTotal',sTextSubtotal:'subtotal',sTextGst:'gst',sTextTotal:'total',sTextPaymentTo:'paymentTo',sTextPaymentReference:'paymentReference',sTextPaymentInstruction:'paymentInstruction',sTextDefaultNote:'defaultNote'};Object.entries(textIds).forEach(([id,k])=>$(id).value=settings.invoiceText[k]??DEFAULT_SETTINGS.invoiceText[k]);$('settingsLogoPreview').src=logoSrc();renderBankSettings();renderProductSettings();renderSettingsPreview()}
function renderBankSettings(){$('bankSettings').innerHTML=settings.bankAccounts.map((b,i)=>`<div class="settings-row bank-row"><label>Account label<input data-bank-i="${i}" data-bank-k="name" value="${esc(b.name)}"></label><label>Account number<input data-bank-i="${i}" data-bank-k="account" value="${esc(b.account)}"></label><label class="default-check"><input type="radio" name="defaultBank" data-default-bank="${i}" ${b.isDefault?'checked':''}> Default</label><button class="danger" type="button" data-remove-bank="${i}">Remove</button></div>`).join('');$('bankSettings').querySelectorAll('[data-bank-k]').forEach(x=>x.oninput=e=>{settings.bankAccounts[+e.target.dataset.bankI][e.target.dataset.bankK]=e.target.value;renderSettingsPreview()});$('bankSettings').querySelectorAll('[data-default-bank]').forEach(x=>x.onchange=e=>{settings.bankAccounts.forEach((b,j)=>b.isDefault=j===+e.target.dataset.defaultBank);renderSettingsPreview()});$('bankSettings').querySelectorAll('[data-remove-bank]').forEach(x=>x.onclick=()=>{if(settings.bankAccounts.length===1)return toast('Keep at least one bank account');settings.bankAccounts.splice(+x.dataset.removeBank,1);if(!settings.bankAccounts.some(b=>b.isDefault))settings.bankAccounts[0].isDefault=true;renderBankSettings();renderSettingsPreview()})}
function renderProductSettings(){$('productSettings').innerHTML=settings.products.map((p,i)=>`<div class="settings-row product-row"><label>Product / service<input data-product-i="${i}" data-product-k="name" value="${esc(p.name)}"></label><label>Default price ex GST<input type="number" min="0" step="0.01" data-product-i="${i}" data-product-k="price" value="${num(p.price)}"></label><button class="danger" type="button" data-remove-product="${i}">Remove</button></div>`).join('');$('productSettings').querySelectorAll('[data-product-k]').forEach(x=>x.oninput=e=>settings.products[+e.target.dataset.productI][e.target.dataset.productK]=e.target.dataset.productK==='price'?num(e.target.value):e.target.value);$('productSettings').querySelectorAll('[data-remove-product]').forEach(x=>x.onclick=()=>{if(settings.products.length===1)return toast('Keep at least one product');settings.products.splice(+x.dataset.removeProduct,1);renderProductSettings()})}
function settingsDraft(){const invoiceText={invoiceTitle:$('sTextInvoiceTitle').value,billTo:$('sTextBillTo').value,invoiceNumber:$('sTextInvoiceNumber').value,invoiceDate:$('sTextInvoiceDate').value,dueDate:$('sTextDueDate').value,description:$('sTextDescription').value,qty:$('sTextQty').value,unitPrice:$('sTextUnitPrice').value,lineTotal:$('sTextLineTotal').value,subtotal:$('sTextSubtotal').value,gst:$('sTextGst').value,total:$('sTextTotal').value,paymentTo:$('sTextPaymentTo').value,paymentReference:$('sTextPaymentReference').value,paymentInstruction:$('sTextPaymentInstruction').value,defaultNote:$('sTextDefaultNote').value};return {...settings,company:$('sCompany').value,trading:$('sTrading').value,address:$('sAddress').value,phone:$('sPhone').value,email:$('sEmail').value,gstNumber:$('sGst').value,dueDays:num($('sDueDays').value),gstRate:num($('sGstRate').value),extraFeeEnabled:$('sExtraFeeEnabled').checked,extraFeeLabel:$('sExtraFeeLabel').value||'Service fee',extraFeeRate:num($('sExtraFeeRate').value),template:$('sTemplate').value,theme:$('sTheme').value,primaryColor:$('sPrimary').value,accentColor:$('sAccent').value,invoiceText}}
function renderSettingsPreview(){if(!$('settingsInvoicePreview'))return;const snap=settingsDraft(),t=snap.invoiceText||DEFAULT_SETTINGS.invoiceText,bank=defaultBank(settings),logo=settings.logoData||ORIGINAL_LOGO,template=snap.template||'classic',tx=taxConfig(snap),subtotal=209,gst=subtotal*tx.gstRate/100,fee=tx.extraFeeEnabled?subtotal*tx.extraFeeRate/100:0,total=subtotal+gst+fee,extra=tx.extraFeeEnabled&&tx.extraFeeRate!==0?`<span>${esc(tx.extraFeeLabel)} (${tx.extraFeeRate}%) <strong>${money(fee)}</strong></span>`:'';$('settingsInvoicePreview').innerHTML=`<div class="settings-invoice-preview preview-${esc(template)}" style="--preview-primary:${esc(snap.primaryColor||'#082f4f')};--preview-accent:${esc(snap.accentColor||'#72bf2e')}"><div class="preview-top"><img src="${esc(logo)}"><div class="preview-company"><strong>${esc(snap.company||'Care New Zealand Limited')}</strong><span>${esc(snap.address||'Company address')}</span><span>${esc(snap.phone||'Phone')} · ${esc(snap.email||'Email')}</span><span>GST No: ${esc(snap.gstNumber||'GST NUMBER')}</span></div></div><div class="preview-title"><div><h3>${esc(t.invoiceTitle||'INVOICE')}</h3><span>${esc(t.invoiceNumber||'Invoice #')}: CC-260901-1234</span></div><div><strong>${esc(t.billTo||'Bill To')}</strong><span>Sample Customer</span><span>25 Example Street, Wellington</span></div></div><div class="preview-date">${esc(t.invoiceDate||'Invoice date')}: 01 Sep 2026 &nbsp;&nbsp; ${esc(t.dueDate||'Due date')}: 04 Sep 2026</div><table><thead><tr><th>${esc(t.description||'Description')}</th><th>${esc(t.qty||'Qty')}</th><th>${esc(t.unitPrice||'Unit (ex GST)')}</th><th>${esc(t.lineTotal||'Amount')}</th></tr></thead><tbody><tr><td>Regular Cleaning - Fortnightly</td><td>1</td><td>$149.00</td><td>$149.00</td></tr><tr><td>Oven Cleaning</td><td>1</td><td>$60.00</td><td>$60.00</td></tr></tbody></table><div class="preview-totals"><span>${esc(t.subtotal||'Subtotal (ex GST)')} <strong>${money(subtotal)}</strong></span><span>${esc(t.gst||'GST')} (${tx.gstRate}%) <strong>${money(gst)}</strong></span>${extra}<span class="preview-grand">${esc(t.total||'Total')} <strong>${money(total)}</strong></span></div><div class="preview-payment"><strong>${esc(t.paymentTo||'Payment to')}:</strong> ${esc(bank.name||'Bank account')} - ${esc(bank.account||'00-0000-0000000-00')}<br><strong>${esc(t.paymentReference||'Payment reference')}:</strong> CC-260901-1234<br>${esc(t.paymentInstruction||'')}<br><br>${esc((t.defaultNote||'').replace(/\{dueDays\}/g,String(snap.dueDays||3)).replace(/\{tradingName\}/g,snap.trading||'CareClean'))}</div></div>`}
function exportCsvRows(arr,filename='careclean-invoices.csv'){const headers=['invoice_date','invoice_number','customer_name','customer_address','customer_email','subtotal','gst','additional_fee_or_tax','total'];const rows=arr.map(x=>[x.invoice_date,x.invoice_number,x.customer_name,x.customer_address||'',x.customer_email||'',num(x.subtotal),num(x.gst),invoiceTaxFrom(x).extraFee,num(x.total)]);const quote=v=>'\"'+String(v??'').replace(/\"/g,'\"\"')+'\"';const csv=[headers.join(','),...rows.map(r=>r.map(quote).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function setThemePreset(){const map={careclean:['#082f4f','#72bf2e'],navy:['#17324d','#5b7c99'],green:['#245b35','#67a86b'],charcoal:['#2d3439','#7c8b91'],'pastel-pink':['#9f6f86','#f4c9d9'],'pastel-blue':['#6689a3','#c8e3f1'],'pastel-purple':['#796d9c','#ddd2f2'],'pastel-green':['#668c79','#cfe8d8']};if(map[$('sTheme').value]){[$('sPrimary').value,$('sAccent').value]=map[$('sTheme').value]}renderSettingsPreview()}
function monthKey(dateStr){return String(dateStr||'').slice(0,7)}
function monthLabel(key){if(!key)return'';const [y,m]=key.split('-').map(Number);return new Date(y,m-1,1).toLocaleDateString('en-NZ',{month:'short',year:'numeric'})}
function setReportRange(kind){const now=new Date(),end=new Date(now.getFullYear(),now.getMonth(),now.getDate());let start;if(kind==='last-month'){start=new Date(now.getFullYear(),now.getMonth()-1,1);const last=new Date(now.getFullYear(),now.getMonth(),0);$('reportFrom').value=isoDate(start);$('reportTo').value=isoDate(last)}else{const months=Number(kind);start=new Date(now.getFullYear(),now.getMonth()-(months-1),1);$('reportFrom').value=isoDate(start);$('reportTo').value=isoDate(end)}runReport()}
async function initReports(){if(!$('reportFrom').value||!$('reportTo').value)setReportRange('6');else runReport()}
async function runReport(){const from=$('reportFrom').value,to=$('reportTo').value;if(!from||!to)return toast('Choose a from and to date');if(from>to)return toast('The from date must be before the to date');const all=await allInvoices(),arr=all.filter(x=>x.invoice_date>=from&&x.invoice_date<=to);currentReportInvoices=arr;let net=0,gst=0,total=0;arr.forEach(x=>{net+=num(x.subtotal);gst+=num(x.gst);total+=num(x.total)});$('reportNet').textContent=money(net);$('reportGst').textContent=money(gst);$('reportTotal').textContent=money(total);$('reportCount').textContent=arr.length;$('reportPeriodLabel').textContent=`${from} to ${to}`;const grouped={};arr.forEach(x=>{const k=monthKey(x.invoice_date);if(!grouped[k])grouped[k]={count:0,net:0,gst:0,fee:0,total:0};const tx=invoiceTaxFrom(x);grouped[k].count++;grouped[k].net+=num(x.subtotal);grouped[k].gst+=num(x.gst);grouped[k].fee+=tx.extraFee;grouped[k].total+=num(x.total)});const months=[];let d=new Date(from+'T12:00:00'),end=new Date(to+'T12:00:00');d=new Date(d.getFullYear(),d.getMonth(),1);while(d<=end){months.push(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`);d.setMonth(d.getMonth()+1)};$('reportRows').innerHTML=months.map(k=>{const x=grouped[k]||{count:0,net:0,gst:0,fee:0,total:0};return `<tr><td><strong>${esc(monthLabel(k))}</strong></td><td>${x.count}</td><td>${money(x.net)}</td><td>${money(x.gst)}</td><td>${money(x.fee)}</td><td><strong>${money(x.total)}</strong></td></tr>`}).join('')||'<tr><td colspan="6">No invoices in this period.</td></tr>';renderSalesChart(months,grouped)}
function renderSalesChart(months,grouped){if(!window.Chart)return;const canvas=$('salesChart'),labels=months.map(monthLabel),values=months.map(k=>(grouped[k]||{}).total||0);if(salesChart)salesChart.destroy();const valueLabels={id:'valueLabels',afterDatasetsDraw(chart){const {ctx}=chart;ctx.save();ctx.font='600 11px system-ui';ctx.textAlign='center';ctx.textBaseline='bottom';ctx.fillStyle='#405462';chart.getDatasetMeta(0).data.forEach((bar,i)=>{ctx.fillText(money(values[i]),bar.x,bar.y-5)});ctx.restore()}};salesChart=new Chart(canvas,{type:'bar',data:{labels,datasets:[{label:'Total invoiced',data:values,backgroundColor:settings.primaryColor||'#082f4f',borderRadius:7,maxBarThickness:60}]},options:{responsive:true,maintainAspectRatio:false,layout:{padding:{top:28}},plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>money(c.raw)}}},scales:{y:{beginAtZero:true,ticks:{callback:v=>'$'+v.toLocaleString('en-NZ')}}}},plugins:[valueLabels]})}

document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>switchView(b.dataset.view));
$('addItem').onclick=()=>addItem();$('clearInvoice').onclick=newInvoice;$('invoiceDate').onchange=()=>{if(!currentId)$('dueDate').value=addDays($('invoiceDate').value,settings.dueDays??3)};
$('previewPdf').onclick=()=>{if(validate())makePdf()};$('saveInvoice').onclick=async()=>{let r=await save();if(r){await renderInvoiceList();newInvoice();toast('Invoice saved. Ready for the next invoice.')}};
$('emailInvoice').onclick=async()=>{const requestedEmail=$('customerEmail').value.trim();let inv=await save();if(!inv)return;await renderInvoiceList();if(!requestedEmail){newInvoice();return toast('Invoice saved. No customer email was entered, so no email was sent.')}if(!sb){newInvoice();return toast('Invoice saved. Email requires Supabase setup. Ready for the next invoice.')}let pdf=makePdf(inv,'blob');let {error}=await sb.functions.invoke('send-invoice',{body:{to:inv.customer_email,invoice:inv,pdf_base64:pdf.base64,filename:pdf.filename}});if(error)toast('Invoice saved, but email failed: '+error.message);else toast('Invoice emailed successfully. Ready for the next invoice.');newInvoice()};
$('filterMonth').oninput=renderInvoiceList;$('filterSearch').oninput=renderInvoiceList;$('resetFilters').onclick=()=>{$('filterMonth').value='';$('filterSearch').value='';renderInvoiceList()};$('exportCsv').onclick=async()=>exportCsvRows(await allInvoices());$('closeModal').onclick=()=>$('invoiceModal').classList.remove('open');$('invoiceModal').onclick=e=>{if(e.target===$('invoiceModal'))$('invoiceModal').classList.remove('open')};
$('addBank').onclick=()=>{settings.bankAccounts.push({name:'Additional Account',account:'',isDefault:false});renderBankSettings();renderSettingsPreview()};$('addProduct').onclick=()=>{settings.products.push({name:'New Service',price:0});renderProductSettings()};
$('sTheme').onchange=setThemePreset;['sCompany','sTrading','sAddress','sPhone','sEmail','sGst','sDueDays','sGstRate','sExtraFeeLabel','sExtraFeeRate','sTemplate','sPrimary','sAccent','sTextInvoiceTitle','sTextBillTo','sTextInvoiceNumber','sTextInvoiceDate','sTextDueDate','sTextDescription','sTextQty','sTextUnitPrice','sTextLineTotal','sTextSubtotal','sTextGst','sTextTotal','sTextPaymentTo','sTextPaymentReference','sTextPaymentInstruction','sTextDefaultNote'].forEach(id=>$(id).addEventListener('input',renderSettingsPreview));$('sExtraFeeEnabled').addEventListener('change',renderSettingsPreview);$('sTemplate').addEventListener('change',renderSettingsPreview);
$('sLogo').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{settings.logoData=reader.result;$('settingsLogoPreview').src=reader.result;renderSettingsPreview()};reader.readAsDataURL(file)};$('resetLogo').onclick=()=>{settings.logoData='';$('settingsLogoPreview').src=ORIGINAL_LOGO;$('sLogo').value='';renderSettingsPreview()};
$('saveSettings').onclick=()=>{const draft=settingsDraft();settings={...settings,...draft,supabaseUrl:$('sSupabaseUrl').value,supabaseKey:$('sSupabaseKey').value};localStorage.setItem('cc_settings',JSON.stringify(settings));initSupabase();applyBranding();recalc();$('configNotice').style.display=settings.gstNumber?'none':'block';toast('Settings saved')};
document.querySelectorAll('.report-range').forEach(b=>b.onclick=()=>setReportRange(b.dataset.range));$('runReport').onclick=runReport;$('reportExportCsv').onclick=()=>exportCsvRows(currentReportInvoices,`careclean-sales-report-${$('reportFrom').value}-to-${$('reportTo').value}.csv`);
initSupabase();applyBranding();newInvoice();$('configNotice').style.display=settings.gstNumber?'none':'block';
