(() => {
  const $=id=>document.getElementById(id);
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const num=v=>Number(v)||0, money=n=>'$'+Number(n||0).toFixed(2), iso=()=>new Date().toISOString().slice(0,10);
  const client=()=>window.SAAS?.client?.(); const business=()=>window.SAAS?.state?.business;
  const DEFAULT={labourRate:30,margin:20,validityDays:14,costingPrefix:'JC',quotePrefix:'QUO',quoteTerms:'This quote is valid for {validityDays} days from the quote date.',presets:[{name:'Materials',unit:'item',unitCost:0},{name:'Travel / fuel',unit:'km',unitCost:0},{name:'Equipment',unit:'hour',unitCost:0},{name:'Subcontractor',unit:'item',unitCost:0}]};
  let cfg={...DEFAULT}, costingId=null, customerId=null, labour=[], costs=[], fields=[], editingQuoteId=null, quoteCustomerId=null;

  function currentBusinessSettings(){return business()?.settings||{} }
  function loadCfg(){const b=currentBusinessSettings();cfg={...DEFAULT,...(b.jobCostingSettings||{})};cfg.presets=Array.isArray(cfg.presets)?cfg.presets:DEFAULT.presets.map(x=>({...x}));}
  function gstRate(){return num(window.invoiceAppHelpers?.settings?.()?.gstRate??currentBusinessSettings().gstRate??15)}
  function toast(s){const t=$('toast');if(t){t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}else alert(s)}
  function cleanPrefix(v,fallback){return String(v||fallback).trim().replace(/[^A-Za-z0-9]/g,'').toUpperCase()||fallback}
  function fmt(prefix,n){return `${cleanPrefix(prefix,'X')}-${String(n).padStart(4,'0')}`}
  async function nextNumber(table,column,prefix){const c=client(); if(!c)return fmt(prefix,1);const {data}=await c.from(table).select(column).order('created_at',{ascending:false}).limit(500);let max=0;const re=new RegExp('^'+cleanPrefix(prefix,'X').replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'-(\\d+)$','i');for(const x of data||[]){const m=String(x[column]||'').match(re);if(m)max=Math.max(max,Number(m[1])||0)}return fmt(prefix,max+1)}
  function billing(c){const a=Array.isArray(c?.contacts)?c.contacts:[];return a.find(x=>x.billing)||a[0]||{} }
  async function customers(){const c=client();if(!c)return[];const {data,error}=await c.from('customers').select('*').order('name');if(error){console.warn(error);return[]}return data||[]}
  async function refreshCustomers(){const arr=await customers();const list=$('jcCustomerOptions');if(list)list.innerHTML=arr.map(c=>`<option value="${esc(c.name)}"></option>`).join('')}
  async function selectCustomer(name){const arr=await customers();const c=arr.find(x=>String(x.name).trim().toLowerCase()===String(name||'').trim().toLowerCase());customerId=c?.id||null;const hint=$('jcCustomerHint');if(hint)hint.textContent=c?`${c.customer_number||''}${billing(c).email?' · '+billing(c).email:''}`:'Customer not found — add them under My Customers first.';return c}

  function costTotals(){const l=labour.reduce((s,x)=>s+num(x.hours)*num(x.rate),0),o=costs.reduce((s,x)=>s+num(x.qty)*num(x.unitCost),0),cost=l+o,m=Math.min(99.9,Math.max(0,num($('jcMargin')?.value??cfg.margin))),recommended=cost>0?cost/(1-m/100):0,quote=num($('jcQuotePrice')?.value),gst=quote*gstRate()/100;return{labour:l,other:o,cost,margin:m,recommended,quote,gst,total:quote+gst}}
  function recalc(){const t=costTotals();$('jcLabourTotal').textContent=money(t.labour);$('jcOtherTotal').textContent=money(t.other);$('jcCostTotal').textContent=money(t.cost);$('jcMarginDisplay').textContent=t.margin.toFixed(1).replace('.0','')+'%';$('jcRecommended').textContent=money(t.recommended);$('jcGstLabel').textContent=`GST (${gstRate()}%)`;$('jcQuoteGst').textContent=money(t.gst);$('jcQuoteTotal').textContent=money(t.total);if($('jcQuotePrice')&&!$('jcQuotePrice').dataset.touched)$('jcQuotePrice').value=t.recommended?t.recommended.toFixed(2):''}
  function renderLabour(){const r=$('jcLabourRows');if(!r)return;r.innerHTML='<div class="jc-row-head"><span>Description / role</span><span>Hours</span><span>Cost / hour</span><span>Total</span><span></span></div>'+labour.map((x,i)=>`<div class="jc-cost-row"><input data-jl="${i}" data-k="description" value="${esc(x.description||'Labour')}" placeholder="Labour"><input type="number" min="0" step="0.25" data-jl="${i}" data-k="hours" value="${num(x.hours)}"><input type="number" min="0" step="0.01" data-jl="${i}" data-k="rate" value="${num(x.rate)}"><strong>${money(num(x.hours)*num(x.rate))}</strong><button class="remove" data-jl-remove="${i}">×</button></div>`).join('');r.querySelectorAll('[data-jl]').forEach(e=>e.oninput=ev=>{const i=+ev.target.dataset.jl,k=ev.target.dataset.k;labour[i][k]=k==='description'?ev.target.value:num(ev.target.value);const row=ev.target.closest('.jc-cost-row');if(row)row.querySelector('strong').textContent=money(num(labour[i].hours)*num(labour[i].rate));recalc()});r.querySelectorAll('[data-jl-remove]').forEach(b=>b.onclick=()=>{labour.splice(+b.dataset.jlRemove,1);renderLabour();recalc()})}
  function renderCosts(){const r=$('jcCostRows');if(!r)return;r.innerHTML='<div class="jc-row-head jc-other-head"><span>Description</span><span>Qty</span><span>Unit</span><span>Unit cost</span><span>Total</span><span></span></div>'+costs.map((x,i)=>`<div class="jc-cost-row jc-other-row"><div class="jc-preset-wrap"><input data-jc="${i}" data-k="description" list="jcPresetOptions" value="${esc(x.description||'')}" placeholder="Cost description"></div><input type="number" min="0" step="0.01" data-jc="${i}" data-k="qty" value="${num(x.qty)}"><input data-jc="${i}" data-k="unit" value="${esc(x.unit||'item')}" placeholder="item"><input type="number" min="0" step="0.01" data-jc="${i}" data-k="unitCost" value="${num(x.unitCost)}"><strong>${money(num(x.qty)*num(x.unitCost))}</strong><button class="remove" data-jc-remove="${i}">×</button></div>`).join('')+`<datalist id="jcPresetOptions">${cfg.presets.map(p=>`<option value="${esc(p.name)}"></option>`).join('')}</datalist>`;r.querySelectorAll('[data-jc]').forEach(e=>{e.oninput=ev=>{const i=+ev.target.dataset.jc,k=ev.target.dataset.k;costs[i][k]=['qty','unitCost'].includes(k)?num(ev.target.value):ev.target.value;const row=ev.target.closest('.jc-cost-row');if(row)row.querySelector('strong').textContent=money(num(costs[i].qty)*num(costs[i].unitCost));recalc()};e.onchange=ev=>{const i=+ev.target.dataset.jc,k=ev.target.dataset.k;if(k==='description'){const p=cfg.presets.find(p=>p.name.toLowerCase()===String(ev.target.value).trim().toLowerCase());if(p){costs[i].unit=p.unit||'item';costs[i].unitCost=num(p.unitCost);if(!costs[i].qty)costs[i].qty=1;renderCosts();recalc()}}}});r.querySelectorAll('[data-jc-remove]').forEach(b=>b.onclick=()=>{costs.splice(+b.dataset.jcRemove,1);renderCosts();recalc()})}
  function renderFields(){const r=$('jcCustomFields');if(!r)return;r.innerHTML=fields.map((x,i)=>`<div class="custom-field-row"><input data-jf="${i}" data-k="label" value="${esc(x.label||'')}" placeholder="Field name"><input data-jf="${i}" data-k="value" value="${esc(x.value||'')}" placeholder="Value"><button class="remove" data-jf-remove="${i}">×</button></div>`).join('')||'<p class="hint">No additional fields added.</p>';r.querySelectorAll('[data-jf]').forEach(e=>e.oninput=ev=>fields[+ev.target.dataset.jf][ev.target.dataset.k]=ev.target.value);r.querySelectorAll('[data-jf-remove]').forEach(b=>b.onclick=()=>{fields.splice(+b.dataset.jfRemove,1);renderFields()})}
  async function fresh(){costingId=null;customerId=null;$('jcNumber').value=await nextNumber('job_costings','costing_number',cfg.costingPrefix);$('jcDate').value=iso();$('jcCustomerName').value='';$('jcDescription').value='';$('jcNotes').value='';$('jcMargin').value=cfg.margin;$('jcQuotePrice').value='';delete $('jcQuotePrice').dataset.touched;labour=[{description:'Labour',hours:0,rate:cfg.labourRate}];costs=[];fields=[];renderLabour();renderCosts();renderFields();recalc();refreshCustomers()}
  function costingPayload(){const t=costTotals();return{id:costingId,costing_number:$('jcNumber').value,costing_date:$('jcDate').value,customer_id:customerId,customer_name:$('jcCustomerName').value.trim(),job_description:$('jcDescription').value.trim(),notes:$('jcNotes').value.trim(),labour_items:labour,variable_costs:costs,custom_fields:fields,total_labour:t.labour,total_variable:t.other,total_cost_ex_gst:t.cost,margin_percent:t.margin,recommended_price_ex_gst:t.recommended,proposed_quote_price_ex_gst:t.quote,updated_at:new Date().toISOString()}}
  function validateCosting(){if(!customerId){toast('Select an existing customer from My Customers.');return false}if(!$('jcDescription').value.trim()){toast('Enter a job / service description.');return false}return true}
  async function saveCosting(silent=false){if(!validateCosting())return null;const c=client();if(!c)return null;const p=costingPayload(),row={...p};delete row.id;let r;if(costingId)r=await c.from('job_costings').update(row).eq('id',costingId).select().single();else r=await c.from('job_costings').insert(row).select().single();if(r.error){toast('Could not save costing: '+r.error.message);return null}costingId=r.data.id;if(!silent)toast('Job costing saved to the cloud.');return r.data}
  async function loadCosting(id){const c=client();const {data,error}=await c.from('job_costings').select('*').eq('id',id).single();if(error||!data)return toast('Could not load costing.');costingId=data.id;customerId=data.customer_id;$('jcNumber').value=data.costing_number;$('jcDate').value=data.costing_date;$('jcCustomerName').value=data.customer_name||'';$('jcDescription').value=data.job_description||'';$('jcNotes').value=data.notes||'';$('jcMargin').value=num(data.margin_percent);$('jcQuotePrice').value=num(data.proposed_quote_price_ex_gst)||'';$('jcQuotePrice').dataset.touched='1';labour=Array.isArray(data.labour_items)?data.labour_items:[];costs=Array.isArray(data.variable_costs)?data.variable_costs:[];fields=Array.isArray(data.custom_fields)?data.custom_fields:[];renderLabour();renderCosts();renderFields();recalc();showTab('costing')}
  async function deleteCosting(id){if(!confirm('Delete this saved job costing?'))return;const {error}=await client().from('job_costings').delete().eq('id',id);if(error)toast(error.message);else{toast('Job costing deleted.');renderSaved()}}
  async function renderSaved(){const c=client();let {data,error}=await c.from('job_costings').select('*').order('created_at',{ascending:false});if(error)return;const q=String($('jcSavedSearch')?.value||'').toLowerCase();data=(data||[]).filter(x=>!q||[x.costing_number,x.customer_name,x.job_description].join(' ').toLowerCase().includes(q));$('jcSavedRows').innerHTML=data.map(x=>`<tr><td>${esc(x.costing_date)}</td><td><strong>${esc(x.costing_number)}</strong></td><td>${esc(x.customer_name)}</td><td>${esc(x.job_description)}</td><td>${money(x.total_cost_ex_gst)}</td><td>${money(x.recommended_price_ex_gst)}</td><td>${money(x.proposed_quote_price_ex_gst)}</td><td><div class="row-actions"><button class="secondary" data-jc-edit="${x.id}">Edit</button><button class="secondary" data-jc-quote="${x.id}">Quote</button><button class="danger" data-jc-del="${x.id}">Delete</button></div></td></tr>`).join('')||'<tr><td colspan="8">No saved costings found.</td></tr>';$('jcSavedRows').querySelectorAll('[data-jc-edit]').forEach(b=>b.onclick=()=>loadCosting(b.dataset.jcEdit));$('jcSavedRows').querySelectorAll('[data-jc-quote]').forEach(b=>b.onclick=async()=>{await loadCosting(b.dataset.jcQuote);createQuote()});$('jcSavedRows').querySelectorAll('[data-jc-del]').forEach(b=>b.onclick=()=>deleteCosting(b.dataset.jcDel))}

  async function createQuote(){let costing=await saveCosting(true);if(!costing)return;const quotePrice=num($('jcQuotePrice').value);if(quotePrice<=0)return toast('Enter the price you want to quote, excluding GST.');const c=await selectCustomer($('jcCustomerName').value),bc=billing(c),qNo=await nextNumber('quotes','quote_number',cfg.quotePrefix),rate=gstRate(),gst=quotePrice*rate/100;const row={job_costing_id:costing.id,quote_number:qNo,quote_date:iso(),valid_until:new Date(Date.now()+cfg.validityDays*86400000).toISOString().slice(0,10),customer_id:customerId,customer_name:c?.name||costing.customer_name,customer_address:c?.address||'',customer_email:bc.email||'',description:costing.job_description,quoted_price_ex_gst:quotePrice,gst_rate:rate,gst_amount:gst,total_incl_gst:quotePrice+gst,notes:'',terms:String(cfg.quoteTerms||'').replaceAll('{validityDays}',String(cfg.validityDays)),status:'draft',updated_at:new Date().toISOString()};const {data,error}=await client().from('quotes').insert(row).select().single();if(error)return toast('Could not create quote: '+error.message);toast(`Quote ${data.quote_number} created.`);showTab('quotes');openQuote(data.id)}
  function statusBadge(s){const label={draft:'Draft',sent:'Sent',approved:'Approved',won:'Deal won',rejected:'Rejected'}[s]||s;return `<span class="quote-status status-${esc(s)}">${esc(label)}</span>`}
  async function renderQuotes(){const c=client();let {data,error}=await c.from('quotes').select('*').order('created_at',{ascending:false});if(error)return;const all=data||[];for(const s of ['draft','sent','approved','won']){const el=$('jcQuote'+s[0].toUpperCase()+s.slice(1)+'Count');if(el)el.textContent=all.filter(x=>x.status===s).length}const q=String($('jcQuoteSearch')?.value||'').toLowerCase(),sf=$('jcQuoteStatusFilter')?.value||'';data=all.filter(x=>(!sf||x.status===sf)&&(!q||[x.quote_number,x.customer_name,x.description].join(' ').toLowerCase().includes(q)));$('jcQuoteRows').innerHTML=data.map(x=>`<tr><td>${esc(x.quote_date)}</td><td><strong>${esc(x.quote_number)}</strong></td><td>${esc(x.customer_name)}</td><td>${esc(x.description)}</td><td>${money(x.quoted_price_ex_gst)}</td><td>${money(x.gst_amount)}</td><td>${money(x.total_incl_gst)}</td><td>${statusBadge(x.status)}</td><td><div class="row-actions"><button class="secondary" data-q-open="${x.id}">Open</button>${x.status!=='won'?`<button class="secondary" data-q-edit="${x.id}">Edit</button>`:''}${x.status==='approved'?`<button class="primary" data-q-invoice="${x.id}">Create Invoice</button>`:''}</div></td></tr>`).join('')||'<tr><td colspan="9">No quotes found.</td></tr>';const r=$('jcQuoteRows');r.querySelectorAll('[data-q-open]').forEach(b=>b.onclick=()=>openQuote(b.dataset.qOpen));r.querySelectorAll('[data-q-edit]').forEach(b=>b.onclick=()=>openQuote(b.dataset.qEdit,true));r.querySelectorAll('[data-q-invoice]').forEach(b=>b.onclick=()=>quoteToInvoice(b.dataset.qInvoice))}
  async function getQuote(id){const {data,error}=await client().from('quotes').select('*').eq('id',id).single();if(error){toast(error.message);return null}return data}
  async function openQuote(id,edit=false){const q=await getQuote(id);if(!q)return;editingQuoteId=q.id;quoteCustomerId=q.customer_id;const body=$('quoteModalContent');body.innerHTML=edit?quoteEditHtml(q):quoteViewHtml(q);$('quoteModal').classList.add('open');if(edit)bindQuoteEdit(q);else bindQuoteView(q)}
  function quoteEditHtml(q){return `<h2>Edit Quote ${esc(q.quote_number)}</h2><div class="form-grid compact"><label>Quote date<input id="qeDate" type="date" value="${esc(q.quote_date)}"></label><label>Valid until<input id="qeValid" type="date" value="${esc(q.valid_until||'')}"></label><label class="wide">Customer<input id="qeCustomer" value="${esc(q.customer_name)}" readonly></label><label class="wide">Description<input id="qeDescription" value="${esc(q.description)}"></label><label>Price (ex GST)<input id="qePrice" type="number" min="0" step="0.01" value="${num(q.quoted_price_ex_gst)}"></label><label>GST rate %<input id="qeGst" type="number" min="0" step="0.01" value="${num(q.gst_rate)}"></label><label class="wide">Notes<textarea id="qeNotes" rows="3">${esc(q.notes||'')}</textarea></label><label class="wide">Terms<textarea id="qeTerms" rows="4">${esc(q.terms||'')}</textarea></label></div><div class="actions"><button class="secondary" id="qeCancel">Cancel</button><button class="primary" id="qeSave">Save Quote</button></div>`}
  function quoteViewHtml(q){return `<div class="profile-head"><div><h2>Quote ${esc(q.quote_number)}</h2>${statusBadge(q.status)}</div><div class="row-actions">${q.status!=='won'?'<button class="secondary" id="qvEdit">Edit</button>':''}<button class="secondary" id="qvPdf">Download PDF</button>${q.status!=='won'?'<button class="primary" id="qvEmail">Send Quote</button>':''}</div></div><div class="quote-preview"><div class="quote-preview-head"><div><strong>${esc(currentBusinessSettings().trading||currentBusinessSettings().company||business()?.name||'Business')}</strong><small>${esc(currentBusinessSettings().address||'')}</small></div><div><strong>QUOTE</strong><span>${esc(q.quote_number)}</span></div></div><div class="profile-grid"><div><strong>Customer</strong><p>${esc(q.customer_name)}<br>${esc(q.customer_address||'')}<br>${esc(q.customer_email||'')}</p></div><div><strong>Quote date</strong><p>${esc(q.quote_date)}<br>Valid until: ${esc(q.valid_until||'—')}</p></div></div><table class="inv-table"><thead><tr><th>Description</th><th>Amount ex GST</th></tr></thead><tbody><tr><td>${esc(q.description)}</td><td>${money(q.quoted_price_ex_gst)}</td></tr></tbody></table><div class="inv-summary"><div><span>Subtotal</span><strong>${money(q.quoted_price_ex_gst)}</strong></div><div><span>GST (${num(q.gst_rate)}%)</span><strong>${money(q.gst_amount)}</strong></div><div class="grand"><span>Total</span><strong>${money(q.total_incl_gst)}</strong></div></div>${q.notes?`<div class="inv-footer"><strong>Notes</strong><p>${esc(q.notes)}</p></div>`:''}${q.terms?`<div class="inv-footer"><strong>Terms</strong><p>${esc(q.terms)}</p></div>`:''}</div><div class="actions">${q.status==='draft'||q.status==='sent'?'<button class="secondary" id="qvApprove">Mark Approved</button><button class="danger" id="qvReject">Mark Rejected</button>':''}${q.status==='approved'?'<button class="primary" id="qvInvoice">Create Invoice</button>':''}${q.status==='won'?'<span class="won-note">✓ Deal won — progressed to invoice</span>':''}</div>`}
  function bindQuoteEdit(q){$('qeCancel').onclick=()=>openQuote(q.id);$('qeSave').onclick=async()=>{const price=num($('qePrice').value),rate=num($('qeGst').value),gst=price*rate/100,row={quote_date:$('qeDate').value,valid_until:$('qeValid').value||null,description:$('qeDescription').value.trim(),quoted_price_ex_gst:price,gst_rate:rate,gst_amount:gst,total_incl_gst:price+gst,notes:$('qeNotes').value.trim(),terms:$('qeTerms').value.trim(),updated_at:new Date().toISOString()};const {error}=await client().from('quotes').update(row).eq('id',q.id);if(error)return toast(error.message);toast('Quote updated.');renderQuotes();openQuote(q.id)}}
  function bindQuoteView(q){if($('qvEdit'))$('qvEdit').onclick=()=>openQuote(q.id,true);$('qvPdf').onclick=()=>makeQuotePdf(q);if($('qvEmail'))$('qvEmail').onclick=()=>sendQuote(q);if($('qvApprove'))$('qvApprove').onclick=()=>setQuoteStatus(q.id,'approved');if($('qvReject'))$('qvReject').onclick=()=>setQuoteStatus(q.id,'rejected');if($('qvInvoice'))$('qvInvoice').onclick=()=>quoteToInvoice(q.id)}
  async function setQuoteStatus(id,status){const {error}=await client().from('quotes').update({status,updated_at:new Date().toISOString()}).eq('id',id);if(error)return toast(error.message);toast('Quote status updated.');renderQuotes();openQuote(id)}
  function makeQuotePdf(q,output='save'){const jsPDF=window.jspdf?.jsPDF;if(!jsPDF)return toast('PDF library is not available.');const d=new jsPDF(),s=currentBusinessSettings(),tr=s.trading||s.company||business()?.name||'Business';d.setFontSize(18);d.text(tr,15,18);d.setFontSize(26);d.text('QUOTE',195,18,{align:'right'});d.setFontSize(10);d.text(q.quote_number,195,25,{align:'right'});d.text((s.address||'').split('\n'),15,26);d.text(`Quote date: ${q.quote_date}`,195,34,{align:'right'});d.text(`Valid until: ${q.valid_until||'—'}`,195,40,{align:'right'});d.setFontSize(11);d.text('Quote To',15,52);d.setFontSize(10);d.text([q.customer_name||'',...(String(q.customer_address||'').split('\n')),q.customer_email||''],15,59);d.autoTable({startY:82,head:[['Description','Amount (ex GST)']],body:[[q.description,money(q.quoted_price_ex_gst)]],theme:'grid',styles:{fontSize:10},columnStyles:{1:{halign:'right'}}});let y=d.lastAutoTable.finalY+10;d.text(`Subtotal: ${money(q.quoted_price_ex_gst)}`,195,y,{align:'right'});d.text(`GST (${num(q.gst_rate)}%): ${money(q.gst_amount)}`,195,y+7,{align:'right'});d.setFontSize(12);d.text(`Total: ${money(q.total_incl_gst)}`,195,y+16,{align:'right'});d.setFontSize(9);if(q.notes){d.text('Notes:',15,y+25);d.text(d.splitTextToSize(q.notes,180),15,y+31)}if(q.terms){d.text('Terms:',15,y+48);d.text(d.splitTextToSize(q.terms,180),15,y+54)}const filename=`${q.quote_number}.pdf`;if(output==='blob'){const data=d.output('datauristring').split(',')[1];return{base64:data,filename}}d.save(filename)}
  async function sendQuote(q){const to=String(q.customer_email||'').trim();if(!to)return toast('This customer does not have a billing email address.');const pdf=makeQuotePdf(q,'blob');const {error}=await client().functions.invoke('send-quote',{body:{quoteId:q.id,to,pdfBase64:pdf.base64,filename:pdf.filename}});if(error)return toast('Quote email failed: '+error.message);await client().from('quotes').update({status:q.status==='draft'?'sent':q.status,last_sent_to:to,last_sent_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',q.id);toast('Quote emailed successfully.');renderQuotes();openQuote(q.id)}
  async function quoteToInvoice(id){const q=await getQuote(id);if(!q)return;if(q.status!=='approved')return toast('Mark the quote as Approved before creating an invoice.');$('quoteModal').classList.remove('open');if(window.prefillInvoiceFromQuote)await window.prefillInvoiceFromQuote(q)}

  function renderSettings(){loadCfg();$('jcSetLabourRate').value=cfg.labourRate;$('jcSetMargin').value=cfg.margin;$('jcSetValidity').value=cfg.validityDays;$('jcSetCostingPrefix').value=cfg.costingPrefix;$('jcSetQuotePrefix').value=cfg.quotePrefix;$('jcSetQuoteTerms').value=cfg.quoteTerms;renderPresets()}
  function renderPresets(){const r=$('jcPresetRows');r.innerHTML=cfg.presets.map((x,i)=>`<div class="settings-row jc-preset-row"><input data-jp="${i}" data-k="name" value="${esc(x.name)}" placeholder="Description"><input data-jp="${i}" data-k="unit" value="${esc(x.unit||'item')}" placeholder="Unit"><input type="number" min="0" step="0.01" data-jp="${i}" data-k="unitCost" value="${num(x.unitCost)}" placeholder="Unit cost"><button class="danger" data-jp-remove="${i}">Remove</button></div>`).join('')||'<p class="hint">No cost presets.</p>';r.querySelectorAll('[data-jp]').forEach(e=>e.oninput=ev=>cfg.presets[+ev.target.dataset.jp][ev.target.dataset.k]=ev.target.dataset.k==='unitCost'?num(ev.target.value):ev.target.value);r.querySelectorAll('[data-jp-remove]').forEach(b=>b.onclick=()=>{cfg.presets.splice(+b.dataset.jpRemove,1);renderPresets()})}
  async function saveSettings(){cfg={...cfg,labourRate:num($('jcSetLabourRate').value),margin:num($('jcSetMargin').value),validityDays:Math.max(1,Math.floor(num($('jcSetValidity').value)||14)),costingPrefix:cleanPrefix($('jcSetCostingPrefix').value,'JC'),quotePrefix:cleanPrefix($('jcSetQuotePrefix').value,'QUO'),quoteTerms:$('jcSetQuoteTerms').value.trim(),presets:cfg.presets};const all={...currentBusinessSettings(),jobCostingSettings:cfg};const {error}=await client().from('businesses').update({settings:all,updated_at:new Date().toISOString()}).eq('id',business().id);if(error)return toast(error.message);business().settings=all;const local=JSON.parse(localStorage.getItem('invoice_app_settings')||'{}');localStorage.setItem('invoice_app_settings',JSON.stringify({...local,jobCostingSettings:cfg}));toast('Job costing settings saved.');fresh()}
  function showTab(name){document.querySelectorAll('[data-jc-tab]').forEach(b=>b.classList.toggle('active',b.dataset.jcTab===name));document.querySelectorAll('.jc-panel').forEach(p=>p.classList.toggle('active',p.id===`jc-panel-${name}`));if(name==='saved')renderSaved();if(name==='quotes')renderQuotes();if(name==='settings')renderSettings()}
  async function onShow(){refreshCustomers();if(!$('jcNumber').value)await fresh()}
  function bind(){document.querySelectorAll('[data-jc-tab]').forEach(b=>b.onclick=()=>showTab(b.dataset.jcTab));$('jcNewCostingTop').onclick=async()=>{await fresh();showTab('costing')};$('jcAddLabour').onclick=()=>{labour.push({description:'Labour',hours:0,rate:cfg.labourRate});renderLabour()};$('jcAddCost').onclick=()=>{costs.push({description:'',qty:1,unit:'item',unitCost:0});renderCosts()};$('jcAddField').onclick=()=>{fields.push({label:'',value:''});renderFields()};$('jcMargin').oninput=()=>{delete $('jcQuotePrice').dataset.touched;recalc()};$('jcQuotePrice').oninput=()=>{$('jcQuotePrice').dataset.touched='1';recalc()};$('jcCustomerName').onchange=e=>selectCustomer(e.target.value);$('jcCustomerName').onblur=e=>selectCustomer(e.target.value);$('jcSaveCosting').onclick=()=>saveCosting();$('jcCreateQuote').onclick=createQuote;$('jcClearCosting').onclick=fresh;$('jcSavedSearch').oninput=renderSaved;$('jcSavedRefresh').onclick=renderSaved;$('jcQuoteSearch').oninput=renderQuotes;$('jcQuoteStatusFilter').onchange=renderQuotes;$('jcQuoteRefresh').onclick=renderQuotes;$('jcAddPreset').onclick=()=>{cfg.presets.push({name:'',unit:'item',unitCost:0});renderPresets()};$('jcSaveSettings').onclick=saveSettings;$('closeQuoteModal').onclick=()=>{$('quoteModal').classList.remove('open')};$('quoteModal').onclick=e=>{if(e.target===$('quoteModal'))$('quoteModal').classList.remove('open')}}
  function init(){loadCfg();bind();refreshCustomers();fresh()}
  window.JobCosting={init,onShow,showTab,renderQuotes};
})();
