-- V61.71B-P6 Finlo Live Voice additive foundation + admin controls.
-- Applied to production in two migrations: v6171b_p6_finlo_live_voice and v6171b_p6_live_voice_admin_controls.
-- No financial/accounting tables are modified.
CREATE TABLE IF NOT EXISTS public.finlo_live_voice_settings (id boolean PRIMARY KEY DEFAULT true CHECK(id=true),global_enabled boolean NOT NULL DEFAULT false,emergency_disabled boolean NOT NULL DEFAULT false,model text NOT NULL DEFAULT 'gpt-realtime-2.1-mini',voice text NOT NULL DEFAULT 'marin',max_session_minutes integer NOT NULL DEFAULT 15 CHECK(max_session_minutes BETWEEN 1 AND 60),monthly_session_limit integer NOT NULL DEFAULT 30 CHECK(monthly_session_limit>=0),updated_at timestamptz NOT NULL DEFAULT now(),updated_by uuid);
ALTER TABLE public.finlo_live_voice_settings ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.finlo_live_voice_settings FROM anon,authenticated;
INSERT INTO public.finlo_live_voice_settings(id) VALUES(true) ON CONFLICT(id) DO NOTHING;
CREATE TABLE IF NOT EXISTS public.finlo_live_voice_usage (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),business_id uuid NOT NULL REFERENCES public.businesses(id) ON DELETE CASCADE,user_id uuid NOT NULL,session_id text,model text NOT NULL,started_at timestamptz NOT NULL DEFAULT now(),ended_at timestamptz,duration_seconds integer,status text NOT NULL DEFAULT 'started' CHECK(status IN('started','ended','failed')),created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS finlo_live_voice_usage_business_started_idx ON public.finlo_live_voice_usage(business_id,started_at DESC);
ALTER TABLE public.finlo_live_voice_usage ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.finlo_live_voice_usage FROM anon,authenticated;
INSERT INTO public.modules(slug,name,description,monthly_price,is_active) SELECT 'finlo_live_voice','Finlo Live Voice','Natural realtime voice conversations with Finlo Helper',0,true WHERE NOT EXISTS(SELECT 1 FROM public.modules WHERE slug='finlo_live_voice');
-- Authoritative deployed RPC definitions are documented in V61.71B-P6-IMPLEMENTATION-REPORT.md and production migrations.


-- Controlled RPCs (same definitions applied in production).
CREATE OR REPLACE FUNCTION public.v6171b_p6_live_voice_status() RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE bid uuid:=current_business_id(); uid uuid:=auth.uid(); cfg public.finlo_live_voice_settings; mid uuid; ent public.optional_addon_entitlements; used int:=0; ps timestamptz; pe timestamptz; sub public.subscriptions; st text:='not_subscribed'; entitled boolean:=false;
BEGIN
 IF bid IS NULL OR uid IS NULL THEN RAISE EXCEPTION 'No active business' USING errcode='42501'; END IF;
 IF NOT EXISTS(SELECT 1 FROM business_memberships WHERE business_id=bid AND user_id=uid AND status='active') THEN RAISE EXCEPTION 'Active membership required' USING errcode='42501'; END IF;
 SELECT * INTO cfg FROM finlo_live_voice_settings WHERE id=true; SELECT id INTO mid FROM modules WHERE slug='finlo_live_voice';
 SELECT * INTO ent FROM optional_addon_entitlements WHERE business_id=bid AND module_id=mid AND (starts_at IS NULL OR starts_at<=now()) AND (ends_at IS NULL OR ends_at>now());
 IF ent.business_id IS NOT NULL THEN st:=ent.entitlement_state; END IF; entitled:=st IN('subscribed','included_with_plan','trial','complimentary');
 SELECT * INTO sub FROM subscriptions WHERE business_id=bid ORDER BY created_at DESC LIMIT 1;
 IF sub.id IS NOT NULL AND sub.current_period_start IS NOT NULL AND sub.current_period_end IS NOT NULL THEN ps:=sub.current_period_start;pe:=sub.current_period_end; ELSE ps:=date_trunc('month',now());pe:=ps+interval '1 month'; END IF;
 SELECT count(*) INTO used FROM finlo_live_voice_usage WHERE business_id=bid AND status IN('started','ended') AND started_at>=ps AND started_at<pe;
 RETURN jsonb_build_object('enabled',cfg.global_enabled AND NOT cfg.emergency_disabled AND entitled AND used<coalesce(ent.allowance_override,cfg.monthly_session_limit),'global_enabled',cfg.global_enabled,'emergency_disabled',cfg.emergency_disabled,'entitlement',st,'entitled',entitled,'used_sessions',used,'session_limit',coalesce(ent.allowance_override,cfg.monthly_session_limit),'remaining_sessions',greatest(coalesce(ent.allowance_override,cfg.monthly_session_limit)-used,0),'max_session_minutes',cfg.max_session_minutes,'model',cfg.model,'voice',cfg.voice,'period_start',ps,'next_reset',pe);
END $$;
REVOKE ALL ON FUNCTION public.v6171b_p6_live_voice_status() FROM public,anon; GRANT EXECUTE ON FUNCTION public.v6171b_p6_live_voice_status() TO authenticated;

CREATE OR REPLACE FUNCTION public.v6171b_p6_admin_live_voice_save(p_enabled boolean,p_emergency boolean,p_model text,p_voice text,p_max_minutes integer,p_monthly_limit integer) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
BEGIN IF NOT is_super_admin() THEN RAISE EXCEPTION 'Super admin required' USING errcode='42501'; END IF; IF p_model NOT IN('gpt-realtime-2.1','gpt-realtime-2.1-mini') THEN RAISE EXCEPTION 'Unsupported realtime model'; END IF; IF coalesce(trim(p_voice),'')='' THEN RAISE EXCEPTION 'Voice required'; END IF; UPDATE finlo_live_voice_settings SET global_enabled=p_enabled,emergency_disabled=p_emergency,model=p_model,voice=trim(p_voice),max_session_minutes=greatest(1,least(p_max_minutes,60)),monthly_session_limit=greatest(0,p_monthly_limit),updated_at=now(),updated_by=auth.uid() WHERE id=true; RETURN (SELECT to_jsonb(s) FROM finlo_live_voice_settings s WHERE id=true); END $$;
REVOKE ALL ON FUNCTION public.v6171b_p6_admin_live_voice_save(boolean,boolean,text,text,integer,integer) FROM public,anon; GRANT EXECUTE ON FUNCTION public.v6171b_p6_admin_live_voice_save(boolean,boolean,text,text,integer,integer) TO authenticated;

CREATE OR REPLACE FUNCTION public.v6171b_p6_admin_live_voice_overview() RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
BEGIN IF NOT is_super_admin() THEN RAISE EXCEPTION 'Super admin required' USING errcode='42501'; END IF; RETURN jsonb_build_object('settings',(SELECT to_jsonb(s) FROM finlo_live_voice_settings s WHERE id=true),'businesses',(SELECT coalesce(jsonb_agg(jsonb_build_object('business_id',b.id,'business',b.name,'entitlement',coalesce(e.entitlement_state,'not_subscribed'),'allowance_override',e.allowance_override,'sessions',coalesce(x.sessions,0),'seconds',coalesce(x.seconds,0),'last_used',x.last_used) ORDER BY b.name),'[]'::jsonb) FROM businesses b LEFT JOIN modules m ON m.slug='finlo_live_voice' LEFT JOIN optional_addon_entitlements e ON e.business_id=b.id AND e.module_id=m.id LEFT JOIN LATERAL(SELECT count(*) sessions,coalesce(sum(duration_seconds),0) seconds,max(started_at) last_used FROM finlo_live_voice_usage u WHERE u.business_id=b.id AND u.started_at>=date_trunc('month',now())) x ON true),'kpis',jsonb_build_object('sessions_this_month',(SELECT count(*) FROM finlo_live_voice_usage WHERE started_at>=date_trunc('month',now())),'businesses_using',(SELECT count(distinct business_id) FROM finlo_live_voice_usage WHERE started_at>=date_trunc('month',now())),'minutes_this_month',(SELECT round(coalesce(sum(duration_seconds),0)/60.0,1) FROM finlo_live_voice_usage WHERE started_at>=date_trunc('month',now())),'failed_sessions',(SELECT count(*) FROM finlo_live_voice_usage WHERE status='failed' AND started_at>=date_trunc('month',now())))); END $$;
REVOKE ALL ON FUNCTION public.v6171b_p6_admin_live_voice_overview() FROM public,anon; GRANT EXECUTE ON FUNCTION public.v6171b_p6_admin_live_voice_overview() TO authenticated;

CREATE OR REPLACE FUNCTION public.v6171b_p6_admin_live_voice_entitlement(p_business_id uuid,p_entitlement text,p_allowance integer DEFAULT NULL) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE mid uuid; BEGIN IF NOT is_super_admin() THEN RAISE EXCEPTION 'Super admin required' USING errcode='42501'; END IF; IF p_entitlement NOT IN('not_subscribed','subscribed','included_with_plan','trial','complimentary','suspended') THEN RAISE EXCEPTION 'Invalid entitlement'; END IF; SELECT id INTO mid FROM modules WHERE slug='finlo_live_voice'; INSERT INTO optional_addon_entitlements(business_id,module_id,entitlement_state,allowance_override,updated_at,updated_by) VALUES(p_business_id,mid,p_entitlement,p_allowance,now(),auth.uid()) ON CONFLICT(business_id,module_id) DO UPDATE SET entitlement_state=excluded.entitlement_state,allowance_override=excluded.allowance_override,updated_at=now(),updated_by=auth.uid(); RETURN jsonb_build_object('ok',true); END $$;
REVOKE ALL ON FUNCTION public.v6171b_p6_admin_live_voice_entitlement(uuid,text,integer) FROM public,anon; GRANT EXECUTE ON FUNCTION public.v6171b_p6_admin_live_voice_entitlement(uuid,text,integer) TO authenticated;
