import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const json=(x:any,status=200)=>new Response(JSON.stringify(x),{status,headers:{...cors,'Content-Type':'application/json'}});
const norm=(x:any)=>String(x||'').trim().toLowerCase();
const TEST_REFERRAL_EMAILS=new Set(['damionrod@gmail.com','damionrod@yahoo.com']);
const isTestReferralEmail=(email:any)=>TEST_REFERRAL_EMAILS.has(norm(email));
const esc=(s:any)=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]||m));
const token=()=>{const b=new Uint8Array(32);crypto.getRandomValues(b);return btoa(String.fromCharCode(...b)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')};
const hash=async(s:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(b=>b.toString(16).padStart(2,'0')).join('');
const baseUrl=(v:any)=>{try{const u=new URL(String(v||''));if(!['http:','https:'].includes(u.protocol))return '';u.search='';u.hash='';return u.toString()}catch{return ''}};
Deno.serve(async req=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors});
 try{
  const url=Deno.env.get('SUPABASE_URL')!,serviceKey=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,resend=Deno.env.get('RESEND_API_KEY'),from=Deno.env.get('EMAIL_FROM_ADDRESS');
  if(!resend||!from)return json({error:'Referral email is not configured.'},500);
  const bearer=(req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'');if(!bearer)return json({error:'Not authenticated'},401);
  const db=createClient(url,serviceKey,{auth:{persistSession:false,autoRefreshToken:false}});
  const {data:{user}}=await db.auth.getUser(bearer);if(!user)return json({error:'Not authenticated'},401);
  const {data:p}=await db.from('profiles').select('active_business_id,business_id').eq('id',user.id).single();const bid=p?.active_business_id||p?.business_id;if(!bid)return json({error:'No active business.'},403);
  const {data:m}=await db.from('business_memberships').select('role,status').eq('business_id',bid).eq('user_id',user.id).maybeSingle();if(!m||m.status!=='active')return json({error:'Active business membership required.'},403);
  const body=await req.json().catch(()=>({})),action=String(body.action||'send');
  const {data:camp}=await db.from('referral_campaigns').select('*').eq('active',true).lte('start_date',new Date().toISOString()).or(`end_date.is.null,end_date.gt.${new Date().toISOString()}`).order('start_date',{ascending:false}).limit(1).maybeSingle();
  if(!camp)return json({error:'The referral campaign is not currently active.'},409);
  const {data:ver}=await db.from('referral_campaign_versions').select('*').eq('campaign_id',camp.id).lte('effective_from',new Date().toISOString()).order('version',{ascending:false}).limit(1).maybeSingle();if(!ver)return json({error:'Referral reward configuration is unavailable.'},500);
  let {data:codeRow}=await db.from('business_referral_codes').select('*').eq('business_id',bid).eq('active',true).maybeSingle();
  if(!codeRow){for(let n=0;n<5&&!codeRow;n++){const code=Array.from(crypto.getRandomValues(new Uint8Array(6))).map(b=>b.toString(16).padStart(2,'0')).join('').slice(0,10).toUpperCase();const {data,error}=await db.from('business_referral_codes').insert({business_id:bid,referral_code:code}).select('*').single();if(!error)codeRow=data}if(!codeRow)return json({error:'Could not create referral code.'},500)}
  const sendMail=async(inv:any,rawToken:string,redirect:string)=>{const b=baseUrl(redirect);if(!b)throw new Error('Open Finlo from its deployed http/https address before sending referrals.');const u=new URL(b);u.searchParams.set('ref',codeRow.referral_code);u.searchParams.set('rid',rawToken);const {data:biz}=await db.from('businesses').select('name').eq('id',bid).single();const html=`<div style="font-family:Arial,sans-serif;line-height:1.6;color:#24313a"><h2>${esc(camp.email_heading)}</h2><p><strong>${esc(biz?.name||'A Finlo business')}</strong> has invited you to try Finlo.</p><p>${esc(camp.email_text||camp.promo_text)}</p><p><a href="${esc(u.toString())}" style="display:inline-block;padding:10px 16px;background:#2f8dbc;color:#fff;text-decoration:none;border-radius:4px">Join Finlo</a></p><p style="font-size:12px;color:#71808b">This invitation is linked to the current Finlo referral campaign.</p></div>`;const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${resend}`,'Content-Type':'application/json'},body:JSON.stringify({from:`Finlo <${from}>`,to:[inv.invited_email],subject:`${biz?.name||'A business'} invited you to Finlo`,html})});const d=await r.json();if(!r.ok)throw new Error(d?.message||'Email provider rejected the referral invitation.');return d.id};
  if(action==='send'){
   const email=norm(body.email);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return json({error:'Enter a valid email address.'},400);if(email===norm(user.email)&&!isTestReferralEmail(email))return json({error:'You cannot refer your own login email.'},409);
   const {data:existing}=await db.from('profiles').select('id').ilike('email',email).limit(1);if(existing?.length&&!isTestReferralEmail(email))return json({error:'This email already belongs to a Finlo account.'},409);
   const oneHour=new Date(Date.now()-3600000).toISOString(),oneDay=new Date(Date.now()-86400000).toISOString(),cool=new Date(Date.now()-15*60000).toISOString();
   const [{count:userHour},{count:bizDay},{data:dupe}]=await Promise.all([db.from('referral_invites').select('id',{head:true,count:'exact'}).eq('sent_by_user_id',user.id).gte('last_sent_at',oneHour),db.from('referral_invites').select('id',{head:true,count:'exact'}).eq('referring_business_id',bid).gte('last_sent_at',oneDay),db.from('referral_invites').select('id,last_sent_at,status,resend_count').eq('referring_business_id',bid).ilike('invited_email',email).order('created_at',{ascending:false}).limit(1).maybeSingle()]);
   if((userHour||0)>=20)return json({error:'You have sent several referrals recently. Please try again later.'},429);if((bizDay||0)>=100)return json({error:'This business has reached today’s referral email safety limit.'},429);if(dupe&&new Date(dupe.last_sent_at)>=new Date(cool)&&!isTestReferralEmail(email))return json({error:'This email was invited recently. Please wait before resending.'},429);if(dupe&&['signed_up','qualified','reward_issued'].includes(dupe.status)&&!isTestReferralEmail(email))return json({error:'This referral has already progressed beyond invitation.'},409);
   const raw=token(),tokenHash=await hash(raw);let inv:any;
   if(dupe&&['invited','failed'].includes(dupe.status)){const {data}=await db.from('referral_invites').update({campaign_id:camp.id,campaign_version_id:ver.id,token_hash:tokenHash,status:'invited',last_sent_at:new Date().toISOString(),resend_count:Number(dupe.resend_count||0)+1,updated_at:new Date().toISOString()}).eq('id',dupe.id).select('*').single();inv=data}else{const {data,error}=await db.from('referral_invites').insert({referring_business_id:bid,invited_email:email,referral_code:codeRow.referral_code,campaign_id:camp.id,campaign_version_id:ver.id,sent_by_user_id:user.id,token_hash:tokenHash,status:'invited'}).select('*').single();if(error)return json({error:error.message},400);inv=data}
   try{await sendMail(inv,raw,body.redirectUrl)}catch(e){await db.from('referral_invites').update({status:'failed',updated_at:new Date().toISOString()}).eq('id',inv.id);throw e}return json({ok:true,email});
  }
  if(action==='resend'){
   const id=String(body.inviteId||'');const {data:inv}=await db.from('referral_invites').select('*').eq('id',id).eq('referring_business_id',bid).maybeSingle();if(!inv||!['invited','failed'].includes(inv.status))return json({error:'Referral invitation is not available for resend.'},404);if(Date.now()-new Date(inv.last_sent_at).getTime()<15*60000&&!isTestReferralEmail(inv.invited_email))return json({error:'Please wait 15 minutes before resending this invitation.'},429);const raw=token(),tokenHash=await hash(raw);const updated={...inv,token_hash:tokenHash,status:'invited',last_sent_at:new Date().toISOString(),resend_count:Number(inv.resend_count||0)+1,updated_at:new Date().toISOString()};await db.from('referral_invites').update({token_hash:updated.token_hash,status:'invited',last_sent_at:updated.last_sent_at,resend_count:updated.resend_count,updated_at:updated.updated_at}).eq('id',inv.id);await sendMail(updated,raw,body.redirectUrl);return json({ok:true});
  }
  return json({error:'Unknown action.'},400);
 }catch(e){return json({error:e instanceof Error?e.message:'Referral invitation failed'},400)}
});
