const fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..');let n=0;function ok(x,m){if(!x)throw new Error('FAIL: '+m);n++}
const read=p=>fs.readFileSync(path.join(root,p),'utf8'),idx=read('public/index.html'),saas=read('public/saas.js'),app=read('public/app.js'),sch=read('public/schedule.js'),dash=read('public/dashboard.js'),css=read('public/styles.css'),mig=read('supabase/migrations/20260920175500_v6179_phase_b_atomic_schedule_save.sql');
ok(idx.includes('id="view-dashboard"')&&idx.includes('id="dashboardNav"'),'dashboard view/nav');ok(idx.includes('id="view-schedule"')&&/id="scheduleNav"[^>]*hidden/.test(idx),'schedule hidden nav');
ok(saas.includes("'schedule.js?v=61.79-phase-b'")&&saas.includes("'dashboard.js?v=61.79-phase-b'"),'sequential loader');ok(saas.includes('async function getScheduleAccess()'),'shared Schedule access helper');ok(saas.includes("['owner','admin'].includes(role)"),'shared owner/admin Schedule gate');ok(dash.includes('getScheduleAccess()')&&sch.includes('getScheduleAccess?.()'),'Dashboard and Schedule use shared access');
ok(app.includes("if(v==='schedule'&&$('scheduleNav')?.hidden){v='dashboard'}"),'unauthorised direct schedule navigation fails closed');ok(sch.includes(".eq('business_id',requestBid)")&&sch.includes('token!==S.loadToken||bid()!==requestBid'),'Schedule active-business scope/stale discard');
ok(sch.includes(".not('start_at','is',null).lt('start_at',toUtc).gt('end_at',fromUtc)")&&sch.includes(".or('start_at.is.null,status.eq.unscheduled')"),'visible-range scheduled load plus separate unscheduled load');
for(const src of ['scheduled jobs','unscheduled jobs','customers','job costings','quotes','invoices','employees','assignments'])ok(sch.includes(`'${src}'`),`Schedule checks ${src} errors`);ok(sch.includes('S.refReady=!'),'partial reference failure disables editing');
ok(sch.includes("rpc('v6179_save_schedule_with_assignments'"),'Schedule create/edit uses atomic RPC');ok(sch.includes('Save failed. The original job and assignments were preserved.'),'atomic save failure message');ok(sch.includes('Move failed. The job was restored.'),'drag failure rollback');ok(sch.includes("innerWidth<760?'day':'week'"),'mobile day default');
ok(sch.includes('function weekHours(rows)')&&sch.includes('Math.min(first,hour)')&&sch.includes('Math.max(last,hour)'),'Week grid expands beyond default hours for scheduled jobs');
ok(sch.includes('Recurring scheduling coming next')&&!sch.includes("from('job_recurrence_series').insert"),'recurrence creation disabled');ok(sch.includes('zonedToUtc')&&sch.includes('utcToLocal'),'timezone conversion helpers');ok(sch.includes('businessTimezone'),'active-business timezone default');ok(sch.includes("e.key==='Escape'")&&sch.includes("e.key!=='Tab'"),'modal escape and focus trap');ok(sch.includes("if(S.saving)return")&&sch.includes("'Saving…'"),'duplicate-save prevention/loading state');
ok(dash.includes("rpc('v6179_dashboard_summary'")&&dash.includes("rpc('v6179_today_schedule'"),'dashboard Phase A RPC reuse');for(const src of ['dashboard summary','customer payments','invoices','expenses','expense payments','today schedule','bank reconciliation','unscheduled jobs'])ok(dash.includes(`'${src}'`),`Dashboard checks ${src} result`);ok(dash.includes('Some dashboard summary data is unavailable.'),'summary failure visible');ok(dash.includes('Expense payments')&&dash.includes('Money in vs expense payments'),'honest expense-payment label');ok(dash.includes('data-dashboard-retry'),'dashboard retry actions');ok(dash.includes('scheduleAccess.allowed'),'Dashboard Schedule visibility uses shared allowed result');ok(!dash.includes('scheduleEntitled'),'no separate Dashboard Schedule entitlement rule');ok(dash.includes('token!==D.token||bid()!==businessId'),'Dashboard stale-business discard');
ok(css.includes('@media(max-width:759px)')&&css.includes('.mobile-day-list'),'mobile styling');ok(!sch.includes('service_role')&&!dash.includes('service_role'),'no service role frontend');ok(!sch.includes('google_calendar_connections')&&!dash.includes('google_calendar_connections'),'no Google OAuth implementation');
ok(/^begin;/mi.test(mig)&&/commit;/mi.test(mig),'atomic RPC migration transaction bounded');ok(/security invoker/i.test(mig)&&!/security definer/i.test(mig),'RPC SECURITY INVOKER only');ok(/set search_path = pg_catalog, public, auth/i.test(mig),'RPC explicit search_path');ok(/v6179_schedule_role_allowed\(v_business, true\)/.test(mig),'RPC owner/admin entitlement guard');ok(/current_business_id\(\)/.test(mig),'RPC active business verification');ok(/delete from public\.job_schedule_assignments[\s\S]*foreach v_employee[\s\S]*insert into public\.job_schedule_assignments/.test(mig),'assignment replacement in same function');ok(/revoke all on function[\s\S]*from public/i.test(mig)&&/revoke execute[\s\S]*from anon/i.test(mig)&&/grant execute[\s\S]*to authenticated/i.test(mig),'RPC least-privilege execution grants');ok(!/drop\s+[^;]*cascade/i.test(mig),'no DROP CASCADE');
console.log(`${n}/${n} V61.79 Phase B consolidated correction static checks PASS`);
