const fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..');let n=0;function ok(x,m){if(!x)throw new Error('FAIL: '+m);n++}
const read=p=>fs.readFileSync(path.join(root,p),'utf8'),idx=read('public/index.html'),saas=read('public/saas.js'),app=read('public/app.js'),sch=read('public/schedule.js'),dash=read('public/dashboard.js'),css=read('public/styles.css'),mig=read('supabase/migrations/20260920175500_v6179_phase_b_atomic_schedule_save.sql'),fix=read('supabase/migrations/20260920220000_v6179e_schedule_integrity_correction.sql'),enh=read('supabase/migrations/20260921200000_v6179g_eligible_quote_schedule_recurrence.sql');
ok(idx.includes('id="view-dashboard"')&&idx.includes('id="dashboardNav"'),'dashboard view/nav');ok(idx.includes('id="view-schedule"')&&/id="scheduleNav"[^>]*hidden/.test(idx),'schedule hidden nav');
ok(saas.includes("'schedule.js?v=61.79h-quote-recurrence'")&&saas.includes("'dashboard.js?v=61.79i-unscheduled-quote-filter'"),'sequential loader and corrected Schedule cache key');ok(idx.includes('styles.css?v=61.79h-quote-recurrence')&&idx.includes('saas.js?v=61.79h-quote-recurrence'),'corrected CSS and entitlement code cache keys');ok(saas.includes('async function getScheduleAccess()'),'shared Schedule access helper');ok(saas.includes("['owner','admin'].includes(role)"),'shared owner/admin Schedule gate');ok(dash.includes('getScheduleAccess()')&&sch.includes('getScheduleAccess?.()'),'Dashboard and Schedule use shared access');ok(dash.includes("rpc('v6179_unscheduled_schedule_count')"),'Dashboard unscheduled count uses quote-aware server filter');
ok(app.includes("if(v==='schedule'&&$('scheduleNav')?.hidden){v='dashboard'}"),'unauthorised direct schedule navigation fails closed');ok(sch.includes(".eq('business_id',requestBid)")&&sch.includes('token!==S.loadToken||bid()!==requestBid'),'Schedule active-business scope/stale discard');
ok(sch.includes(".not('start_at','is',null).lt('start_at',toUtc).gt('end_at',fromUtc)")&&sch.includes(".or('start_at.is.null,status.eq.unscheduled')"),'visible-range scheduled load plus separate unscheduled load');
for(const src of ['scheduled jobs','unscheduled jobs','customers','job costings','quotes','invoices','employees','assignments'])ok(sch.includes(`'${src}'`),`Schedule checks ${src} errors`);ok(sch.includes('S.refReady=!'),'partial reference failure disables editing');
ok(sch.includes("rpc('v6179_save_schedule_with_assignments'"),'Schedule create/edit uses atomic RPC');ok(sch.includes('The original job and assignments were preserved.'),'atomic save failure preserves explicit rollback message');ok(sch.includes('saveErrorMessage(res.error)'),'atomic save failure adds actionable error');ok(sch.includes('Move failed. The job was restored.'),'drag failure rollback');ok(sch.includes("initialCompact?'day':'week'")&&sch.includes('handleViewportChange'),'mobile day default and resize adaptation');
ok(sch.includes('function weekHours(rows)')&&sch.includes('Math.min(first,hour)')&&sch.includes('Math.max(last,hour)'),'Week grid expands beyond default hours for scheduled jobs');
ok(sch.includes("e.preferred_name||e.first_name")&&!sch.includes('e.preferred_name,e.first_name,e.last_name'),'employee display uses preferred-name fallback');ok(sch.includes('<label>Timezone<select id="sjTimezone">')&&sch.includes('Intl.supportedValuesOf'),'timezone input constrained to validated choices');
ok(sch.includes("employment_status,archived")&&sch.includes("!['terminated','inactive'].includes")&&sch.includes('validEmployeeIds'),'employee picker and save payload exclude unavailable records');
ok(sch.includes('upgradeEmployeePicker')&&sch.includes('MutationObserver')&&sch.includes('type="checkbox" name="sjEmployee"')&&sch.includes('selectedEmployeeIds()')&&css.includes('.schedule-employee-choice'),'employee assignment uses optional multi-checkbox UI');
ok(sch.includes('Repeat this job (optional)')&&sch.includes('sjRecurring')&&sch.includes('recurrencePayload'),'recurrence is optional and user-controlled');ok(sch.includes('v6179_schedule_eligible_quotes')&&sch.includes('virtual_quote')&&sch.includes('quote:${q.id}'),'eligible quotes appear without schedule rows');ok(sch.includes("['sent','accepted','approved','won']")&&sch.includes('statusByQuote'),'quote statuses are filtered before rendering');ok(sch.includes('Quote scheduled.')&&sch.includes('r.virtual_quote'),'quote drag creates a schedule through the atomic RPC');ok(sch.includes('zonedToUtc')&&sch.includes('utcToLocal'),'timezone conversion helpers');ok(sch.includes('businessTimezone'),'active-business timezone default');ok(sch.includes("e.key==='Escape'")&&sch.includes("e.key!=='Tab'"),'modal escape and focus trap');ok(sch.includes("if(S.saving)return")&&sch.includes("'Saving…'"),'duplicate-save prevention/loading state');
ok(dash.includes("rpc('v6179_dashboard_summary'")&&dash.includes("rpc('v6179_today_schedule'"),'dashboard Phase A RPC reuse');for(const src of ['dashboard summary','customer payments','invoices','expenses','expense payments','today schedule','bank reconciliation','unscheduled jobs'])ok(dash.includes(`'${src}'`),`Dashboard checks ${src} result`);ok(dash.includes('Some dashboard summary data is unavailable.'),'summary failure visible');ok(dash.includes('Expense payments')&&dash.includes('Money in vs expense payments'),'honest expense-payment label');ok(dash.includes('data-dashboard-retry'),'dashboard retry actions');ok(dash.includes('scheduleAccess.allowed'),'Dashboard Schedule visibility uses shared allowed result');ok(!dash.includes('scheduleEntitled'),'no separate Dashboard Schedule entitlement rule');ok(dash.includes('token!==D.token||bid()!==businessId'),'Dashboard stale-business discard');
ok(css.includes('@media(max-width:759px)')&&css.includes('.mobile-day-list'),'mobile styling');ok(!sch.includes('service_role')&&!dash.includes('service_role'),'no service role frontend');ok(!sch.includes('google_calendar_connections')&&!dash.includes('google_calendar_connections'),'no Google OAuth implementation');
ok(/^begin;/mi.test(mig)&&/commit;/mi.test(mig),'atomic RPC migration transaction bounded');ok(/security invoker/i.test(mig)&&!/security definer/i.test(mig),'RPC SECURITY INVOKER only');ok(/set search_path = pg_catalog, public, auth/i.test(mig),'RPC explicit search_path');ok(/v6179_schedule_role_allowed\(v_business, true\)/.test(mig),'RPC owner/admin entitlement guard');ok(/current_business_id\(\)/.test(mig),'RPC active business verification');ok(/delete from public\.job_schedule_assignments[\s\S]*foreach v_employee[\s\S]*insert into public\.job_schedule_assignments/.test(mig),'assignment replacement in same function');ok(/revoke all on function[\s\S]*from public/i.test(mig)&&/revoke execute[\s\S]*from anon/i.test(mig)&&/grant execute[\s\S]*to authenticated/i.test(mig),'RPC least-privilege execution grants');ok(!/drop\s+[^;]*cascade/i.test(mig),'no DROP CASCADE');
ok(/^begin;/mi.test(fix)&&/commit;/mi.test(fix),'integrity correction migration transaction bounded');ok(/security invoker/i.test(fix)&&!/security definer/i.test(fix),'integrity correction remains SECURITY INVOKER');ok(/not \(a\.employee_id=any\(coalesce\(p_employee_ids/.test(fix)&&/on conflict \(schedule_id,employee_id\) do nothing/.test(fix),'assignment diff preserves retained progress rows');ok(!/delete from public\.job_schedule_assignments[\s\S]*where a\.schedule_id=v_schedule\.id and a\.business_id=v_business;\s*foreach/i.test(fix),'integrity correction does not delete all assignments');ok(/coalesce\(nullif\(btrim\(e\.preferred_name\),''\),e\.first_name\)/.test(fix),'dashboard Schedule names use preferred-name fallback');ok(/revoke all on function[\s\S]*from public/i.test(fix)&&/revoke execute[\s\S]*from anon/i.test(fix)&&/grant execute[\s\S]*to authenticated/i.test(fix),'integrity correction preserves RPC grants');ok(/^begin;/mi.test(enh)&&/commit;/mi.test(enh),'quote/recurrence migration transaction bounded');ok(/v6179_schedule_eligible_quotes/.test(enh)&&/status in \('sent','accepted','approved','won'\)/.test(enh),'server-side eligible quote filtering');ok(/job_schedules_business_quote_one_time_uidx/.test(enh),'one-time quote duplicate guard');ok(/selected_dates/.test(enh)&&/generate_series/.test(enh)&&/on conflict \(business_id,recurrence_series_id,recurrence_occurrence_date\) do nothing/.test(enh),'transactional recurrence generation and idempotency');ok(/Quote is not eligible for scheduling/.test(enh)&&/v6179_validate_schedule_refs/.test(enh),'rejected/cross-tenant quote guard');
ok(css.includes('.week-day{min-height:980px!important}'),'requested Week min-height remains unchanged');ok(/const\[a\]=range\(\),days=.*hours=weekHours\(rows\)/.test(sch),'requested shared Week hour range remains unchanged');ok(!sch.includes('day-current-time')&&!sch.includes('ambiguous local time'),'optional Day marker and DST ambiguity handling remain unchanged');ok(css.includes('mask-image:linear-gradient')&&css.includes('.dashboard-actions')&&css.includes('.pulse-grid'),'mobile horizontal rows include scroll affordance');ok(saas.includes('moduleAccessCache')&&saas.includes("select('status,trial_ends_at,modules!inner(slug)')"),'module entitlements share a short-lived batch cache');
console.log(`${n}/${n} V61.79 Phase B consolidated correction static checks PASS`);
