const fs=require('fs'),vm=require('vm'),path=require('path');let n=0;function ok(x,m){if(!x)throw new Error('FAIL: '+m);n++}const root=path.resolve(__dirname,'..');
class El{constructor(id=''){this.id=id;this.innerHTML='';this.hidden=false;this.disabled=false;this.value='';this.textContent='';this.classList={add(){},remove(){},toggle(){},contains(){return false}}}querySelectorAll(){return[]}querySelector(){return null}appendChild(){}focus(){this.focused=true}setAttribute(k,v){this[k]=v}}
function dom(ids=[]){const map=Object.fromEntries(ids.map(id=>[id,new El(id)]));return {map,document:{getElementById:id=>map[id]||null,createElement:()=>new El(),body:new El('body'),addEventListener(){},removeEventListener(){},querySelectorAll(){return[]},activeElement:null}}}
class Q{constructor(res,delay=0){this.res=res;this.delay=delay}select(){return this}eq(){return this}neq(){return this}gte(){return this}gt(){return this}lt(){return this}not(){return this}or(){return this}order(){return this}in(){return this}update(){return this}delete(){return this}insert(){return this}then(a,b){return new Promise(r=>setTimeout(()=>r(this.res),this.delay)).then(a,b)}}
function scheduleEnv(width=1200){const d=dom([]);let rpcHandler=async()=>({data:{id:'new'},error:null}),fromHandler=()=>new Q({data:[],error:null});const SAAS={state:{business:{id:'A',settings:{timezone:'Pacific/Auckland'}},user:{id:'U'},accessRole:'owner'},currentBusinessId(){return this.state.business.id},client:()=>({rpc:(...a)=>rpcHandler(...a),from:t=>fromHandler(t)}),getScheduleAccess:async()=>({businessId:'A',entitled:true,allowed:true,role:'owner'})};const ctx={window:{SAAS,Dashboard:{refresh(){}}},document:d.document,innerWidth:width,Intl,Date,Event:class{constructor(type,options){this.type=type;Object.assign(this,options)}},console,setTimeout,clearTimeout,confirm:()=>true};ctx.window.window=ctx.window;vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(root,'public/schedule.js'),'utf8'),ctx);return {ctx,S:ctx.window.Schedule,_setRpc:f=>rpcHandler=f,_setFrom:f=>fromHandler=f,dom:d,SAAS}}
(async()=>{
  const e=scheduleEnv();e.S.setAccess({businessId:'A',entitled:true,allowed:true});
  let call=null;e._setRpc(async(name,args)=>{call={name,args};return {data:{id:'S1'},error:null}});let r=await e.S._test.atomicSave(null,{business_id:'A',title:'Create',timezone:'Pacific/Auckland',status:'unscheduled'},['E1']);ok(!r.error&&call.name==='v6179_save_schedule_with_assignments'&&call.args.p_schedule_id===null&&call.args.p_employee_ids[0]==='E1','successful schedule creation uses atomic RPC');e.S._test.state.saving=false;
  e._setRpc(async(name,args)=>{call={name,args};return {data:{id:'S0'},error:null}});r=await e.S._test.atomicSave(null,{business_id:'A',title:'Unassigned',timezone:'Pacific/Auckland',status:'scheduled'},[]);ok(!r.error&&call.args.p_employee_ids.length===0,'scheduled job saves without an employee assignment');e.S._test.state.saving=false;
  e._setRpc(async(name,args)=>{call={name,args};return {data:{id:'SM'},error:null}});r=await e.S._test.atomicSave(null,{business_id:'A',title:'Team job',timezone:'Pacific/Auckland',status:'scheduled'},['E1','E2']);ok(!r.error&&call.args.p_employee_ids.join(',')==='E1,E2','scheduled job saves multiple employee assignments');e.S._test.state.saving=false;
  const existing={id:'S1',business_id:'A',title:'Before'};e.S._test.state.assignments=[{schedule_id:'S1',employee_id:'E1'}];e._setRpc(async(name,args)=>{call={name,args};return {data:{id:'S1'},error:null}});r=await e.S._test.atomicSave(existing,{business_id:'A',title:'After',timezone:'Pacific/Auckland',status:'unscheduled'},['E2']);ok(!r.error&&call.args.p_schedule_id==='S1'&&call.args.p_employee_ids[0]==='E2','successful update uses same atomic RPC');e.S._test.state.saving=false;
  const snapshot=JSON.stringify(existing),asnap=JSON.stringify(e.S._test.state.assignments);e._setRpc(async()=>({data:null,error:{message:'invalid employee'}}));r=await e.S._test.atomicSave(existing,{business_id:'A',title:'Bad',timezone:'Pacific/Auckland',status:'unscheduled'},['BAD']);ok(r.error&&JSON.stringify(existing)===snapshot&&JSON.stringify(e.S._test.state.assignments)===asnap,'atomic assignment failure preserves original complete state');e.S._test.state.saving=false;
  let release;e._setRpc(()=>new Promise(res=>release=res));const first=e.S._test.atomicSave(null,{business_id:'A',title:'One',timezone:'Pacific/Auckland',status:'unscheduled'},[]),second=await e.S._test.atomicSave(null,{business_id:'A',title:'Two',timezone:'Pacific/Auckland',status:'unscheduled'},[]);ok(second.duplicate===true,'duplicate-save prevention');release({data:{id:'S2'},error:null});await first;e.S._test.state.saving=false;
  e.S._test.state.rows=[{id:'D1',business_id:'A',title:'Drag',status:'scheduled',start_at:'2026-09-20T21:00:00.000Z',end_at:'2026-09-20T22:00:00.000Z',timezone:'Pacific/Auckland'}];e._setFrom(()=>new Q({data:[{}],error:null}));await e.S._test.moveToSlot('D1','2026-09-22','10:00');ok(e.S._test.state.rows[0].start_at==='2026-09-21T22:00:00.000Z','drag success persists timezone-correct slot');
  const dragBefore={...e.S._test.state.rows[0]};e._setFrom(()=>new Q({data:null,error:{message:'no'}}));await e.S._test.moveToSlot('D1','2026-09-23','11:00');ok(e.S._test.state.rows[0].start_at===dragBefore.start_at&&e.S._test.state.rows[0].end_at===dragBefore.end_at,'drag rollback restores original position');
  let schedCalls=0;e._setFrom(t=>{if(t==='job_schedules')return new Q({data:[],error:null});if(t==='customers')return new Q({data:null,error:{message:'denied'}});return new Q({data:[],error:null})});await e.S._test.load();ok(e.S._test.state.loadErrors.includes('customers')&&!e.S._test.state.refReady,'failed reference-data loading disables editing');
  e.S._test.state.rows=[{id:'KEEP'}];e._setFrom(()=>new Q({data:[],error:null},20));const pending=e.S._test.load();e.SAAS.state.business.id='B';await pending;ok(e.S._test.state.rows[0]?.id==='KEEP','business switch during loading discards stale response');e.SAAS.state.business.id='A';
  e.dom.map.scheduleRoot=new El('scheduleRoot');e.S.setAccess({businessId:'A',entitled:true,allowed:false});ok(e.dom.map.scheduleRoot.innerHTML.includes('not available'),'staff Schedule hiding');e.S.setAccess({businessId:'A',entitled:false,allowed:false});ok(e.dom.map.scheduleRoot.innerHTML.includes('not available'),'Schedule entitlement disabled');delete e.dom.map.scheduleRoot;
  const mobile=scheduleEnv(390);mobile.S.setAccess({businessId:'A',entitled:true,allowed:true});ok(mobile.S._test.state.view==='day'&&mobile.S._test.renderDay([]).includes('No jobs scheduled'),'mobile day view');
  e.S._test.state.anchor='2026-09-23';
  const evening={id:'L1',business_id:'A',title:'9:07 PM example',customer_name:'Evening customer',status:'scheduled',start_at:e.S._test.zonedToUtc('2026-09-23','21:07','Pacific/Auckland'),end_at:e.S._test.zonedToUtc('2026-09-23','22:07','Pacific/Auckland'),timezone:'Pacific/Auckland'};
  const eveningHtml=e.S._test.renderWeek([evening]);ok(e.S._test.weekHours([evening]).at(-1)===21&&eveningHtml.includes('data-drop-time="21:00"')&&eveningHtml.includes('9:07 PM example'),'9:07 PM job appears in Week view');
  const early={id:'E1',business_id:'A',title:'Early clean',customer_name:'Early customer',status:'scheduled',start_at:e.S._test.zonedToUtc('2026-09-24','06:15','Pacific/Auckland'),end_at:e.S._test.zonedToUtc('2026-09-24','07:15','Pacific/Auckland'),timezone:'Pacific/Auckland'};
  const earlyHtml=e.S._test.renderWeek([early]);ok(e.S._test.weekHours([early])[0]===6&&earlyHtml.includes('data-drop-time="06:00"')&&earlyHtml.includes('Early clean'),'early-morning job extends and appears in Week view');
  const defaultHours=e.S._test.weekHours([]);ok(defaultHours.length===13&&defaultHours[0]===7&&defaultHours.at(-1)===19,'Week view keeps normal 7:00 AM–7:59 PM default hours');
  e.S._test.state.refs.employees=[{id:'N1',preferred_name:'Aroha',first_name:'Aroha',last_name:'Ngata'},{id:'N2',preferred_name:'Jon',first_name:'Jonathan',last_name:'Smith'}];ok(e.S._test.employeeName('N1')==='Aroha Ngata'&&e.S._test.employeeName('N2')==='Jon Smith','Schedule employee names use preferred-name fallback without duplication');
  const available=e.S._test.availableEmployees([{id:'A',employment_status:'active',archived:false},{id:'I',employment_status:'inactive',archived:false},{id:'T',employment_status:'terminated',archived:false},{id:'R',employment_status:'active',archived:true},{id:'N',employment_status:null,archived:null}]);ok(available.map(x=>x.id).join(',')==='A,N','employee picker excludes inactive, terminated and archived records');
  e.S._test.state.refs.employees=available;ok(e.S._test.validEmployeeIds(['A','I','A','R']).join(',')==='A','save payload removes unavailable and duplicate employee IDs');
  const choiceHtml=e.S._test.employeeChoices(['A']);ok(choiceHtml.includes('type="checkbox"')&&choiceHtml.includes('name="sjEmployee"')&&choiceHtml.includes('value="A"')&&choiceHtml.includes('checked'),'employee picker renders real checkboxes and retains selected employees');
  const option={tagName:'OPTION',selected:false,parentElement:{id:'sjEmployees',dispatchEvent(){this.changed=true}}},toggleEvent={target:option,preventDefault(){this.prevented=true}};e.S._test.toggleEmployeeOption(toggleEvent);ok(option.selected&&toggleEvent.prevented&&option.parentElement.changed,'employee picker toggles multiple choices without Ctrl');
  ok(e.S._test.isValidTimezone('Pacific/Auckland')&&!e.S._test.isValidTimezone('Not/A_Real_Zone')&&e.S._test.timezoneOptions('Pacific/Auckland').includes('selected'),'job editor timezone choices are browser-validated');
  ok(e.S._test.saveErrorMessage({message:'job_schedules_timezone_check'})==='Choose a valid timezone and try again.','timezone save errors are actionable');
  e.S._test.state.view='week';e.S._test.state.desktopView='week';e.S._test.state.viewportCompact=false;ok(e.S._test.handleViewportChange(390)&&e.S._test.state.view==='day','desktop-to-mobile resize switches Schedule to Day view');ok(e.S._test.handleViewportChange(1200)&&e.S._test.state.view==='week','mobile-to-desktop resize restores prior desktop view');
  ok(e.S._test.zonedToUtc('2026-06-15','09:00','Pacific/Auckland')==='2026-06-14T21:00:00.000Z','Pacific/Auckland standard-time conversion');ok(e.S._test.zonedToUtc('2026-12-15','09:00','Pacific/Auckland')==='2026-12-14T20:00:00.000Z','Pacific/Auckland daylight-saving conversion');const oldTZ=process.env.TZ;process.env.TZ='America/New_York';ok(e.S._test.zonedToUtc('2026-12-15','09:00','Pacific/Auckland')==='2026-12-14T20:00:00.000Z','conversion independent of browser/device timezone');process.env.TZ=oldTZ;

  const dd=dom(['dashboardRoot']);const SAAS={state:{business:{id:'A',name:'Test Co',settings:{timezone:'Pacific/Auckland',currency:'NZD'}}},currentBusinessId(){return this.state.business.id},getScheduleAccess:async()=>({businessId:'A',entitled:true,allowed:true}),client:()=>({rpc:name=>name==='v6179_dashboard_summary'?Promise.resolve({data:null,error:{message:'summary denied'}}):Promise.resolve({data:[],error:null}),from:t=>new Q(t==='bank_transactions'||t==='job_schedules'?{data:[],count:0,error:null}:{data:[],error:null})})};const dc={window:{SAAS,Schedule:{_test:{zonedToUtc:e.S._test.zonedToUtc}},switchView(){}},document:dd.document,Intl,Date,console,setTimeout,clearTimeout};vm.createContext(dc);vm.runInContext(fs.readFileSync(path.join(root,'public/dashboard.js'),'utf8'),dc);await dc.window.Dashboard.refresh();ok(dd.map.dashboardRoot.innerHTML.includes('Some dashboard summary data is unavailable.')&&!dd.map.dashboardRoot.innerHTML.includes('$0</strong><small>Not available'),'Dashboard query failure shows unavailable—not zero');
  console.log(`${n}/${n} V61.79 Phase B behavioural checks PASS`);
})().catch(e=>{console.error(e);process.exit(1)});
