const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
function harness(){const source=fs.readFileSync('public/purchase-review.js','utf8').replace('window.PurchaseReview={showList,open};','window.PurchaseReview={showList,open,__test:{state,allocations,baseRows,rowHtml,cardHtml,categoryFor}};');const window={SAAS:{state:{business:{id:'bingo',settings:{country:'NZ'}}}}};vm.runInNewContext(source,{window,document:{getElementById:()=>null}});return window.PurchaseReview.__test}
test('saved phone scan prefills several rows, uses and original category without opening bill',()=>{const {state,baseRows,cardHtml}=harness();const bill={id:'b',expense_number:'EXP-004',supplier_name:'NZ Cleaning',category_id:'clean',ex_gst:100,gst_amount:15,total_amount:115,expense_attachments:[{id:'p1'},{id:'p2'}]};state.categories=[{id:'clean',name:'Cleaning'}];state.scans.set('b',{attachment_ids:['p1','p2'],proposals:[{description:'Bucket',amount:20,amount_basis:'ex_gst',gst_treatment:'taxable',suggested_use:'supplies'},{description:'Mop',amount:80,amount_basis:'ex_gst',gst_treatment:'taxable',suggested_use:'stock'}]});state.expanded.add('b');const rows=baseRows(bill);assert.equal(rows.length,2);assert.equal(rows[0].ex_gst,'20.00');assert.equal(rows[0].gst,'3.00');assert.equal(rows[1].gst,'12.00');assert.equal(rows[0].category_id,'clean');assert.equal(rows[0].kind,'supplies');assert.match(cardHtml(bill),/Bucket/);assert.match(cardHtml(bill),/Mop/);assert.match(cardHtml(bill),/\$115.00 incl GST/)});
test('GST-free and mixed-tax lines use only confirmed tax evidence',()=>{const {allocations}=harness();const zero=allocations([{description:'No GST',amount:50,amount_basis:'incl_gst',gst_treatment:'unknown'}],{ex_gst:50,gst_amount:0,total_amount:50});assert.equal(zero[0].gst,'0.00');const mixed=allocations([{description:'taxed',amount:100,amount_basis:'ex_gst',gst_treatment:'taxable'},{description:'exempt',amount:50,amount_basis:'ex_gst',gst_treatment:'no_gst'}],{ex_gst:150,gst_amount:15,total_amount:165});assert.equal(mixed[0].gst,'15.00');assert.equal(mixed[1].gst,'0.00');const unclear=allocations([{description:'taxed?',amount:100,amount_basis:'ex_gst',gst_treatment:'unknown'},{description:'exempt',amount:50,amount_basis:'ex_gst',gst_treatment:'no_gst'}],{ex_gst:150,gst_amount:15,total_amount:165});assert.equal(unclear[0].gst,'')});
test('inclusive GST allocates correctly and incomplete source stays unresolved',()=>{const {allocations}=harness();const incl=allocations([{description:'A',amount:23,amount_basis:'incl_gst',gst_treatment:'taxable'},{description:'B',amount:92,amount_basis:'incl_gst',gst_treatment:'taxable'}],{ex_gst:100,gst_amount:15,total_amount:115});assert.equal(JSON.stringify(incl.map(x=>[x.ex_gst,x.gst])),JSON.stringify([['20.00','3.00'],['80.00','12.00']]));const incomplete=allocations([{description:'Missing items',amount:20.22,amount_basis:'unknown',gst_treatment:'unknown'}],{ex_gst:361.94,gst_amount:54.29,total_amount:416.23});assert.equal(incomplete[0].ex_gst,'');assert.equal(incomplete[0].gst,'')});
test('single compact row exposes amount columns, editable categories and equipment details',()=>{const {rowHtml,state}=harness();state.categories=[{id:'a',name:'Default'},{id:'b',name:'Changed'}];const markup=rowHtml({description:'Machine',kind:'equipment',category_id:'a',quantity:1,ex_gst:'100.00',gst:'15.00'},0);assert.match(markup,/name="category_id"/);assert.match(markup,/value="a" selected/);assert.match(markup,/value="b"/);assert.match(markup,/name="kind"/);assert.match(markup,/\$115.00/);assert.match(markup,/name="available_on"/);const css=fs.readFileSync('public/purchase-review.css','utf8');assert.match(css,/\.pr-item\{display:grid/);assert.match(css,/\.pr-mobile-summary\{display:flex/);assert.match(css,/overflow:visible/)});
test('reviewed bills remain in list, collapsed; Stock & Equipment has no purchase review tab',()=>{const {state,cardHtml}=harness();state.reviews.set('b',{revision:1,rows:[{description:'Bucket',kind:'supplies',category_id:'a',quantity:1,ex_gst:20,gst:3}]});const card=cardHtml({id:'b',ex_gst:20,gst_amount:3,total_amount:23});assert.match(card,/Reviewed/);assert.match(card,/data-pr-items hidden/);assert.match(card,/View reviewed items/);const html=fs.readFileSync('public/index.html','utf8');assert.match(html,/data-exp-tab="review"/);assert.doesNotMatch(html,/data-se-tab="review"/);for(const kind of ['stock_sale','supplies','equipment','small_tools'])assert.match(html,new RegExp(`data-se-tab="${kind}"`))});
test('Mercury bill credits reduce ex GST and GST to the saved invoice without a guessed adjustment',()=>{
 const {allocations}=harness();const amounts=[243.83,45,6.5,139.14,4.5,43.2,4];const names=['Anytime','Daily Fixed Charge','2% EASY PAY DISCOUNT','Variable Usage Charge','Dual Fuel Discount','Daily Fixed Charge','2% EASY PAY DISCOUNT'];
 const rows=allocations(names.map((description,i)=>({description,amount:amounts[i],amount_basis:'ex_gst',gst_treatment:'taxable',quantity:1})),{ex_gst:456.17,gst_amount:68.41,total_amount:524.58,category_id:'utilities'});
 assert.equal(JSON.stringify(rows.filter(x=>x.kind==='discount').map(x=>[x.ex_gst,x.gst,x.discount_target_index])),JSON.stringify([['-6.50','-0.98',1],['-4.50','-0.68',3],['-4.00','-0.60',5]]));
 assert.equal(rows.reduce((n,x)=>n+Math.round(Number(x.ex_gst)*100),0),45617);
 assert.equal(rows.reduce((n,x)=>n+Math.round(Number(x.gst)*100),0),6841);
});
test('mixed GST discount remains unresolved unless its printed tax treatment is known',()=>{
 const {allocations}=harness();const rows=allocations([{description:'Taxed',amount:100,amount_basis:'ex_gst',gst_treatment:'taxable'},{description:'Exempt',amount:50,amount_basis:'ex_gst',gst_treatment:'no_gst'},{description:'Invoice discount',amount:-10,amount_basis:'ex_gst',gst_treatment:'unknown'}],{ex_gst:140,gst_amount:13.50,total_amount:153.50});
 assert.equal(rows[2].kind,'discount');assert.equal(rows[2].gst,'');
});
