(()=>{
  const q=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const state={data:null,industries:[]};
  const client=()=>window.SAAS?.client?.();
  async function rpc(name,args={}){const {data,error}=await client().rpc(name,args);if(error)throw error;return data}
  function selected(name){return state.data?.state?.selected_modules?.includes(name)}
  function render(step){
    const d=state.data||{},b=d.business||{},s=d.state||{},g=d.gst||{};step=Number(step||s.current_step||1);q('onboardingProgress').textContent=`${step} of 5`;q('onboardingBar').style.width=`${step*20}%`;
    const body=q('onboardingBody');
    if(step===1)body.innerHTML=`<h1>Let's get your business ready</h1><p>A few quick questions and you'll be ready to go.</p><div class="onboarding-fields"><label>Business name<input id="obName" value="${esc(b.name||'')}"></label><label>What does your business do?<select id="obIndustry"><option value="">Choose one</option>${state.industries.map(x=>`<option value="${esc(x.code)}" ${b.industry===x.code?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label><label>Business type<select id="obType"><option value="sole_trader" ${b.business_type==='sole_trader'?'selected':''}>Sole trader / Self-employed</option><option value="company" ${b.business_type==='company'?'selected':''}>Company</option><option value="partnership" ${b.business_type==='partnership'?'selected':''}>Partnership</option><option value="trust" ${b.business_type==='trust'?'selected':''}>Trust</option><option value="other" ${b.business_type==='other'?'selected':''}>Other</option><option value="unsure" ${b.business_type==='unsure'?'selected':''}>I'm not sure</option></select></label><label>Business email<input id="obEmail" type="email" value="${esc(b.business_email||window.SAAS?.state?.user?.email||'')}"></label></div><button class="primary onboarding-next" data-next="1">Continue</button>`;
    if(step===2){const gst=s.gst_confirmation||'unanswered';body.innerHTML=`<h1>GST</h1><p>Are you registered for GST?</p><div class="choice-grid three"><button class="choice-card ${gst==='yes'?'selected':''}" data-gst="yes"><strong>Yes</strong></button><button class="choice-card ${gst==='no'?'selected':''}" data-gst="no"><strong>No</strong></button><button class="choice-card ${gst==='unsure'?'selected':''}" data-gst="unsure"><strong>I'm not sure</strong></button></div><div id="obGstExtra"></div><div class="onboarding-actions"><button class="secondary" data-back="1">Back</button><button class="primary" data-next="2">Continue</button></div>`;renderGstExtra(gst,g)}
    if(step===3)body.innerHTML=`<h1>What would you like to use Finlo for?</h1><p>Choose what matters now. You can change this later.</p><div class="choice-grid two module-choices">${[['invoice_manager','Invoices & Quotes'],['expenses','Expenses & Receipts'],['bank_reconciliation','Bank Transactions'],['payroll','Payroll']].map(([v,l])=>`<button class="choice-card ${selected(v)?'selected':''}" data-module-choice="${v}"><span class="choice-check">✓</span><strong>${l}</strong></button>`).join('')}</div><div class="onboarding-actions"><button class="secondary" data-back="2">Back</button><button class="primary" data-next="3">Continue</button></div>`;
    if(step===4)body.innerHTML=`<h1>How are you starting?</h1><p>We'll tailor what you see next.</p><div class="choice-grid two"><button class="choice-card ${s.starting_mode==='fresh'?'selected':''}" data-start="fresh"><strong>I'm starting fresh</strong><span>I don't have existing business records to bring across.</span></button><button class="choice-card ${s.starting_mode==='existing'?'selected':''}" data-start="existing"><strong>I already have business records</strong><span>I have records I'd like to bring into Finlo.</span></button></div><div class="onboarding-actions"><button class="secondary" data-back="3">Back</button><button class="primary" data-next="4">Continue</button></div>`;
    if(step===5)body.innerHTML=s.starting_mode==='existing'?`<h1>Bring your records into Finlo</h1><p>Choose what you want to bring across. Finlo keeps each import in the right workflow.</p><div class="onboarding-import-options"><div class="card onboarding-import-card"><strong>Customers &amp; suppliers</strong><span>Upload CSV or Excel. These can be imported after review.</span><button class="primary" data-existing-records>Upload records</button></div><div class="card onboarding-import-card"><strong>Invoices &amp; expenses</strong><span>Upload CSV or Excel for analysis and review. Historical financial records are not committed in V61.71B.</span><button class="secondary" data-existing-records>Review a file</button></div><div class="card onboarding-import-card"><strong>Bank transactions</strong><span>Upload a CSV downloaded from your bank and bring your transactions into Finlo Bank Reconciliation.</span><button class="primary" data-bank-import>Import bank CSV</button></div></div><div class="ready-actions"><button class="secondary" data-finish="dashboard">I'll do this later</button></div><p class="hint">You can come back anytime from Settings → Import & Migration.</p>`:`<div class="ready-mark">✓</div><h1>You're ready to go</h1><p>Finlo has set up your business. You can change your settings anytime.</p><div class="ready-actions"><button class="primary" data-finish="create">Create an invoice</button><button class="secondary" data-finish="expense">Add an expense</button><button class="secondary" data-finish="dashboard">Go to my dashboard</button></div>`;
    bind(step);
  }
  function renderGstExtra(v,g){const el=q('obGstExtra');if(!el)return;if(v==='unsure')el.innerHTML=`<div class="notice soft"><strong>That's okay. You can confirm this later.</strong><div class="inline-actions"><a class="secondary button-link" href="https://www.ird.govt.nz/gst/registering-for-gst" target="_blank" rel="noopener">Check with Inland Revenue</a><span>I'll confirm this later</span></div></div>`;else if(v==='yes')el.innerHTML=`<div class="onboarding-fields gst-fields"><label>GST number<input id="obGstNumber" value="${esc(g.gst_number||'')}"></label><label>How often do you file GST?<select id="obGstFrequency"><option value="">I'm not sure</option><option value="monthly" ${g.filing_frequency==='monthly'?'selected':''}>Every month</option><option value="two_monthly" ${g.filing_frequency==='two_monthly'?'selected':''}>Every 2 months</option><option value="six_monthly" ${g.filing_frequency==='six_monthly'?'selected':''}>Every 6 months</option></select></label><label class="wide">When does GST normally go into your return?<select id="obGstBasis"><option value="">I'm not sure</option><option value="payments" ${g.accounting_basis==='payments'?'selected':''}>When money is actually paid — Payments basis</option><option value="invoice" ${g.accounting_basis==='invoice'?'selected':''}>When invoices are sent or received — Invoice basis</option><option value="hybrid" ${g.accounting_basis==='hybrid'?'selected':''}>Something else — Hybrid</option></select></label></div>`;else el.innerHTML=''}
  async function save(step){
    if(step===1){await rpc('v6171_onboarding_save',{p_step:1,p_payload:{business_name:q('obName').value,industry:q('obIndustry').value,business_type:q('obType').value,business_email:q('obEmail').value}})}
    if(step===2){const gst=document.querySelector('[data-gst].selected')?.dataset?.gst||state.data.state.gst_confirmation||'unanswered';await rpc('v6171_onboarding_save',{p_step:2,p_payload:{gst_confirmation:gst}});if(gst==='yes'){const basis=q('obGstBasis')?.value||'',freq=q('obGstFrequency')?.value||'';if(basis&&freq){await rpc('v6170e_set_gst_settings',{p_registered:true,p_gst_number:q('obGstNumber')?.value||'',p_basis:basis,p_frequency:freq,p_balance_month:Number(state.data.gst?.balance_date_month||3),p_balance_day:Number(state.data.gst?.balance_date_day||31),p_effective_from:new Date().toISOString().slice(0,10)})}}else if(gst==='no'){const g=state.data.gst||{};await rpc('v6170e_set_gst_settings',{p_registered:false,p_gst_number:null,p_basis:g.accounting_basis||'payments',p_frequency:g.filing_frequency||'two_monthly',p_balance_month:Number(g.balance_date_month||3),p_balance_day:Number(g.balance_date_day||31),p_effective_from:new Date().toISOString().slice(0,10)})}}
    if(step===3){await rpc('v6171_onboarding_save',{p_step:3,p_payload:{selected_modules:[...document.querySelectorAll('[data-module-choice].selected')].map(x=>x.dataset.moduleChoice)}})}
    if(step===4){const x=document.querySelector('[data-start].selected')?.dataset?.start;if(!x)throw new Error('Choose how you are starting.');await rpc('v6171_onboarding_save',{p_step:4,p_payload:{starting_mode:x}})}
    state.data=await rpc('v6171_onboarding_get');render(Math.min(step+1,5));
  }
  function bind(step){q('onboardingBody').querySelectorAll('[data-back]').forEach(x=>x.onclick=()=>render(x.dataset.back));q('onboardingBody').querySelectorAll('[data-next]').forEach(x=>x.onclick=async()=>{x.disabled=true;try{await save(Number(x.dataset.next))}catch(e){alert(e.message||'Could not save this step.');x.disabled=false}});q('onboardingBody').querySelectorAll('[data-gst]').forEach(x=>x.onclick=()=>{document.querySelectorAll('[data-gst]').forEach(y=>y.classList.remove('selected'));x.classList.add('selected');state.data.state.gst_confirmation=x.dataset.gst;renderGstExtra(x.dataset.gst,state.data.gst||{})});q('onboardingBody').querySelectorAll('[data-module-choice]').forEach(x=>x.onclick=()=>x.classList.toggle('selected'));q('onboardingBody').querySelectorAll('[data-start]').forEach(x=>x.onclick=()=>{document.querySelectorAll('[data-start]').forEach(y=>y.classList.remove('selected'));x.classList.add('selected')});q('onboardingBody').querySelectorAll('[data-finish]').forEach(x=>x.onclick=async()=>{await rpc('v6171_onboarding_save',{p_step:5,p_payload:{}});q('onboardingShell').hidden=true;window.FinloHelper?.setContext?.({module:'dashboard',step:'',topic:''});showGettingStarted();if(x.dataset.finish==='expense')window.switchView?.('expenses');else window.switchView?.('create')});q('onboardingBody').querySelectorAll('[data-existing-records]').forEach(x=>x.addEventListener('click',()=>window.ImportMigration?.open?.({onboarding:true})));q('onboardingBody').querySelector('[data-bank-import]')?.addEventListener('click',()=>window.ImportMigration?.launchBank?.({onboarding:true}));window.FinloHelper?.setContext?.({module:'onboarding',step:String(step),country:'NZ',topic:step===2?'GST setup':'Onboarding'})}
  async function showGettingStarted(){const s=state.data?.state;if(!s||s.getting_started_dismissed)return;const card=q('gettingStartedCard');if(!card)return;const bid=window.SAAS.currentBusinessId(),c=client();const [cu,inv,exp,emp,bank]=await Promise.all([c.from('customers').select('id',{count:'exact',head:true}).eq('business_id',bid),c.from('invoices').select('id',{count:'exact',head:true}).eq('business_id',bid),c.from('expenses').select('id',{count:'exact',head:true}).eq('business_id',bid),c.from('payroll_employees').select('id',{count:'exact',head:true}).eq('business_id',bid),c.from('bank_transactions').select('id',{count:'exact',head:true}).eq('business_id',bid)]);const items=[['Business set up',true]];if(s.gst_confirmation==='unsure'||(s.gst_confirmation==='yes'&&!state.data?.gst?.effective_from))items.push(['Confirm your GST settings',false]);items.push(['Add your first customer',(cu.count||0)>0],['Create your first invoice',(inv.count||0)>0],['Add your first expense',(exp.count||0)>0]);if(s.selected_modules?.includes('payroll'))items.push(['Add your first employee',(emp.count||0)>0]);if(s.selected_modules?.includes('bank_reconciliation'))items.push(['Add your first bank transactions',(bank.count||0)>0]);q('gettingStartedItems').innerHTML=items.map(([l,done])=>`<div class="getting-item ${done?'done':''}"><span>${done?'✓':'○'}</span>${esc(l)}</div>`).join('');card.hidden=false}
  async function init(){if(!client()||!window.SAAS?.currentBusinessId?.())return;const [data,ind]=await Promise.all([rpc('v6171_onboarding_get'),client().from('platform_industries').select('code,name').eq('is_active',true).order('sort_order')]);state.data=data;state.industries=ind.data||[];const s=data?.state,country=String(data?.business?.country||'NZ').toUpperCase();if(s&&country==='NZ'&&s.status!=='completed'&&s.status!=='dismissed'){q('onboardingShell').hidden=false;render(s.current_step||1)}else if(s?.status==='completed')showGettingStarted();q('dismissGettingStarted')?.addEventListener('click',async()=>{await rpc('v6171_onboarding_dismiss_getting_started');q('gettingStartedCard').hidden=true})}
  window.FinloOnboarding={init,reload:init};
})();
