(function(g){'use strict';
const N=v=>Number(v||0), trunc2=v=>Math.floor((N(v)+1e-9)*100)/100, whole=v=>Math.floor(Math.max(0,N(v))+1e-9);
const PPY={weekly:52,fortnightly:26,'four-weekly':13,four_weekly:13,monthly:12};
const SLT={weekly:464,fortnightly:928,'four-weekly':1856,four_weekly:1856,monthly:2010.66};
const SECONDARY={SB:.1225,S:.1925,SH:.3175,ST:.3475,SA:.4075,CAE:.1925,EDW:.1925,NSW:.1225,ND:.4675};
const LOW={SB:0,S:15601,SH:53501,ST:78101,SA:180001};
function need(code,message){return{status:'needs_confirmation',reasons:[{code,message}]}}
function norm(c){return String(c||'').toUpperCase().replace(/\s+/g,' ').trim()}
function annualTax(a){a=N(a);if(a<=15600)return a*.105;if(a<=53500)return a*.175-1092;if(a<=78100)return a*.30-7779.5;if(a<=180000)return a*.33-10122.5;return a*.39-20922.5}
function ietc(a){if(a<24000||a>=70000)return 0;if(a<=66000)return 520;return Math.max(0,520-(a-66000)*.13)}
function ordinary(i){
 if(norm(i.countryCode)!=='NZ')return{status:'not_applicable'}; const f=String(i.frequency||'').toLowerCase(),ppy=PPY[f];if(!ppy)return need('unsupported_frequency','Weekly, fortnightly, four-weekly or monthly frequency is required.');
 const code=norm(i.taxCode),pay=whole(i.taxableEarnings); if(!code)return need('tax_code_required','A current tax code is required.');
 let paye=0,sl=0;
 if(code==='STC'||code==='WT'){if(!Number.isFinite(Number(i.tailoredTaxRate)))return need('tailored_rate_required','Current IRD tailored/schedular rate evidence is required.');paye=trunc2(pay*N(i.tailoredTaxRate));if(code==='WT')return{status:'calculated',paye,studentLoan:0,acc:0,kiwisaverAllowed:false,rule:'IRD-2026-27'};}
 else if(['M','M SL','ME','ME SL'].includes(code)){const annual=pay*ppy,acc=annual>=156641?2741.22:annual*.0175,total=annualTax(annual)+acc-(code.startsWith('ME')?ietc(annual):0),weekly=trunc2(total/52);paye=trunc2(weekly*52/ppy);}
 else {const base=code.replace(/ SL$/,'');if(!Object.prototype.hasOwnProperty.call(SECONDARY,base))return need('unsupported_tax_code','Tax code is not supported without explicit statutory evidence.');paye=trunc2(pay*SECONDARY[base]);}
 const hasSL=code.endsWith(' SL')||i.studentLoan===true;
 if(hasSL){if(i.studentLoanSpecialRate!=null){const r=N(i.studentLoanSpecialRate);if(r<0||r>.12)return need('student_loan_special_rate_invalid','IRD student-loan special rate must be between 0% and 12%.');const useThreshold=i.studentLoanThresholdApplies!==false;sl=trunc2(Math.max(0,pay-(useThreshold?SLT[f]:0))*r);}else if(['M SL','ME SL'].includes(code)){sl=trunc2(Math.max(0,pay-SLT[f])*.12);}else if(code.endsWith(' SL'))sl=trunc2(pay*.12);else return need('student_loan_evidence_required','Student-loan tax code or current IRD special-rate evidence is required.');}
 return{status:'calculated',paye,studentLoan:sl,taxableWholeDollars:pay,rule:'IRD-2026-27'};
}
function kiwi(i){if(norm(i.countryCode)!=='NZ')return{status:'not_applicable'};const status=String(i.status||'not_enrolled');if(status==='not_enrolled')return{status:'calculated',employee:0,employerGross:0,esct:0,employerNet:0};if(status==='suspended')return{status:'calculated',employee:0,employerGross:0,esct:0,employerNet:0};if(status!=='enrolled')return need('kiwisaver_status_unknown','KiwiSaver status is not supported.');if(norm(i.taxCode)==='NSW'||norm(i.taxCode)==='WT')return need('kiwisaver_not_permitted','KiwiSaver cannot be calculated for this tax code.');
 let er=N(i.employeeRate),mr=N(i.employerRate);const valid=[.035,.04,.06,.08,.10];if(er===.03){if(i.temporaryRateReduction!==true)return need('kiwisaver_reduction_evidence_required','A current IRD temporary rate-reduction notice is required for 3%.');}else if(!valid.includes(er))return need('kiwisaver_employee_rate_invalid','Current employee KiwiSaver rate must be 3.5%, 4%, 6%, 8%, 10%, or evidenced temporary 3%.');if(mr===.03){if(i.temporaryRateReduction!==true)return need('kiwisaver_employer_reduction_evidence_required','3% employer contribution requires an applicable temporary rate reduction.');}else if(mr<.035)return need('kiwisaver_employer_rate_invalid','Employer contribution is below the statutory minimum.');
 const gross=N(i.kiwisaverGross),employee=trunc2(gross*er),employerGross=trunc2(gross*mr);if(employerGross<=0)return{status:'calculated',employee,employerGross:0,esct:0,employerNet:0};if(i.esctThresholdAmount==null||i.esctThresholdAmount===''||!Number.isFinite(Number(i.esctThresholdAmount)))return need('esct_threshold_evidence_required','ESCT threshold amount evidence is required.');const a=N(i.esctThresholdAmount),rate=a<=18720?.105:a<=64200?.175:a<=93720?.30:a<=216000?.33:.39;const esct=trunc2(whole(employerGross)*rate),employerNet=trunc2(employerGross-esct);return{status:'calculated',employee,employerGross,esct,employerNet,esctRate:rate};
}
function extra(i){if(norm(i.countryCode)!=='NZ')return{status:'not_applicable'};const amount=N(i.amount);if(amount<0)return need('extra_pay_invalid','Extra pay cannot be negative.');const code=norm(i.taxCode);if(['NSW','ND'].includes(code)){const rate=code==='NSW'?.1225:.4675;return{status:'calculated',paye:trunc2(whole(amount)*rate),studentLoan:0,rate};}if(code==='STC'){if(!Number.isFinite(Number(i.tailoredTaxRate)))return need('tailored_rate_required','Current IRD tailored tax certificate evidence is required.');return{status:'calculated',paye:trunc2(amount*N(i.tailoredTaxRate)),studentLoan:0,rate:N(i.tailoredTaxRate)};}
 const prior=Array.isArray(i.priorPays)?i.priorPays.filter(x=>N(x.amount)>0):[];if(!prior.length)return need('prior_pay_evidence_required','Required prior PAYE-income evidence is missing.');let annualised;if(i.termination){if(prior.length<2)return need('two_prior_pays_required','Two prior paid pay periods are required for end-of-employment extra pay.');const p=prior.slice(0,2),mult={weekly:52,fortnightly:26,'four-weekly':13,four_weekly:13,monthly:12};annualised=p.reduce((s,x)=>s+N(x.amount)*(mult[String(x.frequency||'').toLowerCase()]||0),0)/2;}else{const fourWeek=N(i.priorFourWeekIncome);if(!Number.isFinite(Number(i.priorFourWeekIncome)))return need('four_week_income_required','Four-week PAYE-income evidence is required for extra pay.');annualised=fourWeek*(String(i.frequency).toLowerCase()==='monthly'?12:13);}
 const base=code.replace(/ SL$/,''),low=LOW[base]||0,grossed=whole(annualised+low+amount),taxRate=grossed<=15600?.105:grossed<=53500?.175:grossed<=78100?.30:grossed<=180000?.33:.39;let acc=0;if(!['redundancy','retiring_allowance','ess'].includes(String(i.kind||''))){const pre=annualised+low;acc=Math.max(0,Math.min(amount,156641-pre))*.0175;}const paye=trunc2(amount*taxRate+acc);return{status:'calculated',paye,studentLoan:0,taxRate,acc:trunc2(acc),annualised,grossed};
}
function calculate(i){const o=ordinary(i);if(o.status!=='calculated')return o;const k=kiwi(i);if(k.status!=='calculated')return k;return{status:'calculated',paye:o.paye,studentLoan:o.studentLoan,kiwisaverEmployee:k.employee,kiwisaverEmployerGross:k.employerGross,esct:k.esct,kiwisaverEmployerNet:k.employerNet,ordinary:o,kiwisaver:k,engine:'FinloNZTax/P7'};}
g.FinloNZTax={ordinary,kiwi,extra,calculate,version:'V61.73-P7',_test:{trunc2,whole,annualTax,ietc}};
})(typeof window!=='undefined'?window:globalThis);
