-- V61.70F-P2.1 — AU BAS Purchase Evidence Ex-GST Display Fix
-- Projection-only correction. No source transaction, recognition, lifecycle or tax-setting changes.

create or replace function public.v6170f_bas_calculate(p_from date,p_to date) returns jsonb language plpgsql stable security definer set search_path=public as $$
declare bid uuid:=current_business_id(); cfg jsonb; basis text; registered boolean; g1 numeric:=0; one_a numeric:=0; one_b numeric:=0; sales_items jsonb:='[]'; purchase_items jsonb:='[]'; review jsonb:='[]'; conflict_items jsonb:='[]'; missing_sales int:=0; missing_purchases int:=0; legacy_count int:=0; due date;
begin
 if bid is null or not v6147_can_read_area(bid,'financials') then raise exception 'Financial access denied' using errcode='42501';end if;
 if v6170f_business_country()<>'AU' then raise exception 'BAS calculation requires an Australian business' using errcode='22023';end if;
 if p_from is null or p_to is null or p_from>p_to then raise exception 'Invalid BAS period';end if;
 cfg:=v6170f_bas_settings(p_to); basis:=cfg->>'accounting_basis'; registered:=coalesce((cfg->>'gst_registered')::boolean,false); due:=v6170f_bas_due_date(p_to,cfg->>'filing_frequency');
 if not registered then review:=review||jsonb_build_array(jsonb_build_object('severity','blocking','code','not_registered','message','Business is not GST registered for this BAS period.'));end if;
 if basis='non_cash' then
   select coalesce(sum(case when i.au_tax_classification in('gst_taxable','gst_free','input_taxed') then i.total else 0 end),0),coalesce(sum(case when i.au_tax_classification='gst_taxable' then i.gst else 0 end),0),coalesce(jsonb_agg(jsonb_build_object('source_type','invoice','source_id',i.id,'date',i.invoice_date,'reference',i.invoice_number,'party',c.name,'party_id',i.customer_id,'classification',i.au_tax_classification,'g1',case when i.au_tax_classification in('gst_taxable','gst_free','input_taxed') then i.total else 0 end,'gst',case when i.au_tax_classification='gst_taxable' then i.gst else 0 end,'total',i.total) order by i.invoice_date,i.invoice_number),'[]') into g1,one_a,sales_items from invoices i left join customers c on c.id=i.customer_id and c.business_id=i.business_id where i.business_id=bid and i.invoice_date between p_from and p_to and coalesce(i.lifecycle_state,'issued') not in('draft','voided');
   select count(*) into missing_sales from invoices i where i.business_id=bid and i.invoice_date between p_from and p_to and coalesce(i.lifecycle_state,'issued') not in('draft','voided') and i.au_tax_classification is null;
   select coalesce(sum(case when e.au_tax_classification='gst_taxable' then e.gst_amount*coalesce(e.business_use_percent,100)/100 else 0 end),0),coalesce(jsonb_agg(jsonb_build_object('source_type','expense','source_id',e.id,'date',e.invoice_date,'reference',e.expense_number,'party',e.supplier_name,'party_id',e.supplier_id,'classification',e.au_tax_classification,'ex_gst',case when e.au_tax_classification is not null then e.business_ex_gst else null end,'gst',case when e.au_tax_classification='gst_taxable' then e.gst_amount*coalesce(e.business_use_percent,100)/100 else 0 end,'total',e.total_amount*coalesce(e.business_use_percent,100)/100) order by e.invoice_date,e.expense_number),'[]') into one_b,purchase_items from expenses e where e.business_id=bid and e.invoice_date between p_from and p_to and coalesce(e.lifecycle_state,'recorded')='recorded';
   select count(*) into missing_purchases from expenses e where e.business_id=bid and e.invoice_date between p_from and p_to and coalesce(e.lifecycle_state,'recorded')='recorded' and e.au_tax_classification is null;
 else
   select coalesce(sum(case when i.au_tax_classification in('gst_taxable','gst_free','input_taxed') then cp.amount else 0 end),0),coalesce(sum(case when i.au_tax_classification='gst_taxable' then coalesce(i.gst,0)*(cp.amount/nullif(i.total,0)) else 0 end),0),coalesce(jsonb_agg(jsonb_build_object('source_type','customer_payment','source_id',cp.id,'source_document_id',i.id,'date',cp.payment_date,'reference',i.invoice_number,'party',c.name,'party_id',i.customer_id,'classification',i.au_tax_classification,'g1',case when i.au_tax_classification in('gst_taxable','gst_free','input_taxed') then cp.amount else 0 end,'gst',case when i.au_tax_classification='gst_taxable' then coalesce(i.gst,0)*(cp.amount/nullif(i.total,0)) else 0 end,'total',cp.amount) order by cp.payment_date,i.invoice_number),'[]') into g1,one_a,sales_items from customer_payments cp join invoices i on i.id=cp.invoice_id and i.business_id=cp.business_id left join customers c on c.id=i.customer_id and c.business_id=i.business_id where cp.business_id=bid and cp.payment_date between p_from and p_to and coalesce(cp.is_legacy_estimate,false)=false and i.total>0 and coalesce(i.lifecycle_state,'issued') not in('draft','voided');
   select count(*) into legacy_count from customer_payments cp where cp.business_id=bid and cp.payment_date between p_from and p_to and coalesce(cp.is_legacy_estimate,false)=true;
   select count(*) into missing_sales from customer_payments cp join invoices i on i.id=cp.invoice_id and i.business_id=cp.business_id where cp.business_id=bid and cp.payment_date between p_from and p_to and coalesce(cp.is_legacy_estimate,false)=false and i.au_tax_classification is null;
   select coalesce(sum(case when e.au_tax_classification='gst_taxable' then e.gst_amount*(ep.amount/nullif(e.total_amount,0))*coalesce(e.business_use_percent,100)/100 else 0 end),0),coalesce(jsonb_agg(jsonb_build_object('source_type','expense_payment','source_id',ep.id,'source_document_id',e.id,'date',ep.payment_date,'reference',e.expense_number,'party',e.supplier_name,'party_id',e.supplier_id,'classification',e.au_tax_classification,'ex_gst',case when e.au_tax_classification is not null then e.business_ex_gst*(ep.amount/nullif(e.total_amount,0)) else null end,'gst',case when e.au_tax_classification='gst_taxable' then e.gst_amount*(ep.amount/nullif(e.total_amount,0))*coalesce(e.business_use_percent,100)/100 else 0 end,'total',ep.amount*coalesce(e.business_use_percent,100)/100) order by ep.payment_date,e.expense_number),'[]') into one_b,purchase_items from expense_payments ep join expenses e on e.id=ep.expense_id and e.business_id=ep.business_id where ep.business_id=bid and ep.payment_date between p_from and p_to and e.total_amount>0 and coalesce(e.lifecycle_state,'recorded')='recorded';
   select count(*) into missing_purchases from expense_payments ep join expenses e on e.id=ep.expense_id and e.business_id=ep.business_id where ep.business_id=bid and ep.payment_date between p_from and p_to and e.au_tax_classification is null;
 end if;
 -- Controlled correction evidence. The correction source carries or inherits the original AU classification. Refund settlement does not create GST again.
 select g1-coalesce(sum(case when coalesce(cn.au_tax_classification,i.au_tax_classification) in('gst_taxable','gst_free','input_taxed') then cn.total_amount else 0 end),0),one_a-coalesce(sum(case when coalesce(cn.au_tax_classification,i.au_tax_classification)='gst_taxable' then cn.gst_amount else 0 end),0) into g1,one_a from customer_credit_notes cn join invoices i on i.id=cn.original_invoice_id and i.business_id=cn.business_id where cn.business_id=bid and cn.lifecycle_state='issued' and cn.credit_date between p_from and p_to;
 select sales_items||coalesce(jsonb_agg(jsonb_build_object('source_type','customer_credit_note','source_id',cn.id,'source_document_id',i.id,'date',cn.credit_date,'reference',cn.credit_note_number,'original_reference',i.invoice_number,'party',c.name,'party_id',cn.customer_id,'classification',coalesce(cn.au_tax_classification,i.au_tax_classification),'g1',case when coalesce(cn.au_tax_classification,i.au_tax_classification) in('gst_taxable','gst_free','input_taxed') then -cn.total_amount else 0 end,'gst',case when coalesce(cn.au_tax_classification,i.au_tax_classification)='gst_taxable' then -cn.gst_amount else 0 end,'total',-cn.total_amount) order by cn.credit_date,cn.credit_note_number),'[]'::jsonb) into sales_items from customer_credit_notes cn join invoices i on i.id=cn.original_invoice_id and i.business_id=cn.business_id left join customers c on c.id=cn.customer_id and c.business_id=cn.business_id where cn.business_id=bid and cn.lifecycle_state='issued' and cn.credit_date between p_from and p_to;
 select one_b-coalesce(sum(case when coalesce(sc.au_tax_classification,e.au_tax_classification)='gst_taxable' then sc.gst_amount*coalesce(e.business_use_percent,100)/100 else 0 end),0) into one_b from supplier_credits sc join expenses e on e.id=sc.original_expense_id and e.business_id=sc.business_id where sc.business_id=bid and sc.lifecycle_state='recorded' and sc.credit_date between p_from and p_to;
 select purchase_items||coalesce(jsonb_agg(jsonb_build_object('source_type','supplier_credit','source_id',sc.id,'source_document_id',e.id,'date',sc.credit_date,'reference',sc.credit_note_number,'original_reference',e.expense_number,'party',e.supplier_name,'party_id',sc.supplier_id,'classification',coalesce(sc.au_tax_classification,e.au_tax_classification),'ex_gst',case when coalesce(sc.au_tax_classification,e.au_tax_classification) is not null then -(sc.ex_gst*coalesce(e.business_use_percent,100)/100) else null end,'gst',case when coalesce(sc.au_tax_classification,e.au_tax_classification)='gst_taxable' then -(sc.gst_amount*coalesce(e.business_use_percent,100)/100) else 0 end,'total',-(sc.total_amount*coalesce(e.business_use_percent,100)/100)) order by sc.credit_date,sc.credit_note_number),'[]'::jsonb) into purchase_items from supplier_credits sc join expenses e on e.id=sc.original_expense_id and e.business_id=sc.business_id where sc.business_id=bid and sc.lifecycle_state='recorded' and sc.credit_date between p_from and p_to;
 if missing_sales>0 then review:=review||jsonb_build_array(jsonb_build_object('severity','blocking','code','missing_sales_tax_classification','count',missing_sales,'message','Australian sales evidence is missing a controlled GST classification. Review before finalising BAS.'));end if;
 if missing_purchases>0 then review:=review||jsonb_build_array(jsonb_build_object('severity','blocking','code','missing_purchase_tax_classification','count',missing_purchases,'message','Australian purchase evidence is missing a controlled GST classification. Review before finalising BAS.'));end if;
 if legacy_count>0 then review:=review||jsonb_build_array(jsonb_build_object('severity','blocking','code','legacy_estimated_payments','count',legacy_count,'message','Legacy estimated payment dates cannot be used as exact cash-basis BAS evidence.'));end if;
 select coalesce(jsonb_agg(jsonb_build_object('id',r.id,'period_start',r.period_start,'period_end',r.period_end,'status',r.status) order by r.period_start),'[]') into conflict_items from bas_returns r where r.business_id=bid and r.status='finalised' and daterange(r.period_start,r.period_end,'[]')&&daterange(p_from,p_to,'[]') and not(r.period_start=p_from and r.period_end=p_to);
 if jsonb_array_length(conflict_items)>0 then review:=review||jsonb_build_array(jsonb_build_object('severity','blocking','code','finalised_period_overlap','message','BAS period conflict — an existing finalised BAS overlaps this period.','returns',conflict_items));end if;
 return jsonb_build_object('jurisdiction','AU','period_start',p_from,'period_end',p_to,'due_date',due,'settings',cfg,'basis',basis,'filing_frequency',cfg->>'filing_frequency','g1_total_sales',round(g1,2),'gst_on_sales',round(one_a,2),'gst_on_purchases',round(one_b,2),'gst_net',round(one_a-one_b,2),'sales_items',sales_items,'purchase_items',purchase_items,'review_items',review,'other_obligations',jsonb_build_object('payg_withholding',jsonb_build_object('status','unavailable','message','Requires authoritative finalised Australian payroll evidence.'),'payg_instalment',jsonb_build_object('status','unavailable','message','Not configured in this BAS foundation.')),'calculation_version','v61.70f','g1_reporting_basis','gst_inclusive');
end$$;

