-- V61.70E-P3: GST evidence integrity + overlapping-finalised-return protection.
-- Forward-only. No production data mutation.

create or replace function public.v6170e_gst_calculate(p_from date,p_to date) returns jsonb language plpgsql stable security definer set search_path=public as $$
declare bid uuid:=current_business_id(); cfg jsonb; basis text; registered boolean; sales_ex numeric:=0; sales_gst numeric:=0; purch_ex numeric:=0; purch_gst numeric:=0; debit_adj numeric:=0; credit_adj numeric:=0; legacy_count int:=0; missing_count int:=0; sales_items jsonb:='[]'; purchase_items jsonb:='[]'; adjustment_items jsonb:='[]'; review jsonb:='[]'; conflict_items jsonb:='[]';
begin
 if bid is null or not v6147_can_read_area(bid,'financials') then raise exception 'Financial access denied' using errcode='42501';end if;
 if p_from is null or p_to is null or p_from>p_to then raise exception 'Invalid GST period';end if;
 cfg:=v6170e_gst_settings(p_to); basis:=cfg->>'accounting_basis'; registered:=coalesce((cfg->>'gst_registered')::boolean,false);
 if not registered then return jsonb_build_object('period_start',p_from,'period_end',p_to,'settings',cfg,'sales_ex_gst',0,'gst_collected',0,'purchases_ex_gst',0,'gst_paid',0,'debit_adjustments',0,'credit_adjustments',0,'gst_net',0,'sales_items','[]'::jsonb,'purchase_items','[]'::jsonb,'adjustment_items','[]'::jsonb,'review_items',jsonb_build_array(jsonb_build_object('severity','blocking','code','not_registered','message','Business is not GST registered for this period.')));end if;
 if basis in('invoice','hybrid') then
  select coalesce(sum(greatest(i.total-i.gst,0)),0),coalesce(sum(i.gst),0),coalesce(jsonb_agg(jsonb_build_object('source_type','invoice','source_id',i.id,'date',i.invoice_date,'reference',i.invoice_number,'party',c.name,'party_id',i.customer_id,'ex_gst',greatest(i.total-i.gst,0),'gst',i.gst,'total',i.total) order by i.invoice_date,i.invoice_number),'[]') into sales_ex,sales_gst,sales_items from invoices i left join customers c on c.id=i.customer_id and c.business_id=i.business_id where i.business_id=bid and i.invoice_date between p_from and p_to and coalesce(i.lifecycle_state,'issued') not in('draft','voided');
 else
  select coalesce(sum(greatest(cp.amount-coalesce(i.gst,0)*(cp.amount/nullif(i.total,0)),0)),0),coalesce(sum(coalesce(i.gst,0)*(cp.amount/nullif(i.total,0))),0),coalesce(jsonb_agg(jsonb_build_object('source_type','customer_payment','source_id',cp.id,'date',cp.payment_date,'reference',i.invoice_number,'party',c.name,'party_id',i.customer_id,'ex_gst',greatest(cp.amount-coalesce(i.gst,0)*(cp.amount/nullif(i.total,0)),0),'gst',coalesce(i.gst,0)*(cp.amount/nullif(i.total,0)),'total',cp.amount) order by cp.payment_date),'[]') into sales_ex,sales_gst,sales_items from customer_payments cp join invoices i on i.id=cp.invoice_id and i.business_id=cp.business_id left join customers c on c.id=i.customer_id and c.business_id=i.business_id where cp.business_id=bid and cp.payment_date between p_from and p_to and coalesce(cp.is_legacy_estimate,false)=false and i.total>0;
  select count(*) into legacy_count from customer_payments cp where cp.business_id=bid and cp.payment_date between p_from and p_to and coalesce(cp.is_legacy_estimate,false)=true;
  if legacy_count>0 then review:=review||jsonb_build_array(jsonb_build_object('severity','blocking','code','legacy_estimated_payments','count',legacy_count,'message','Legacy estimated customer payment dates cannot be used as precise payments-basis GST evidence. Review required.'));end if;
 end if;
 if basis='invoice' then
  select coalesce(sum(e.ex_gst*coalesce(e.business_use_percent,100)/100),0),coalesce(sum(e.gst_amount*coalesce(e.business_use_percent,100)/100),0),coalesce(jsonb_agg(jsonb_build_object('source_type','expense','source_id',e.id,'date',e.invoice_date,'reference',e.expense_number,'party',e.supplier_name,'party_id',e.supplier_id,'ex_gst',e.ex_gst*coalesce(e.business_use_percent,100)/100,'gst',e.gst_amount*coalesce(e.business_use_percent,100)/100,'total',e.total_amount*coalesce(e.business_use_percent,100)/100,'business_use_percent',coalesce(e.business_use_percent,100)) order by e.invoice_date,e.expense_number),'[]') into purch_ex,purch_gst,purchase_items from expenses e left join suppliers s on s.id=e.supplier_id and s.business_id=e.business_id where e.business_id=bid and e.invoice_date between p_from and p_to and coalesce(e.lifecycle_state,'recorded')='recorded';
 else
  select coalesce(sum(greatest(ep.amount-(e.gst_amount*(ep.amount/nullif(e.total_amount,0))),0)*coalesce(e.business_use_percent,100)/100),0),coalesce(sum(e.gst_amount*(ep.amount/nullif(e.total_amount,0))*coalesce(e.business_use_percent,100)/100),0),coalesce(jsonb_agg(jsonb_build_object('source_type','expense_payment','source_id',ep.id,'date',ep.payment_date,'reference',e.expense_number,'party',e.supplier_name,'party_id',e.supplier_id,'ex_gst',greatest(ep.amount-(e.gst_amount*(ep.amount/nullif(e.total_amount,0))),0)*coalesce(e.business_use_percent,100)/100,'gst',e.gst_amount*(ep.amount/nullif(e.total_amount,0))*coalesce(e.business_use_percent,100)/100,'total',ep.amount*coalesce(e.business_use_percent,100)/100,'business_use_percent',coalesce(e.business_use_percent,100)) order by ep.payment_date),'[]') into purch_ex,purch_gst,purchase_items from expense_payments ep join expenses e on e.id=ep.expense_id and e.business_id=ep.business_id left join suppliers s on s.id=e.supplier_id and s.business_id=e.business_id where ep.business_id=bid and ep.payment_date between p_from and p_to and e.total_amount>0 and coalesce(e.lifecycle_state,'recorded')='recorded';
 end if;
 -- Supply corrections are both applied to headline totals and emitted as signed evidence rows.
 select sales_ex-coalesce(sum(c.ex_gst),0),sales_gst-coalesce(sum(c.gst_amount),0) into sales_ex,sales_gst from customer_credit_notes c where c.business_id=bid and c.lifecycle_state='issued' and c.credit_date between p_from and p_to;
 select sales_items || coalesce(jsonb_agg(jsonb_build_object('source_type','customer_credit_note','source_id',c.id,'date',c.credit_date,'reference',c.credit_note_number,'party',cu.name,'party_id',c.customer_id,'ex_gst',-c.ex_gst,'gst',-c.gst_amount,'total',-c.total_amount,'original_reference',i.invoice_number) order by c.credit_date,c.credit_note_number),'[]'::jsonb) into sales_items from customer_credit_notes c left join customers cu on cu.id=c.customer_id and cu.business_id=c.business_id left join invoices i on i.id=c.original_invoice_id and i.business_id=c.business_id where c.business_id=bid and c.lifecycle_state='issued' and c.credit_date between p_from and p_to;
 select purch_ex-coalesce(sum(c.ex_gst*coalesce(e.business_use_percent,100)/100),0),purch_gst-coalesce(sum(c.gst_amount*coalesce(e.business_use_percent,100)/100),0) into purch_ex,purch_gst from supplier_credits c join expenses e on e.id=c.original_expense_id and e.business_id=c.business_id where c.business_id=bid and c.lifecycle_state='recorded' and c.credit_date between p_from and p_to;
 select purchase_items || coalesce(jsonb_agg(jsonb_build_object('source_type','supplier_credit','source_id',c.id,'date',c.credit_date,'reference',c.credit_note_number,'party',e.supplier_name,'party_id',c.supplier_id,'ex_gst',-(c.ex_gst*coalesce(e.business_use_percent,100)/100),'gst',-(c.gst_amount*coalesce(e.business_use_percent,100)/100),'total',-(c.total_amount*coalesce(e.business_use_percent,100)/100),'business_use_percent',coalesce(e.business_use_percent,100),'original_reference',e.expense_number) order by c.credit_date,c.credit_note_number),'[]'::jsonb) into purchase_items from supplier_credits c join expenses e on e.id=c.original_expense_id and e.business_id=c.business_id left join suppliers s on s.id=c.supplier_id and s.business_id=c.business_id where c.business_id=bid and c.lifecycle_state='recorded' and c.credit_date between p_from and p_to;
 select coalesce(sum(case when direction='debit' then gst_amount else 0 end),0),coalesce(sum(case when direction='credit' then gst_amount else 0 end),0),coalesce(jsonb_agg(jsonb_build_object('id',id,'date',adjustment_date,'type',adjustment_type,'direction',direction,'gst_amount',gst_amount,'reason',reason,'reference',reference) order by adjustment_date),'[]') into debit_adj,credit_adj,adjustment_items from gst_adjustments where business_id=bid and status='active' and adjustment_date between p_from and p_to;
 select count(*) into missing_count from expenses e where e.business_id=bid and e.invoice_date between p_from and p_to and coalesce(e.lifecycle_state,'recorded')='recorded' and e.total_amount>0 and e.gst_amount is null;
 if missing_count>0 then review:=review||jsonb_build_array(jsonb_build_object('severity','blocking','code','missing_gst','count',missing_count,'message','Recorded expenses are missing GST information.'));end if;
 select coalesce(jsonb_agg(jsonb_build_object('id',r.id,'period_start',r.period_start,'period_end',r.period_end,'status',r.status,'calculation_version',r.calculation_version) order by r.period_start),'[]') into conflict_items from gst_returns r where r.business_id=bid and r.status='finalised' and daterange(r.period_start,r.period_end,'[]') && daterange(p_from,p_to,'[]') and not(r.period_start=p_from and r.period_end=p_to);
 if jsonb_array_length(conflict_items)>0 then review:=review||jsonb_build_array(jsonb_build_object('severity','blocking','code','finalised_period_overlap','message','GST period conflict — an existing finalised return overlaps this period.','returns',conflict_items));end if;
 return jsonb_build_object('period_start',p_from,'period_end',p_to,'settings',cfg,'basis',basis,'sales_ex_gst',round(sales_ex,2),'gst_collected',round(sales_gst,2),'purchases_ex_gst',round(purch_ex,2),'gst_paid',round(purch_gst,2),'debit_adjustments',round(debit_adj,2),'credit_adjustments',round(credit_adj,2),'gst_net',round(sales_gst+debit_adj-purch_gst-credit_adj,2),'sales_items',sales_items,'purchase_items',purchase_items,'adjustment_items',adjustment_items,'review_items',review,'calculation_version','v61.70e-p3');
end$$;

create or replace function public.v6170e_save_gst_return(p_from date,p_to date,p_status text default 'draft') returns gst_returns language plpgsql security definer set search_path=public as $$
declare bid uuid:=current_business_id(); calc jsonb; r gst_returns; blockers int; cfg jsonb; v_existing boolean:=false; v_conflict gst_returns;
begin
 if bid is null or not v6147_can_write_area(bid,'financials') then raise exception 'GST return access denied' using errcode='42501';end if;
 if p_status not in('draft','reviewed','finalised') then raise exception 'Invalid GST return status';end if;
 select * into r from gst_returns where business_id=bid and period_start=p_from and period_end=p_to for update; v_existing:=found;
 if v_existing and r.status='finalised' then raise exception 'This GST return is finalised and locked';end if;
 -- Finalisation is fail-closed for same-business overlapping finalised returns. Draft/Reviewed remain reviewable.
 if p_status='finalised' then
  select * into v_conflict from gst_returns x where x.business_id=bid and x.status='finalised' and daterange(x.period_start,x.period_end,'[]') && daterange(p_from,p_to,'[]') and (not v_existing or x.id<>r.id) order by x.period_start limit 1 for update;
  if found then raise exception 'GST period conflict: existing finalised return % to % overlaps this period',v_conflict.period_start,v_conflict.period_end using errcode='23514';end if;
 end if;
 calc:=v6170e_gst_calculate(p_from,p_to); cfg:=calc->'settings'; select count(*) into blockers from jsonb_array_elements(calc->'review_items') x where x->>'severity'='blocking';
 if p_status='finalised' and blockers>0 then raise exception 'GST return has blocking review items and cannot be finalised';end if;
 if v_existing then
  update gst_returns set status=p_status,gst_rate=15,taxable_sales_ex_gst=(calc->>'sales_ex_gst')::numeric,gst_collected=(calc->>'gst_collected')::numeric,taxable_purchases_ex_gst=(calc->>'purchases_ex_gst')::numeric,gst_paid=(calc->>'gst_paid')::numeric,debit_adjustments=(calc->>'debit_adjustments')::numeric,credit_adjustments=(calc->>'credit_adjustments')::numeric,gst_net=(calc->>'gst_net')::numeric,snapshot=calc,accounting_basis=calc->>'basis',filing_frequency=cfg->>'filing_frequency',statutory_rule_snapshot=jsonb_build_object('country','NZ','standard_rate_percent',15),registration_snapshot=cfg,review_items=calc->'review_items',calculation_version='v61.70e-p3',finalised_at=case when p_status='finalised' then now() else null end,finalised_by=case when p_status='finalised' then auth.uid() else null end,updated_at=now(),updated_by=auth.uid() where id=r.id returning * into r;
 else
  insert into gst_returns(business_id,period_start,period_end,status,gst_rate,taxable_sales_ex_gst,gst_collected,taxable_purchases_ex_gst,gst_paid,debit_adjustments,credit_adjustments,gst_net,snapshot,accounting_basis,filing_frequency,statutory_rule_snapshot,registration_snapshot,review_items,calculation_version,finalised_at,finalised_by,created_by,updated_by)
  values(bid,p_from,p_to,p_status,15,(calc->>'sales_ex_gst')::numeric,(calc->>'gst_collected')::numeric,(calc->>'purchases_ex_gst')::numeric,(calc->>'gst_paid')::numeric,(calc->>'debit_adjustments')::numeric,(calc->>'credit_adjustments')::numeric,(calc->>'gst_net')::numeric,calc,calc->>'basis',cfg->>'filing_frequency',jsonb_build_object('country','NZ','standard_rate_percent',15),cfg,calc->'review_items','v61.70e-p3',case when p_status='finalised' then now() end,case when p_status='finalised' then auth.uid() end,auth.uid(),auth.uid()) returning * into r;
 end if;
 if p_status='finalised' then update gst_adjustments set included_return_id=r.id,updated_at=now(),updated_by=auth.uid() where business_id=bid and status='active' and adjustment_date between p_from and p_to and included_return_id is null;end if;
 return r;
end$$;

revoke all on function public.v6170e_gst_calculate(date,date),public.v6170e_save_gst_return(date,date,text) from public,anon;
grant execute on function public.v6170e_gst_calculate(date,date),public.v6170e_save_gst_return(date,date,text) to authenticated;
