import {PRODUCT_KNOWLEDGE_VERSION, PRODUCT_GUIDANCE_RULES, MODULE_LABELS, PRODUCT_KNOWLEDGE} from "./product-knowledge.js";
import {createClient} from "https://esm.sh/@supabase/supabase-js@2";
const VERSION="v61.71B-P6";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...cors,"Content-Type":"application/json"}});
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"Method not allowed"},405);
 const url=Deno.env.get("SUPABASE_URL"),anon=Deno.env.get("SUPABASE_ANON_KEY"),service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),key=Deno.env.get("OPENAI_API_KEY");if(!url||!anon||!service||!key)return json({error:"Live Voice is temporarily unavailable."},503);
 const auth=req.headers.get("Authorization")||"",client=createClient(url,anon,{global:{headers:{Authorization:auth}}}),admin=createClient(url,service);
 try{const {data:{user}}=await client.auth.getUser();if(!user)return json({error:"Not authenticated"},401);const body=await req.json();const {data:bid,error:be}=await client.rpc("current_business_id");if(be||!bid)return json({error:"No active business context."},403);if(body?.business_id&&String(body.business_id)!==String(bid))return json({error:"Business context changed."},409);
 const {data:status,error:se}=await client.rpc("v6171b_p6_live_voice_status");if(se)throw se;if(!status?.global_enabled||status?.emergency_disabled)return json({error:"Finlo Live Voice is currently unavailable."},503);if(!status?.entitled)return json({error:"Finlo Live Voice is not included for this business."},403);if(Number(status?.remaining_sessions||0)<=0)return json({error:"Live Voice session allowance reached.",status},429);
 const module=String(body?.context?.module||"dashboard").slice(0,50),label=MODULE_LABELS[module]||module,country=String(body?.context?.country||"NZ").slice(0,2);
 const knowledge=PRODUCT_KNOWLEDGE.map((k:any)=>({id:k.id,title:k.title,module:k.module,navigation:k.navigation,facts:k.facts,procedure:k.procedure}));
 const instructions=`You are Finlo Live Voice, the realtime voice form of Finlo Helper. Be friendly, concise, practical and easy to understand. You provide guidance only: never claim to create/send invoices, record expenses, reconcile bank transactions, run payroll, change settings/subscriptions, finalise GST/BAS, post journals, delete records, or take financial actions. Current Finlo context: module ${label}; country ${country}. ${PRODUCT_GUIDANCE_RULES} Authoritative Finlo Product Knowledge version ${PRODUCT_KNOWLEDGE_VERSION}: ${JSON.stringify(knowledge)}`;
 const offer=String(body?.sdp||"");if(!offer||offer.length>100000)return json({error:"Invalid WebRTC offer."},400);
 const session={type:"realtime",model:status.model,instructions,audio:{output:{voice:status.voice},input:{turn_detection:{type:"semantic_vad",create_response:true,interrupt_response:true}}}};
 const form=new FormData();form.set("sdp",offer);form.set("session",JSON.stringify(session));
 const r=await fetch("https://api.openai.com/v1/realtime/calls",{method:"POST",headers:{Authorization:`Bearer ${key}`},body:form});const answer=await r.text();if(!r.ok)return json({error:"Live Voice connection could not be created.",provider_status:r.status},502);
 const usageId=crypto.randomUUID();await admin.from("finlo_live_voice_usage").insert({id:usageId,business_id:bid,user_id:user.id,model:status.model,status:"started"});
 return new Response(answer,{status:201,headers:{...cors,"Content-Type":"application/sdp","X-Finlo-Live-Version":VERSION,"X-Finlo-Usage-Id":usageId,"X-Finlo-Max-Session-Minutes":String(status.max_session_minutes)}});
 }catch(e){return json({error:"Finlo Live Voice is unavailable right now."},503)}});
