-- Frindly v61.105 Phase 13I — read-only accountant handoff integrity.
-- Applied live as migration v61105_phase13i_accountant_handoff_integrity.
-- No transaction, journal, GST/BAS, payroll, asset or historical source records are mutated.
create or replace function public.v61105_phase13i_accountant_handoff(p_from date,p_to date) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare b uuid:=public.current_business_id();v_uid uuid:=auth.uid();v_gl_debit numeric:=0;v_gl_credit numeric:=0;v_tb_debit numeric:=0;v_tb_credit numeric:=0;v_revenue numeric:=0;v_cos numeric:=0;v_expenses numeric:=0;v_profit numeric:=0;v_assets numeric:=0;v_liabilities numeric:=0;v_equity numeric:=0;v_bs_profit numeric:=0;v_bs_balances boolean:=false;v_opening text;v_recon jsonb;v_gl_balanced boolean;v_tb_balanced boolean;v_pnl_formula boolean;v_bs_equation boolean;v_ready boolean;
begin
 if v_uid is null or b is null or p_from is null or p_to is null or p_from>p_to then raise exception 'Choose a business and valid handoff period';end if;
 if not public.v6169a_accountant_centre_access(b,false) then raise exception 'Accounting access denied';end if;
 select coalesce(round(sum(l.debit),2),0),coalesce(round(sum(l.credit),2),0) into v_gl_debit,v_gl_credit from public.accounting_journals j join public.accounting_journal_lines l on l.journal_id=j.id and l.business_id=j.business_id where j.business_id=b and j.status in('posted','reversed') and j.journal_date between p_from and p_to;
 select coalesce(round(sum(t.debits),2),0),coalesce(round(sum(t.credits),2),0) into v_tb_debit,v_tb_credit from public.v6170b_trial_balance(p_from,p_to)t;
 select coalesce(revenue,0),coalesce(cost_of_sales,0),coalesce(expenses,0),coalesce(net_profit,0) into v_revenue,v_cos,v_expenses,v_profit from public.v6170b_profit_loss(p_from,p_to);
 select coalesce(assets,0),coalesce(liabilities,0),coalesce(equity,0),coalesce(current_profit,0),coalesce(balances,false),opening_balance_message into v_assets,v_liabilities,v_equity,v_bs_profit,v_bs_balances,v_opening from public.v6170b_balance_sheet(p_to);
 v_recon:=public.v61105_ledger_reconciliation(p_from,p_to);
 v_gl_balanced:=v_gl_debit=v_gl_credit;v_tb_balanced:=v_tb_debit=v_tb_credit and v_tb_debit=v_gl_debit and v_tb_credit=v_gl_credit;v_pnl_formula:=round(v_revenue-v_cos-v_expenses,2)=round(v_profit,2);v_bs_equation:=round(v_assets,2)=round(v_liabilities+v_equity+v_bs_profit,2) and v_bs_balances;
 v_ready:=v_gl_balanced and v_tb_balanced and v_pnl_formula and v_bs_equation and coalesce((v_recon->>'critical_integrity_count')::int,0)=0 and coalesce((v_recon->>'posting_pending_count')::int,0)=0 and coalesce((v_recon->>'review_required_count')::int,0)=0;
 return jsonb_build_object('version','v61.105-phase13i','business_id',b,'period_start',p_from,'period_end',p_to,'handoff_ready',v_ready,'checks',jsonb_build_object('gl_balanced',v_gl_balanced,'trial_balance_matches_gl',v_tb_balanced,'pnl_formula_balanced',v_pnl_formula,'balance_sheet_balanced',v_bs_equation),'general_ledger',jsonb_build_object('debits',v_gl_debit,'credits',v_gl_credit),'trial_balance',jsonb_build_object('debits',v_tb_debit,'credits',v_tb_credit),'profit_and_loss',jsonb_build_object('revenue',v_revenue,'cost_of_sales',v_cos,'expenses',v_expenses,'net_profit',v_profit),'balance_sheet',jsonb_build_object('assets',v_assets,'liabilities',v_liabilities,'equity',v_equity,'current_profit',v_bs_profit,'opening_balance_message',v_opening),'exceptions',jsonb_build_object('issue_count',coalesce((v_recon->>'issue_count')::int,0),'posting_pending_count',coalesce((v_recon->>'posting_pending_count')::int,0),'legacy_review_count',coalesce((v_recon->>'legacy_review_count')::int,0),'review_required_count',coalesce((v_recon->>'review_required_count')::int,0),'critical_integrity_count',coalesce((v_recon->>'critical_integrity_count')::int,0)));
end $$;
revoke execute on function public.v61105_phase13i_accountant_handoff(date,date) from public,anon;
grant execute on function public.v61105_phase13i_accountant_handoff(date,date) to authenticated;
