-- Phase 13M: append-only legacy payroll accounting acknowledgement workflow.
-- Does not modify payroll, bank transactions, journals, PAYE, payslips or closed periods.
create table if not exists public.accounting_legacy_payroll_resolution_events(
 id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade,
 pay_run_id uuid not null references public.payroll_pay_runs(id) on delete cascade,event_type text not null check(event_type in('resolve','reopen')),
 treatment text,note text not null,created_at timestamptz not null default now(),created_by uuid not null references auth.users(id),
 constraint legacy_payroll_resolution_treatment_ck check((event_type='reopen' and treatment is null) or (event_type='resolve' and treatment in('historical_record_acknowledged','handled_in_opening_balance','verified_outside_frindly'))),
 constraint legacy_payroll_resolution_note_ck check(length(btrim(note))>=10));
alter table public.accounting_legacy_payroll_resolution_events enable row level security;
create index if not exists accounting_legacy_payroll_resolution_events_lookup_idx on public.accounting_legacy_payroll_resolution_events(business_id,pay_run_id,created_at desc,id desc);
drop policy if exists legacy_payroll_resolution_select on public.accounting_legacy_payroll_resolution_events;
create policy legacy_payroll_resolution_select on public.accounting_legacy_payroll_resolution_events for select to authenticated using (business_id=public.current_business_id() and public.v6169a_accountant_centre_access(business_id,false));
revoke all on public.accounting_legacy_payroll_resolution_events from anon;grant select on public.accounting_legacy_payroll_resolution_events to authenticated;

create or replace function public.v61105_phase13m_resolve_legacy_payroll(p_pay_run_id uuid,p_treatment text,p_note text) returns jsonb language plpgsql security definer set search_path='' as $$
declare b uuid:=public.current_business_id();u uuid:=auth.uid();p public.payroll_pay_runs;begin
 if u is null or b is null then raise exception 'Choose a business and sign in';end if;if not public.v6169a_accountant_centre_access(b,false) then raise exception 'Accounting access denied';end if;
 if p_treatment not in('historical_record_acknowledged','handled_in_opening_balance','verified_outside_frindly') then raise exception 'Invalid legacy payroll treatment';end if;if length(btrim(coalesce(p_note,'')))<10 then raise exception 'Add a clear resolution note (at least 10 characters)';end if;
 select * into p from public.payroll_pay_runs where id=p_pay_run_id and business_id=b;if p.id is null then raise exception 'Pay run not found in current business';end if;
 if p.status not in('finalised','reversed') or p.finalised_at is null or p.finalised_at>=timestamp '2026-10-01' then raise exception 'Only pre-ledger legacy payroll runs can use this workflow';end if;
 if exists(select 1 from public.accounting_journals j where j.business_id=b and j.source_type='payroll' and j.source_id=p.id and j.status in('posted','reversed')) then raise exception 'This payroll run already has a formal journal';end if;
 insert into public.accounting_legacy_payroll_resolution_events(business_id,pay_run_id,event_type,treatment,note,created_by) values(b,p.id,'resolve',p_treatment,btrim(p_note),u);
 return jsonb_build_object('resolved',true,'pay_run_id',p.id,'pay_run_number',p.pay_run_number,'treatment',p_treatment,'journal_created',false,'payroll_changed',false);end$$;
revoke execute on function public.v61105_phase13m_resolve_legacy_payroll(uuid,text,text) from public,anon;grant execute on function public.v61105_phase13m_resolve_legacy_payroll(uuid,text,text) to authenticated;

create or replace function public.v61105_phase13m_reopen_legacy_payroll(p_pay_run_id uuid,p_note text) returns jsonb language plpgsql security definer set search_path='' as $$
declare b uuid:=public.current_business_id();u uuid:=auth.uid();p public.payroll_pay_runs;begin
 if u is null or b is null then raise exception 'Choose a business and sign in';end if;if not public.v6169a_accountant_centre_access(b,false) then raise exception 'Accounting access denied';end if;if length(btrim(coalesce(p_note,'')))<10 then raise exception 'Add a clear reopen note (at least 10 characters)';end if;
 select * into p from public.payroll_pay_runs where id=p_pay_run_id and business_id=b;if p.id is null then raise exception 'Pay run not found in current business';end if;
 if not exists(select 1 from (select event_type from public.accounting_legacy_payroll_resolution_events where business_id=b and pay_run_id=p.id order by created_at desc,id desc limit 1)x where event_type='resolve') then raise exception 'This legacy payroll run is not currently resolved';end if;
 insert into public.accounting_legacy_payroll_resolution_events(business_id,pay_run_id,event_type,treatment,note,created_by) values(b,p.id,'reopen',null,btrim(p_note),u);
 return jsonb_build_object('resolved',false,'pay_run_id',p.id,'pay_run_number',p.pay_run_number,'journal_created',false,'payroll_changed',false);end$$;
revoke execute on function public.v61105_phase13m_reopen_legacy_payroll(uuid,text) from public,anon;grant execute on function public.v61105_phase13m_reopen_legacy_payroll(uuid,text) to authenticated;

-- Reconciliation: a legacy payroll exception is cleared only when its latest audit event is resolve.
do $$declare d text;begin select pg_get_functiondef(p.oid) into d from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='v61105_ledger_reconciliation';if d is null or strpos(d,'and not exists(select 1 from public.accounting_journals j where j.business_id=b and j.source_type=''payroll'' and j.source_id=p.id and j.status in(''posted'',''reversed''))')=0 then raise exception '13M reconciliation patch guard failed';end if;d:=replace(d,'and not exists(select 1 from public.accounting_journals j where j.business_id=b and j.source_type=''payroll'' and j.source_id=p.id and j.status in(''posted'',''reversed''))','and not exists(select 1 from public.accounting_journals j where j.business_id=b and j.source_type=''payroll'' and j.source_id=p.id and j.status in(''posted'',''reversed'')) and not exists(select 1 from lateral (select e.event_type from public.accounting_legacy_payroll_resolution_events e where e.business_id=b and e.pay_run_id=p.id order by e.created_at desc,e.id desc limit 1) lr where lr.event_type=''resolve'')');d:=replace(d,'''v61.105-phase13l''','''v61.105-phase13m''');execute d;end$$;
revoke execute on function public.v61105_ledger_reconciliation(date,date) from public,anon;grant execute on function public.v61105_ledger_reconciliation(date,date) to authenticated;

create or replace function public.v61105_phase13l_legacy_payroll_review(p_from date,p_to date) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare b uuid:=public.current_business_id();v jsonb;begin if auth.uid() is null or b is null or p_from is null or p_to is null or p_from>p_to then raise exception 'Choose a business and valid review period';end if;if not public.v6169a_accountant_centre_access(b,false) then raise exception 'Accounting access denied';end if;
 with runs as(select p.id,p.pay_run_number,p.pay_date,round(p.gross_pay,2) gross_pay,round(p.total_deductions,2) deductions,round(p.net_pay,2) net_pay,round(p.total_employment_cost,2) employment_cost,round(coalesce(sum(e.reimbursements),0),2) reimbursements,round(p.gross_pay-p.total_deductions+coalesce(sum(e.reimbursements),0),2) expected_net,count(e.id) employee_count,(select count(*) from public.bank_transactions bt where bt.business_id=b and bt.amount=-p.net_pay and bt.transaction_date between p.pay_date-7 and p.pay_date+7) exact_bank_candidates from public.payroll_pay_runs p left join public.payroll_pay_run_employees e on e.pay_run_id=p.id and e.business_id=p.business_id where p.business_id=b and p.pay_date between p_from and p_to and p.status in('finalised','reversed') and p.finalised_at<timestamp '2026-10-01' and not exists(select 1 from public.accounting_journals j where j.business_id=b and j.source_type='payroll' and j.source_id=p.id and j.status in('posted','reversed')) group by p.id),enriched as(select r.*,lr.event_type resolution_event,lr.treatment resolution_treatment,lr.note resolution_note,lr.created_at resolved_at,lr.created_by resolved_by from runs r left join lateral(select e.event_type,e.treatment,e.note,e.created_at,e.created_by from public.accounting_legacy_payroll_resolution_events e where e.business_id=b and e.pay_run_id=r.id order by e.created_at desc,e.id desc limit 1)lr on true)
 select jsonb_build_object('version','v61.105-phase13m','business_id',b,'period_start',p_from,'period_end',p_to,'legacy_payroll_count',count(*),'resolved_count',count(*) filter(where resolution_event='resolve'),'unresolved_count',count(*) filter(where resolution_event is distinct from 'resolve'),'arithmetically_consistent_count',count(*) filter(where abs(net_pay-expected_net)<=0.005),'bank_evidence_found_count',count(*) filter(where exact_bank_candidates>0),'posting_recommendation','do_not_auto_post_without_independent_cash_evidence','runs',coalesce(jsonb_agg(jsonb_build_object('pay_run_id',id,'pay_run_number',pay_run_number,'pay_date',pay_date,'gross_pay',gross_pay,'deductions',deductions,'reimbursements',reimbursements,'net_pay',net_pay,'expected_net',expected_net,'employment_cost',employment_cost,'employee_count',employee_count,'arithmetically_consistent',abs(net_pay-expected_net)<=0.005,'exact_bank_candidates',exact_bank_candidates,'resolved',resolution_event='resolve','resolution_treatment',resolution_treatment,'resolution_note',resolution_note,'resolved_at',resolved_at,'resolved_by',resolved_by,'classification',case when resolution_event='resolve' then 'legacy_payroll_resolved_by_documented_treatment' when abs(net_pay-expected_net)>0.005 then 'legacy_payroll_data_review' when exact_bank_candidates=0 then 'legacy_payroll_unverified_cash_history' else 'legacy_payroll_bank_evidence_available' end) order by pay_date,pay_run_number),'[]'::jsonb)) into v from enriched;return v;end$$;
revoke execute on function public.v61105_phase13l_legacy_payroll_review(date,date) from public,anon;grant execute on function public.v61105_phase13l_legacy_payroll_review(date,date) to authenticated;

do $$declare d text;begin select pg_get_functiondef(p.oid) into d from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='v61105_phase13i_accountant_handoff';if d is null then raise exception '13M handoff function missing';end if;d:=replace(d,'''v61.105-phase13l''','''v61.105-phase13m''');execute d;end$$;
